//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace KIT_ERP.BuyingOutside {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class dsOutSideDelivery : DataSet {
        
        private OO_HTDataTable tableOO_HT;
        
        public dsOutSideDelivery() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected dsOutSideDelivery(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["OO_HT"] != null)) {
                    this.Tables.Add(new OO_HTDataTable(ds.Tables["OO_HT"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public OO_HTDataTable OO_HT {
            get {
                return this.tableOO_HT;
            }
        }
        
        public override DataSet Clone() {
            dsOutSideDelivery cln = ((dsOutSideDelivery)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["OO_HT"] != null)) {
                this.Tables.Add(new OO_HTDataTable(ds.Tables["OO_HT"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableOO_HT = ((OO_HTDataTable)(this.Tables["OO_HT"]));
            if ((this.tableOO_HT != null)) {
                this.tableOO_HT.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "dsOutSideDelivery";
            this.Prefix = "";
            this.Namespace = "http://www.tempuri.org/dsOutSideDelivery.xsd";
            this.Locale = new System.Globalization.CultureInfo("ko-KR");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableOO_HT = new OO_HTDataTable();
            this.Tables.Add(this.tableOO_HT);
        }
        
        private bool ShouldSerializeOO_HT() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void OO_HTRowChangeEventHandler(object sender, OO_HTRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class OO_HTDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnItemNum;
            
            private DataColumn columnItemDrawNum;
            
            private DataColumn columnItemName;
            
            private DataColumn columnUnitCostDistinction;
            
            private DataColumn columnBeginProcessCode;
            
            private DataColumn columnBeginProcess;
            
            private DataColumn columnEndProcessCode;
            
            private DataColumn columnEndProcess;
            
            private DataColumn columnCompanyName;
            
            private DataColumn columnBusinessRegistrationNum;
            
            private DataColumn columnOrderRate;
            
            private DataColumn columnFirstDeliveryDemandQuantity;
            
            private DataColumn columnFirstDeliveryDemandDate;
            
            private DataColumn columnSecondDeliveryDemandQuantity;
            
            private DataColumn columnSecondDeliveryDemandDate;
            
            private DataColumn columnThirdDeliveryDemandQuantity;
            
            private DataColumn columnThirdDeliveryDemandDate;
            
            private DataColumn columnFourthDeliveryDemandQuantity;
            
            private DataColumn columnFourthDeliveryDemandDate;
            
            private DataColumn columnFifthDeliveryDemandQuantity;
            
            private DataColumn columnFifthDeliveryDemandDate;
            
            private DataColumn columnOrderQuantity;
            
            private DataColumn columnApplyUnitCost;
            
            private DataColumn columnTotalCost;
            
            private DataColumn columnRemainQuantity;
            
            private DataColumn columnVolumNum;
            
            private DataColumn columnProgressCondition;
            
            private DataColumn columnRegistrationPerson;
            
            private DataColumn columnRegistrationPersonID;
            
            private DataColumn columnRegistrationDate;
            
            private DataColumn columnUpdatingPerson;
            
            private DataColumn columnUpdatingPersonID;
            
            private DataColumn columnUpdatingDate;
            
            private DataColumn columnOutSideOrderRequestHistoryIndex;
            
            private DataColumn columnOutSideOrderHistoryIndex;
            
            internal OO_HTDataTable() : 
                    base("OO_HT") {
                this.InitClass();
            }
            
            internal OO_HTDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn ItemNumColumn {
                get {
                    return this.columnItemNum;
                }
            }
            
            internal DataColumn ItemDrawNumColumn {
                get {
                    return this.columnItemDrawNum;
                }
            }
            
            internal DataColumn ItemNameColumn {
                get {
                    return this.columnItemName;
                }
            }
            
            internal DataColumn UnitCostDistinctionColumn {
                get {
                    return this.columnUnitCostDistinction;
                }
            }
            
            internal DataColumn BeginProcessCodeColumn {
                get {
                    return this.columnBeginProcessCode;
                }
            }
            
            internal DataColumn BeginProcessColumn {
                get {
                    return this.columnBeginProcess;
                }
            }
            
            internal DataColumn EndProcessCodeColumn {
                get {
                    return this.columnEndProcessCode;
                }
            }
            
            internal DataColumn EndProcessColumn {
                get {
                    return this.columnEndProcess;
                }
            }
            
            internal DataColumn CompanyNameColumn {
                get {
                    return this.columnCompanyName;
                }
            }
            
            internal DataColumn BusinessRegistrationNumColumn {
                get {
                    return this.columnBusinessRegistrationNum;
                }
            }
            
            internal DataColumn OrderRateColumn {
                get {
                    return this.columnOrderRate;
                }
            }
            
            internal DataColumn FirstDeliveryDemandQuantityColumn {
                get {
                    return this.columnFirstDeliveryDemandQuantity;
                }
            }
            
            internal DataColumn FirstDeliveryDemandDateColumn {
                get {
                    return this.columnFirstDeliveryDemandDate;
                }
            }
            
            internal DataColumn SecondDeliveryDemandQuantityColumn {
                get {
                    return this.columnSecondDeliveryDemandQuantity;
                }
            }
            
            internal DataColumn SecondDeliveryDemandDateColumn {
                get {
                    return this.columnSecondDeliveryDemandDate;
                }
            }
            
            internal DataColumn ThirdDeliveryDemandQuantityColumn {
                get {
                    return this.columnThirdDeliveryDemandQuantity;
                }
            }
            
            internal DataColumn ThirdDeliveryDemandDateColumn {
                get {
                    return this.columnThirdDeliveryDemandDate;
                }
            }
            
            internal DataColumn FourthDeliveryDemandQuantityColumn {
                get {
                    return this.columnFourthDeliveryDemandQuantity;
                }
            }
            
            internal DataColumn FourthDeliveryDemandDateColumn {
                get {
                    return this.columnFourthDeliveryDemandDate;
                }
            }
            
            internal DataColumn FifthDeliveryDemandQuantityColumn {
                get {
                    return this.columnFifthDeliveryDemandQuantity;
                }
            }
            
            internal DataColumn FifthDeliveryDemandDateColumn {
                get {
                    return this.columnFifthDeliveryDemandDate;
                }
            }
            
            internal DataColumn OrderQuantityColumn {
                get {
                    return this.columnOrderQuantity;
                }
            }
            
            internal DataColumn ApplyUnitCostColumn {
                get {
                    return this.columnApplyUnitCost;
                }
            }
            
            internal DataColumn TotalCostColumn {
                get {
                    return this.columnTotalCost;
                }
            }
            
            internal DataColumn RemainQuantityColumn {
                get {
                    return this.columnRemainQuantity;
                }
            }
            
            internal DataColumn VolumNumColumn {
                get {
                    return this.columnVolumNum;
                }
            }
            
            internal DataColumn ProgressConditionColumn {
                get {
                    return this.columnProgressCondition;
                }
            }
            
            internal DataColumn RegistrationPersonColumn {
                get {
                    return this.columnRegistrationPerson;
                }
            }
            
            internal DataColumn RegistrationPersonIDColumn {
                get {
                    return this.columnRegistrationPersonID;
                }
            }
            
            internal DataColumn RegistrationDateColumn {
                get {
                    return this.columnRegistrationDate;
                }
            }
            
            internal DataColumn UpdatingPersonColumn {
                get {
                    return this.columnUpdatingPerson;
                }
            }
            
            internal DataColumn UpdatingPersonIDColumn {
                get {
                    return this.columnUpdatingPersonID;
                }
            }
            
            internal DataColumn UpdatingDateColumn {
                get {
                    return this.columnUpdatingDate;
                }
            }
            
            internal DataColumn OutSideOrderRequestHistoryIndexColumn {
                get {
                    return this.columnOutSideOrderRequestHistoryIndex;
                }
            }
            
            internal DataColumn OutSideOrderHistoryIndexColumn {
                get {
                    return this.columnOutSideOrderHistoryIndex;
                }
            }
            
            public OO_HTRow this[int index] {
                get {
                    return ((OO_HTRow)(this.Rows[index]));
                }
            }
            
            public event OO_HTRowChangeEventHandler OO_HTRowChanged;
            
            public event OO_HTRowChangeEventHandler OO_HTRowChanging;
            
            public event OO_HTRowChangeEventHandler OO_HTRowDeleted;
            
            public event OO_HTRowChangeEventHandler OO_HTRowDeleting;
            
            public void AddOO_HTRow(OO_HTRow row) {
                this.Rows.Add(row);
            }
            
            public OO_HTRow AddOO_HTRow(
                        string ItemNum, 
                        string ItemDrawNum, 
                        string ItemName, 
                        string UnitCostDistinction, 
                        string BeginProcessCode, 
                        string BeginProcess, 
                        string EndProcessCode, 
                        string EndProcess, 
                        string CompanyName, 
                        string BusinessRegistrationNum, 
                        System.Decimal OrderRate, 
                        System.Decimal FirstDeliveryDemandQuantity, 
                        System.DateTime FirstDeliveryDemandDate, 
                        System.Decimal SecondDeliveryDemandQuantity, 
                        System.DateTime SecondDeliveryDemandDate, 
                        System.Decimal ThirdDeliveryDemandQuantity, 
                        System.DateTime ThirdDeliveryDemandDate, 
                        System.Decimal FourthDeliveryDemandQuantity, 
                        System.DateTime FourthDeliveryDemandDate, 
                        System.Decimal FifthDeliveryDemandQuantity, 
                        System.DateTime FifthDeliveryDemandDate, 
                        System.Decimal OrderQuantity, 
                        System.Decimal ApplyUnitCost, 
                        System.Decimal TotalCost, 
                        System.Decimal RemainQuantity, 
                        int VolumNum, 
                        string ProgressCondition, 
                        string RegistrationPerson, 
                        string RegistrationPersonID, 
                        System.DateTime RegistrationDate, 
                        string UpdatingPerson, 
                        string UpdatingPersonID, 
                        System.DateTime UpdatingDate, 
                        int OutSideOrderRequestHistoryIndex) {
                OO_HTRow rowOO_HTRow = ((OO_HTRow)(this.NewRow()));
                rowOO_HTRow.ItemArray = new object[] {
                        ItemNum,
                        ItemDrawNum,
                        ItemName,
                        UnitCostDistinction,
                        BeginProcessCode,
                        BeginProcess,
                        EndProcessCode,
                        EndProcess,
                        CompanyName,
                        BusinessRegistrationNum,
                        OrderRate,
                        FirstDeliveryDemandQuantity,
                        FirstDeliveryDemandDate,
                        SecondDeliveryDemandQuantity,
                        SecondDeliveryDemandDate,
                        ThirdDeliveryDemandQuantity,
                        ThirdDeliveryDemandDate,
                        FourthDeliveryDemandQuantity,
                        FourthDeliveryDemandDate,
                        FifthDeliveryDemandQuantity,
                        FifthDeliveryDemandDate,
                        OrderQuantity,
                        ApplyUnitCost,
                        TotalCost,
                        RemainQuantity,
                        VolumNum,
                        ProgressCondition,
                        RegistrationPerson,
                        RegistrationPersonID,
                        RegistrationDate,
                        UpdatingPerson,
                        UpdatingPersonID,
                        UpdatingDate,
                        OutSideOrderRequestHistoryIndex,
                        null};
                this.Rows.Add(rowOO_HTRow);
                return rowOO_HTRow;
            }
            
            public OO_HTRow FindByOutSideOrderHistoryIndex(int OutSideOrderHistoryIndex) {
                return ((OO_HTRow)(this.Rows.Find(new object[] {
                            OutSideOrderHistoryIndex})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                OO_HTDataTable cln = ((OO_HTDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new OO_HTDataTable();
            }
            
            internal void InitVars() {
                this.columnItemNum = this.Columns["ItemNum"];
                this.columnItemDrawNum = this.Columns["ItemDrawNum"];
                this.columnItemName = this.Columns["ItemName"];
                this.columnUnitCostDistinction = this.Columns["UnitCostDistinction"];
                this.columnBeginProcessCode = this.Columns["BeginProcessCode"];
                this.columnBeginProcess = this.Columns["BeginProcess"];
                this.columnEndProcessCode = this.Columns["EndProcessCode"];
                this.columnEndProcess = this.Columns["EndProcess"];
                this.columnCompanyName = this.Columns["CompanyName"];
                this.columnBusinessRegistrationNum = this.Columns["BusinessRegistrationNum"];
                this.columnOrderRate = this.Columns["OrderRate"];
                this.columnFirstDeliveryDemandQuantity = this.Columns["FirstDeliveryDemandQuantity"];
                this.columnFirstDeliveryDemandDate = this.Columns["FirstDeliveryDemandDate"];
                this.columnSecondDeliveryDemandQuantity = this.Columns["SecondDeliveryDemandQuantity"];
                this.columnSecondDeliveryDemandDate = this.Columns["SecondDeliveryDemandDate"];
                this.columnThirdDeliveryDemandQuantity = this.Columns["ThirdDeliveryDemandQuantity"];
                this.columnThirdDeliveryDemandDate = this.Columns["ThirdDeliveryDemandDate"];
                this.columnFourthDeliveryDemandQuantity = this.Columns["FourthDeliveryDemandQuantity"];
                this.columnFourthDeliveryDemandDate = this.Columns["FourthDeliveryDemandDate"];
                this.columnFifthDeliveryDemandQuantity = this.Columns["FifthDeliveryDemandQuantity"];
                this.columnFifthDeliveryDemandDate = this.Columns["FifthDeliveryDemandDate"];
                this.columnOrderQuantity = this.Columns["OrderQuantity"];
                this.columnApplyUnitCost = this.Columns["ApplyUnitCost"];
                this.columnTotalCost = this.Columns["TotalCost"];
                this.columnRemainQuantity = this.Columns["RemainQuantity"];
                this.columnVolumNum = this.Columns["VolumNum"];
                this.columnProgressCondition = this.Columns["ProgressCondition"];
                this.columnRegistrationPerson = this.Columns["RegistrationPerson"];
                this.columnRegistrationPersonID = this.Columns["RegistrationPersonID"];
                this.columnRegistrationDate = this.Columns["RegistrationDate"];
                this.columnUpdatingPerson = this.Columns["UpdatingPerson"];
                this.columnUpdatingPersonID = this.Columns["UpdatingPersonID"];
                this.columnUpdatingDate = this.Columns["UpdatingDate"];
                this.columnOutSideOrderRequestHistoryIndex = this.Columns["OutSideOrderRequestHistoryIndex"];
                this.columnOutSideOrderHistoryIndex = this.Columns["OutSideOrderHistoryIndex"];
            }
            
            private void InitClass() {
                this.columnItemNum = new DataColumn("ItemNum", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnItemNum);
                this.columnItemDrawNum = new DataColumn("ItemDrawNum", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnItemDrawNum);
                this.columnItemName = new DataColumn("ItemName", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnItemName);
                this.columnUnitCostDistinction = new DataColumn("UnitCostDistinction", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnUnitCostDistinction);
                this.columnBeginProcessCode = new DataColumn("BeginProcessCode", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnBeginProcessCode);
                this.columnBeginProcess = new DataColumn("BeginProcess", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnBeginProcess);
                this.columnEndProcessCode = new DataColumn("EndProcessCode", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnEndProcessCode);
                this.columnEndProcess = new DataColumn("EndProcess", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnEndProcess);
                this.columnCompanyName = new DataColumn("CompanyName", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnCompanyName);
                this.columnBusinessRegistrationNum = new DataColumn("BusinessRegistrationNum", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnBusinessRegistrationNum);
                this.columnOrderRate = new DataColumn("OrderRate", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnOrderRate);
                this.columnFirstDeliveryDemandQuantity = new DataColumn("FirstDeliveryDemandQuantity", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnFirstDeliveryDemandQuantity);
                this.columnFirstDeliveryDemandDate = new DataColumn("FirstDeliveryDemandDate", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnFirstDeliveryDemandDate);
                this.columnSecondDeliveryDemandQuantity = new DataColumn("SecondDeliveryDemandQuantity", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnSecondDeliveryDemandQuantity);
                this.columnSecondDeliveryDemandDate = new DataColumn("SecondDeliveryDemandDate", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnSecondDeliveryDemandDate);
                this.columnThirdDeliveryDemandQuantity = new DataColumn("ThirdDeliveryDemandQuantity", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnThirdDeliveryDemandQuantity);
                this.columnThirdDeliveryDemandDate = new DataColumn("ThirdDeliveryDemandDate", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnThirdDeliveryDemandDate);
                this.columnFourthDeliveryDemandQuantity = new DataColumn("FourthDeliveryDemandQuantity", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnFourthDeliveryDemandQuantity);
                this.columnFourthDeliveryDemandDate = new DataColumn("FourthDeliveryDemandDate", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnFourthDeliveryDemandDate);
                this.columnFifthDeliveryDemandQuantity = new DataColumn("FifthDeliveryDemandQuantity", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnFifthDeliveryDemandQuantity);
                this.columnFifthDeliveryDemandDate = new DataColumn("FifthDeliveryDemandDate", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnFifthDeliveryDemandDate);
                this.columnOrderQuantity = new DataColumn("OrderQuantity", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnOrderQuantity);
                this.columnApplyUnitCost = new DataColumn("ApplyUnitCost", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnApplyUnitCost);
                this.columnTotalCost = new DataColumn("TotalCost", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnTotalCost);
                this.columnRemainQuantity = new DataColumn("RemainQuantity", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnRemainQuantity);
                this.columnVolumNum = new DataColumn("VolumNum", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnVolumNum);
                this.columnProgressCondition = new DataColumn("ProgressCondition", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnProgressCondition);
                this.columnRegistrationPerson = new DataColumn("RegistrationPerson", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnRegistrationPerson);
                this.columnRegistrationPersonID = new DataColumn("RegistrationPersonID", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnRegistrationPersonID);
                this.columnRegistrationDate = new DataColumn("RegistrationDate", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnRegistrationDate);
                this.columnUpdatingPerson = new DataColumn("UpdatingPerson", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnUpdatingPerson);
                this.columnUpdatingPersonID = new DataColumn("UpdatingPersonID", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnUpdatingPersonID);
                this.columnUpdatingDate = new DataColumn("UpdatingDate", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnUpdatingDate);
                this.columnOutSideOrderRequestHistoryIndex = new DataColumn("OutSideOrderRequestHistoryIndex", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnOutSideOrderRequestHistoryIndex);
                this.columnOutSideOrderHistoryIndex = new DataColumn("OutSideOrderHistoryIndex", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnOutSideOrderHistoryIndex);
                this.Constraints.Add(new UniqueConstraint("Constraint1", new DataColumn[] {
                                this.columnOutSideOrderHistoryIndex}, true));
                this.columnOutSideOrderHistoryIndex.AutoIncrement = true;
                this.columnOutSideOrderHistoryIndex.AllowDBNull = false;
                this.columnOutSideOrderHistoryIndex.ReadOnly = true;
                this.columnOutSideOrderHistoryIndex.Unique = true;
            }
            
            public OO_HTRow NewOO_HTRow() {
                return ((OO_HTRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new OO_HTRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(OO_HTRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.OO_HTRowChanged != null)) {
                    this.OO_HTRowChanged(this, new OO_HTRowChangeEvent(((OO_HTRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.OO_HTRowChanging != null)) {
                    this.OO_HTRowChanging(this, new OO_HTRowChangeEvent(((OO_HTRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.OO_HTRowDeleted != null)) {
                    this.OO_HTRowDeleted(this, new OO_HTRowChangeEvent(((OO_HTRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.OO_HTRowDeleting != null)) {
                    this.OO_HTRowDeleting(this, new OO_HTRowChangeEvent(((OO_HTRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveOO_HTRow(OO_HTRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class OO_HTRow : DataRow {
            
            private OO_HTDataTable tableOO_HT;
            
            internal OO_HTRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableOO_HT = ((OO_HTDataTable)(this.Table));
            }
            
            public string ItemNum {
                get {
                    try {
                        return ((string)(this[this.tableOO_HT.ItemNumColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableOO_HT.ItemNumColumn] = value;
                }
            }
            
            public string ItemDrawNum {
                get {
                    try {
                        return ((string)(this[this.tableOO_HT.ItemDrawNumColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableOO_HT.ItemDrawNumColumn] = value;
                }
            }
            
            public string ItemName {
                get {
                    try {
                        return ((string)(this[this.tableOO_HT.ItemNameColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableOO_HT.ItemNameColumn] = value;
                }
            }
            
            public string UnitCostDistinction {
                get {
                    try {
                        return ((string)(this[this.tableOO_HT.UnitCostDistinctionColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableOO_HT.UnitCostDistinctionColumn] = value;
                }
            }
            
            public string BeginProcessCode {
                get {
                    try {
                        return ((string)(this[this.tableOO_HT.BeginProcessCodeColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableOO_HT.BeginProcessCodeColumn] = value;
                }
            }
            
            public string BeginProcess {
                get {
                    try {
                        return ((string)(this[this.tableOO_HT.BeginProcessColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableOO_HT.BeginProcessColumn] = value;
                }
            }
            
            public string EndProcessCode {
                get {
                    try {
                        return ((string)(this[this.tableOO_HT.EndProcessCodeColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableOO_HT.EndProcessCodeColumn] = value;
                }
            }
            
            public string EndProcess {
                get {
                    try {
                        return ((string)(this[this.tableOO_HT.EndProcessColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableOO_HT.EndProcessColumn] = value;
                }
            }
            
            public string CompanyName {
                get {
                    try {
                        return ((string)(this[this.tableOO_HT.CompanyNameColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableOO_HT.CompanyNameColumn] = value;
                }
            }
            
            public string BusinessRegistrationNum {
                get {
                    try {
                        return ((string)(this[this.tableOO_HT.BusinessRegistrationNumColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableOO_HT.BusinessRegistrationNumColumn] = value;
                }
            }
            
            public System.Decimal OrderRate {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableOO_HT.OrderRateColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableOO_HT.OrderRateColumn] = value;
                }
            }
            
            public System.Decimal FirstDeliveryDemandQuantity {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableOO_HT.FirstDeliveryDemandQuantityColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableOO_HT.FirstDeliveryDemandQuantityColumn] = value;
                }
            }
            
            public System.DateTime FirstDeliveryDemandDate {
                get {
                    try {
                        return ((System.DateTime)(this[this.tableOO_HT.FirstDeliveryDemandDateColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableOO_HT.FirstDeliveryDemandDateColumn] = value;
                }
            }
            
            public System.Decimal SecondDeliveryDemandQuantity {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableOO_HT.SecondDeliveryDemandQuantityColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableOO_HT.SecondDeliveryDemandQuantityColumn] = value;
                }
            }
            
            public System.DateTime SecondDeliveryDemandDate {
                get {
                    try {
                        return ((System.DateTime)(this[this.tableOO_HT.SecondDeliveryDemandDateColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableOO_HT.SecondDeliveryDemandDateColumn] = value;
                }
            }
            
            public System.Decimal ThirdDeliveryDemandQuantity {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableOO_HT.ThirdDeliveryDemandQuantityColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableOO_HT.ThirdDeliveryDemandQuantityColumn] = value;
                }
            }
            
            public System.DateTime ThirdDeliveryDemandDate {
                get {
                    try {
                        return ((System.DateTime)(this[this.tableOO_HT.ThirdDeliveryDemandDateColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableOO_HT.ThirdDeliveryDemandDateColumn] = value;
                }
            }
            
            public System.Decimal FourthDeliveryDemandQuantity {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableOO_HT.FourthDeliveryDemandQuantityColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableOO_HT.FourthDeliveryDemandQuantityColumn] = value;
                }
            }
            
            public System.DateTime FourthDeliveryDemandDate {
                get {
                    try {
                        return ((System.DateTime)(this[this.tableOO_HT.FourthDeliveryDemandDateColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableOO_HT.FourthDeliveryDemandDateColumn] = value;
                }
            }
            
            public System.Decimal FifthDeliveryDemandQuantity {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableOO_HT.FifthDeliveryDemandQuantityColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableOO_HT.FifthDeliveryDemandQuantityColumn] = value;
                }
            }
            
            public System.DateTime FifthDeliveryDemandDate {
                get {
                    try {
                        return ((System.DateTime)(this[this.tableOO_HT.FifthDeliveryDemandDateColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableOO_HT.FifthDeliveryDemandDateColumn] = value;
                }
            }
            
            public System.Decimal OrderQuantity {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableOO_HT.OrderQuantityColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableOO_HT.OrderQuantityColumn] = value;
                }
            }
            
            public System.Decimal ApplyUnitCost {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableOO_HT.ApplyUnitCostColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableOO_HT.ApplyUnitCostColumn] = value;
                }
            }
            
            public System.Decimal TotalCost {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableOO_HT.TotalCostColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableOO_HT.TotalCostColumn] = value;
                }
            }
            
            public System.Decimal RemainQuantity {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableOO_HT.RemainQuantityColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableOO_HT.RemainQuantityColumn] = value;
                }
            }
            
            public int VolumNum {
                get {
                    try {
                        return ((int)(this[this.tableOO_HT.VolumNumColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableOO_HT.VolumNumColumn] = value;
                }
            }
            
            public string ProgressCondition {
                get {
                    try {
                        return ((string)(this[this.tableOO_HT.ProgressConditionColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableOO_HT.ProgressConditionColumn] = value;
                }
            }
            
            public string RegistrationPerson {
                get {
                    try {
                        return ((string)(this[this.tableOO_HT.RegistrationPersonColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableOO_HT.RegistrationPersonColumn] = value;
                }
            }
            
            public string RegistrationPersonID {
                get {
                    try {
                        return ((string)(this[this.tableOO_HT.RegistrationPersonIDColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableOO_HT.RegistrationPersonIDColumn] = value;
                }
            }
            
            public System.DateTime RegistrationDate {
                get {
                    try {
                        return ((System.DateTime)(this[this.tableOO_HT.RegistrationDateColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableOO_HT.RegistrationDateColumn] = value;
                }
            }
            
            public string UpdatingPerson {
                get {
                    try {
                        return ((string)(this[this.tableOO_HT.UpdatingPersonColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableOO_HT.UpdatingPersonColumn] = value;
                }
            }
            
            public string UpdatingPersonID {
                get {
                    try {
                        return ((string)(this[this.tableOO_HT.UpdatingPersonIDColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableOO_HT.UpdatingPersonIDColumn] = value;
                }
            }
            
            public System.DateTime UpdatingDate {
                get {
                    try {
                        return ((System.DateTime)(this[this.tableOO_HT.UpdatingDateColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableOO_HT.UpdatingDateColumn] = value;
                }
            }
            
            public int OutSideOrderRequestHistoryIndex {
                get {
                    try {
                        return ((int)(this[this.tableOO_HT.OutSideOrderRequestHistoryIndexColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableOO_HT.OutSideOrderRequestHistoryIndexColumn] = value;
                }
            }
            
            public int OutSideOrderHistoryIndex {
                get {
                    return ((int)(this[this.tableOO_HT.OutSideOrderHistoryIndexColumn]));
                }
                set {
                    this[this.tableOO_HT.OutSideOrderHistoryIndexColumn] = value;
                }
            }
            
            public bool IsItemNumNull() {
                return this.IsNull(this.tableOO_HT.ItemNumColumn);
            }
            
            public void SetItemNumNull() {
                this[this.tableOO_HT.ItemNumColumn] = System.Convert.DBNull;
            }
            
            public bool IsItemDrawNumNull() {
                return this.IsNull(this.tableOO_HT.ItemDrawNumColumn);
            }
            
            public void SetItemDrawNumNull() {
                this[this.tableOO_HT.ItemDrawNumColumn] = System.Convert.DBNull;
            }
            
            public bool IsItemNameNull() {
                return this.IsNull(this.tableOO_HT.ItemNameColumn);
            }
            
            public void SetItemNameNull() {
                this[this.tableOO_HT.ItemNameColumn] = System.Convert.DBNull;
            }
            
            public bool IsUnitCostDistinctionNull() {
                return this.IsNull(this.tableOO_HT.UnitCostDistinctionColumn);
            }
            
            public void SetUnitCostDistinctionNull() {
                this[this.tableOO_HT.UnitCostDistinctionColumn] = System.Convert.DBNull;
            }
            
            public bool IsBeginProcessCodeNull() {
                return this.IsNull(this.tableOO_HT.BeginProcessCodeColumn);
            }
            
            public void SetBeginProcessCodeNull() {
                this[this.tableOO_HT.BeginProcessCodeColumn] = System.Convert.DBNull;
            }
            
            public bool IsBeginProcessNull() {
                return this.IsNull(this.tableOO_HT.BeginProcessColumn);
            }
            
            public void SetBeginProcessNull() {
                this[this.tableOO_HT.BeginProcessColumn] = System.Convert.DBNull;
            }
            
            public bool IsEndProcessCodeNull() {
                return this.IsNull(this.tableOO_HT.EndProcessCodeColumn);
            }
            
            public void SetEndProcessCodeNull() {
                this[this.tableOO_HT.EndProcessCodeColumn] = System.Convert.DBNull;
            }
            
            public bool IsEndProcessNull() {
                return this.IsNull(this.tableOO_HT.EndProcessColumn);
            }
            
            public void SetEndProcessNull() {
                this[this.tableOO_HT.EndProcessColumn] = System.Convert.DBNull;
            }
            
            public bool IsCompanyNameNull() {
                return this.IsNull(this.tableOO_HT.CompanyNameColumn);
            }
            
            public void SetCompanyNameNull() {
                this[this.tableOO_HT.CompanyNameColumn] = System.Convert.DBNull;
            }
            
            public bool IsBusinessRegistrationNumNull() {
                return this.IsNull(this.tableOO_HT.BusinessRegistrationNumColumn);
            }
            
            public void SetBusinessRegistrationNumNull() {
                this[this.tableOO_HT.BusinessRegistrationNumColumn] = System.Convert.DBNull;
            }
            
            public bool IsOrderRateNull() {
                return this.IsNull(this.tableOO_HT.OrderRateColumn);
            }
            
            public void SetOrderRateNull() {
                this[this.tableOO_HT.OrderRateColumn] = System.Convert.DBNull;
            }
            
            public bool IsFirstDeliveryDemandQuantityNull() {
                return this.IsNull(this.tableOO_HT.FirstDeliveryDemandQuantityColumn);
            }
            
            public void SetFirstDeliveryDemandQuantityNull() {
                this[this.tableOO_HT.FirstDeliveryDemandQuantityColumn] = System.Convert.DBNull;
            }
            
            public bool IsFirstDeliveryDemandDateNull() {
                return this.IsNull(this.tableOO_HT.FirstDeliveryDemandDateColumn);
            }
            
            public void SetFirstDeliveryDemandDateNull() {
                this[this.tableOO_HT.FirstDeliveryDemandDateColumn] = System.Convert.DBNull;
            }
            
            public bool IsSecondDeliveryDemandQuantityNull() {
                return this.IsNull(this.tableOO_HT.SecondDeliveryDemandQuantityColumn);
            }
            
            public void SetSecondDeliveryDemandQuantityNull() {
                this[this.tableOO_HT.SecondDeliveryDemandQuantityColumn] = System.Convert.DBNull;
            }
            
            public bool IsSecondDeliveryDemandDateNull() {
                return this.IsNull(this.tableOO_HT.SecondDeliveryDemandDateColumn);
            }
            
            public void SetSecondDeliveryDemandDateNull() {
                this[this.tableOO_HT.SecondDeliveryDemandDateColumn] = System.Convert.DBNull;
            }
            
            public bool IsThirdDeliveryDemandQuantityNull() {
                return this.IsNull(this.tableOO_HT.ThirdDeliveryDemandQuantityColumn);
            }
            
            public void SetThirdDeliveryDemandQuantityNull() {
                this[this.tableOO_HT.ThirdDeliveryDemandQuantityColumn] = System.Convert.DBNull;
            }
            
            public bool IsThirdDeliveryDemandDateNull() {
                return this.IsNull(this.tableOO_HT.ThirdDeliveryDemandDateColumn);
            }
            
            public void SetThirdDeliveryDemandDateNull() {
                this[this.tableOO_HT.ThirdDeliveryDemandDateColumn] = System.Convert.DBNull;
            }
            
            public bool IsFourthDeliveryDemandQuantityNull() {
                return this.IsNull(this.tableOO_HT.FourthDeliveryDemandQuantityColumn);
            }
            
            public void SetFourthDeliveryDemandQuantityNull() {
                this[this.tableOO_HT.FourthDeliveryDemandQuantityColumn] = System.Convert.DBNull;
            }
            
            public bool IsFourthDeliveryDemandDateNull() {
                return this.IsNull(this.tableOO_HT.FourthDeliveryDemandDateColumn);
            }
            
            public void SetFourthDeliveryDemandDateNull() {
                this[this.tableOO_HT.FourthDeliveryDemandDateColumn] = System.Convert.DBNull;
            }
            
            public bool IsFifthDeliveryDemandQuantityNull() {
                return this.IsNull(this.tableOO_HT.FifthDeliveryDemandQuantityColumn);
            }
            
            public void SetFifthDeliveryDemandQuantityNull() {
                this[this.tableOO_HT.FifthDeliveryDemandQuantityColumn] = System.Convert.DBNull;
            }
            
            public bool IsFifthDeliveryDemandDateNull() {
                return this.IsNull(this.tableOO_HT.FifthDeliveryDemandDateColumn);
            }
            
            public void SetFifthDeliveryDemandDateNull() {
                this[this.tableOO_HT.FifthDeliveryDemandDateColumn] = System.Convert.DBNull;
            }
            
            public bool IsOrderQuantityNull() {
                return this.IsNull(this.tableOO_HT.OrderQuantityColumn);
            }
            
            public void SetOrderQuantityNull() {
                this[this.tableOO_HT.OrderQuantityColumn] = System.Convert.DBNull;
            }
            
            public bool IsApplyUnitCostNull() {
                return this.IsNull(this.tableOO_HT.ApplyUnitCostColumn);
            }
            
            public void SetApplyUnitCostNull() {
                this[this.tableOO_HT.ApplyUnitCostColumn] = System.Convert.DBNull;
            }
            
            public bool IsTotalCostNull() {
                return this.IsNull(this.tableOO_HT.TotalCostColumn);
            }
            
            public void SetTotalCostNull() {
                this[this.tableOO_HT.TotalCostColumn] = System.Convert.DBNull;
            }
            
            public bool IsRemainQuantityNull() {
                return this.IsNull(this.tableOO_HT.RemainQuantityColumn);
            }
            
            public void SetRemainQuantityNull() {
                this[this.tableOO_HT.RemainQuantityColumn] = System.Convert.DBNull;
            }
            
            public bool IsVolumNumNull() {
                return this.IsNull(this.tableOO_HT.VolumNumColumn);
            }
            
            public void SetVolumNumNull() {
                this[this.tableOO_HT.VolumNumColumn] = System.Convert.DBNull;
            }
            
            public bool IsProgressConditionNull() {
                return this.IsNull(this.tableOO_HT.ProgressConditionColumn);
            }
            
            public void SetProgressConditionNull() {
                this[this.tableOO_HT.ProgressConditionColumn] = System.Convert.DBNull;
            }
            
            public bool IsRegistrationPersonNull() {
                return this.IsNull(this.tableOO_HT.RegistrationPersonColumn);
            }
            
            public void SetRegistrationPersonNull() {
                this[this.tableOO_HT.RegistrationPersonColumn] = System.Convert.DBNull;
            }
            
            public bool IsRegistrationPersonIDNull() {
                return this.IsNull(this.tableOO_HT.RegistrationPersonIDColumn);
            }
            
            public void SetRegistrationPersonIDNull() {
                this[this.tableOO_HT.RegistrationPersonIDColumn] = System.Convert.DBNull;
            }
            
            public bool IsRegistrationDateNull() {
                return this.IsNull(this.tableOO_HT.RegistrationDateColumn);
            }
            
            public void SetRegistrationDateNull() {
                this[this.tableOO_HT.RegistrationDateColumn] = System.Convert.DBNull;
            }
            
            public bool IsUpdatingPersonNull() {
                return this.IsNull(this.tableOO_HT.UpdatingPersonColumn);
            }
            
            public void SetUpdatingPersonNull() {
                this[this.tableOO_HT.UpdatingPersonColumn] = System.Convert.DBNull;
            }
            
            public bool IsUpdatingPersonIDNull() {
                return this.IsNull(this.tableOO_HT.UpdatingPersonIDColumn);
            }
            
            public void SetUpdatingPersonIDNull() {
                this[this.tableOO_HT.UpdatingPersonIDColumn] = System.Convert.DBNull;
            }
            
            public bool IsUpdatingDateNull() {
                return this.IsNull(this.tableOO_HT.UpdatingDateColumn);
            }
            
            public void SetUpdatingDateNull() {
                this[this.tableOO_HT.UpdatingDateColumn] = System.Convert.DBNull;
            }
            
            public bool IsOutSideOrderRequestHistoryIndexNull() {
                return this.IsNull(this.tableOO_HT.OutSideOrderRequestHistoryIndexColumn);
            }
            
            public void SetOutSideOrderRequestHistoryIndexNull() {
                this[this.tableOO_HT.OutSideOrderRequestHistoryIndexColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class OO_HTRowChangeEvent : EventArgs {
            
            private OO_HTRow eventRow;
            
            private DataRowAction eventAction;
            
            public OO_HTRowChangeEvent(OO_HTRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public OO_HTRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
