spring:
  application:
    name: smartmanager-api
  profiles:
    default: local
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1050MB

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
