//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace KIT_ERP.Community {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class DataSet1 : DataSet {
        
        private CWD_TDataTable tableCWD_T;
        
        public DataSet1() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected DataSet1(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["CWD_T"] != null)) {
                    this.Tables.Add(new CWD_TDataTable(ds.Tables["CWD_T"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public CWD_TDataTable CWD_T {
            get {
                return this.tableCWD_T;
            }
        }
        
        public override DataSet Clone() {
            DataSet1 cln = ((DataSet1)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["CWD_T"] != null)) {
                this.Tables.Add(new CWD_TDataTable(ds.Tables["CWD_T"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableCWD_T = ((CWD_TDataTable)(this.Tables["CWD_T"]));
            if ((this.tableCWD_T != null)) {
                this.tableCWD_T.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "DataSet1";
            this.Prefix = "";
            this.Namespace = "http://www.tempuri.org/DataSet1.xsd";
            this.Locale = new System.Globalization.CultureInfo("ko-KR");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableCWD_T = new CWD_TDataTable();
            this.Tables.Add(this.tableCWD_T);
        }
        
        private bool ShouldSerializeCWD_T() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void CWD_TRowChangeEventHandler(object sender, CWD_TRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class CWD_TDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnCWorkDiaryIndex;
            
            private DataColumn columnWorkDateTitle;
            
            private DataColumn columnId;
            
            private DataColumn columnName;
            
            private DataColumn columnMorningWork;
            
            private DataColumn columnAfternoonWork;
            
            private DataColumn columnNightWork;
            
            private DataColumn columnTomorrowWork;
            
            private DataColumn columnListing;
            
            private DataColumn columnClosing;
            
            private DataColumn columnNoWriter;
            
            private DataColumn columnRegistrationDate;
            
            internal CWD_TDataTable() : 
                    base("CWD_T") {
                this.InitClass();
            }
            
            internal CWD_TDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn CWorkDiaryIndexColumn {
                get {
                    return this.columnCWorkDiaryIndex;
                }
            }
            
            internal DataColumn WorkDateTitleColumn {
                get {
                    return this.columnWorkDateTitle;
                }
            }
            
            internal DataColumn IdColumn {
                get {
                    return this.columnId;
                }
            }
            
            internal DataColumn NameColumn {
                get {
                    return this.columnName;
                }
            }
            
            internal DataColumn MorningWorkColumn {
                get {
                    return this.columnMorningWork;
                }
            }
            
            internal DataColumn AfternoonWorkColumn {
                get {
                    return this.columnAfternoonWork;
                }
            }
            
            internal DataColumn NightWorkColumn {
                get {
                    return this.columnNightWork;
                }
            }
            
            internal DataColumn TomorrowWorkColumn {
                get {
                    return this.columnTomorrowWork;
                }
            }
            
            internal DataColumn ListingColumn {
                get {
                    return this.columnListing;
                }
            }
            
            internal DataColumn ClosingColumn {
                get {
                    return this.columnClosing;
                }
            }
            
            internal DataColumn NoWriterColumn {
                get {
                    return this.columnNoWriter;
                }
            }
            
            internal DataColumn RegistrationDateColumn {
                get {
                    return this.columnRegistrationDate;
                }
            }
            
            public CWD_TRow this[int index] {
                get {
                    return ((CWD_TRow)(this.Rows[index]));
                }
            }
            
            public event CWD_TRowChangeEventHandler CWD_TRowChanged;
            
            public event CWD_TRowChangeEventHandler CWD_TRowChanging;
            
            public event CWD_TRowChangeEventHandler CWD_TRowDeleted;
            
            public event CWD_TRowChangeEventHandler CWD_TRowDeleting;
            
            public void AddCWD_TRow(CWD_TRow row) {
                this.Rows.Add(row);
            }
            
            public CWD_TRow AddCWD_TRow(string WorkDateTitle, string Id, string Name, string MorningWork, string AfternoonWork, string NightWork, string TomorrowWork, bool Listing, string Closing, int NoWriter, System.DateTime RegistrationDate) {
                CWD_TRow rowCWD_TRow = ((CWD_TRow)(this.NewRow()));
                rowCWD_TRow.ItemArray = new object[] {
                        null,
                        WorkDateTitle,
                        Id,
                        Name,
                        MorningWork,
                        AfternoonWork,
                        NightWork,
                        TomorrowWork,
                        Listing,
                        Closing,
                        NoWriter,
                        RegistrationDate};
                this.Rows.Add(rowCWD_TRow);
                return rowCWD_TRow;
            }
            
            public CWD_TRow FindByCWorkDiaryIndex(int CWorkDiaryIndex) {
                return ((CWD_TRow)(this.Rows.Find(new object[] {
                            CWorkDiaryIndex})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                CWD_TDataTable cln = ((CWD_TDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new CWD_TDataTable();
            }
            
            internal void InitVars() {
                this.columnCWorkDiaryIndex = this.Columns["CWorkDiaryIndex"];
                this.columnWorkDateTitle = this.Columns["WorkDateTitle"];
                this.columnId = this.Columns["Id"];
                this.columnName = this.Columns["Name"];
                this.columnMorningWork = this.Columns["MorningWork"];
                this.columnAfternoonWork = this.Columns["AfternoonWork"];
                this.columnNightWork = this.Columns["NightWork"];
                this.columnTomorrowWork = this.Columns["TomorrowWork"];
                this.columnListing = this.Columns["Listing"];
                this.columnClosing = this.Columns["Closing"];
                this.columnNoWriter = this.Columns["NoWriter"];
                this.columnRegistrationDate = this.Columns["RegistrationDate"];
            }
            
            private void InitClass() {
                this.columnCWorkDiaryIndex = new DataColumn("CWorkDiaryIndex", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnCWorkDiaryIndex);
                this.columnWorkDateTitle = new DataColumn("WorkDateTitle", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnWorkDateTitle);
                this.columnId = new DataColumn("Id", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnId);
                this.columnName = new DataColumn("Name", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnName);
                this.columnMorningWork = new DataColumn("MorningWork", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnMorningWork);
                this.columnAfternoonWork = new DataColumn("AfternoonWork", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnAfternoonWork);
                this.columnNightWork = new DataColumn("NightWork", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnNightWork);
                this.columnTomorrowWork = new DataColumn("TomorrowWork", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnTomorrowWork);
                this.columnListing = new DataColumn("Listing", typeof(bool), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnListing);
                this.columnClosing = new DataColumn("Closing", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnClosing);
                this.columnNoWriter = new DataColumn("NoWriter", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnNoWriter);
                this.columnRegistrationDate = new DataColumn("RegistrationDate", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnRegistrationDate);
                this.Constraints.Add(new UniqueConstraint("Constraint1", new DataColumn[] {
                                this.columnCWorkDiaryIndex}, true));
                this.columnCWorkDiaryIndex.AutoIncrement = true;
                this.columnCWorkDiaryIndex.AllowDBNull = false;
                this.columnCWorkDiaryIndex.ReadOnly = true;
                this.columnCWorkDiaryIndex.Unique = true;
            }
            
            public CWD_TRow NewCWD_TRow() {
                return ((CWD_TRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new CWD_TRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(CWD_TRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.CWD_TRowChanged != null)) {
                    this.CWD_TRowChanged(this, new CWD_TRowChangeEvent(((CWD_TRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.CWD_TRowChanging != null)) {
                    this.CWD_TRowChanging(this, new CWD_TRowChangeEvent(((CWD_TRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.CWD_TRowDeleted != null)) {
                    this.CWD_TRowDeleted(this, new CWD_TRowChangeEvent(((CWD_TRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.CWD_TRowDeleting != null)) {
                    this.CWD_TRowDeleting(this, new CWD_TRowChangeEvent(((CWD_TRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveCWD_TRow(CWD_TRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class CWD_TRow : DataRow {
            
            private CWD_TDataTable tableCWD_T;
            
            internal CWD_TRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableCWD_T = ((CWD_TDataTable)(this.Table));
            }
            
            public int CWorkDiaryIndex {
                get {
                    return ((int)(this[this.tableCWD_T.CWorkDiaryIndexColumn]));
                }
                set {
                    this[this.tableCWD_T.CWorkDiaryIndexColumn] = value;
                }
            }
            
            public string WorkDateTitle {
                get {
                    try {
                        return ((string)(this[this.tableCWD_T.WorkDateTitleColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableCWD_T.WorkDateTitleColumn] = value;
                }
            }
            
            public string Id {
                get {
                    try {
                        return ((string)(this[this.tableCWD_T.IdColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableCWD_T.IdColumn] = value;
                }
            }
            
            public string Name {
                get {
                    try {
                        return ((string)(this[this.tableCWD_T.NameColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableCWD_T.NameColumn] = value;
                }
            }
            
            public string MorningWork {
                get {
                    try {
                        return ((string)(this[this.tableCWD_T.MorningWorkColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableCWD_T.MorningWorkColumn] = value;
                }
            }
            
            public string AfternoonWork {
                get {
                    try {
                        return ((string)(this[this.tableCWD_T.AfternoonWorkColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableCWD_T.AfternoonWorkColumn] = value;
                }
            }
            
            public string NightWork {
                get {
                    try {
                        return ((string)(this[this.tableCWD_T.NightWorkColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableCWD_T.NightWorkColumn] = value;
                }
            }
            
            public string TomorrowWork {
                get {
                    try {
                        return ((string)(this[this.tableCWD_T.TomorrowWorkColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableCWD_T.TomorrowWorkColumn] = value;
                }
            }
            
            public bool Listing {
                get {
                    try {
                        return ((bool)(this[this.tableCWD_T.ListingColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableCWD_T.ListingColumn] = value;
                }
            }
            
            public string Closing {
                get {
                    try {
                        return ((string)(this[this.tableCWD_T.ClosingColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableCWD_T.ClosingColumn] = value;
                }
            }
            
            public int NoWriter {
                get {
                    try {
                        return ((int)(this[this.tableCWD_T.NoWriterColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableCWD_T.NoWriterColumn] = value;
                }
            }
            
            public System.DateTime RegistrationDate {
                get {
                    try {
                        return ((System.DateTime)(this[this.tableCWD_T.RegistrationDateColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableCWD_T.RegistrationDateColumn] = value;
                }
            }
            
            public bool IsWorkDateTitleNull() {
                return this.IsNull(this.tableCWD_T.WorkDateTitleColumn);
            }
            
            public void SetWorkDateTitleNull() {
                this[this.tableCWD_T.WorkDateTitleColumn] = System.Convert.DBNull;
            }
            
            public bool IsIdNull() {
                return this.IsNull(this.tableCWD_T.IdColumn);
            }
            
            public void SetIdNull() {
                this[this.tableCWD_T.IdColumn] = System.Convert.DBNull;
            }
            
            public bool IsNameNull() {
                return this.IsNull(this.tableCWD_T.NameColumn);
            }
            
            public void SetNameNull() {
                this[this.tableCWD_T.NameColumn] = System.Convert.DBNull;
            }
            
            public bool IsMorningWorkNull() {
                return this.IsNull(this.tableCWD_T.MorningWorkColumn);
            }
            
            public void SetMorningWorkNull() {
                this[this.tableCWD_T.MorningWorkColumn] = System.Convert.DBNull;
            }
            
            public bool IsAfternoonWorkNull() {
                return this.IsNull(this.tableCWD_T.AfternoonWorkColumn);
            }
            
            public void SetAfternoonWorkNull() {
                this[this.tableCWD_T.AfternoonWorkColumn] = System.Convert.DBNull;
            }
            
            public bool IsNightWorkNull() {
                return this.IsNull(this.tableCWD_T.NightWorkColumn);
            }
            
            public void SetNightWorkNull() {
                this[this.tableCWD_T.NightWorkColumn] = System.Convert.DBNull;
            }
            
            public bool IsTomorrowWorkNull() {
                return this.IsNull(this.tableCWD_T.TomorrowWorkColumn);
            }
            
            public void SetTomorrowWorkNull() {
                this[this.tableCWD_T.TomorrowWorkColumn] = System.Convert.DBNull;
            }
            
            public bool IsListingNull() {
                return this.IsNull(this.tableCWD_T.ListingColumn);
            }
            
            public void SetListingNull() {
                this[this.tableCWD_T.ListingColumn] = System.Convert.DBNull;
            }
            
            public bool IsClosingNull() {
                return this.IsNull(this.tableCWD_T.ClosingColumn);
            }
            
            public void SetClosingNull() {
                this[this.tableCWD_T.ClosingColumn] = System.Convert.DBNull;
            }
            
            public bool IsNoWriterNull() {
                return this.IsNull(this.tableCWD_T.NoWriterColumn);
            }
            
            public void SetNoWriterNull() {
                this[this.tableCWD_T.NoWriterColumn] = System.Convert.DBNull;
            }
            
            public bool IsRegistrationDateNull() {
                return this.IsNull(this.tableCWD_T.RegistrationDateColumn);
            }
            
            public void SetRegistrationDateNull() {
                this[this.tableCWD_T.RegistrationDateColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class CWD_TRowChangeEvent : EventArgs {
            
            private CWD_TRow eventRow;
            
            private DataRowAction eventAction;
            
            public CWD_TRowChangeEvent(CWD_TRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public CWD_TRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
