//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2300
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace KIT_ERP.Community {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class dsUser : DataSet {
        
        private UI_MTDataTable tableUI_MT;
        
        public dsUser() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected dsUser(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["UI_MT"] != null)) {
                    this.Tables.Add(new UI_MTDataTable(ds.Tables["UI_MT"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public UI_MTDataTable UI_MT {
            get {
                return this.tableUI_MT;
            }
        }
        
        public override DataSet Clone() {
            dsUser cln = ((dsUser)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["UI_MT"] != null)) {
                this.Tables.Add(new UI_MTDataTable(ds.Tables["UI_MT"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableUI_MT = ((UI_MTDataTable)(this.Tables["UI_MT"]));
            if ((this.tableUI_MT != null)) {
                this.tableUI_MT.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "dsUser";
            this.Prefix = "";
            this.Namespace = "http://www.tempuri.org/dsUser.xsd";
            this.Locale = new System.Globalization.CultureInfo("ko-KR");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableUI_MT = new UI_MTDataTable();
            this.Tables.Add(this.tableUI_MT);
        }
        
        private bool ShouldSerializeUI_MT() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void UI_MTRowChangeEventHandler(object sender, UI_MTRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class UI_MTDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnName;
            
            private DataColumn columnID;
            
            internal UI_MTDataTable() : 
                    base("UI_MT") {
                this.InitClass();
            }
            
            internal UI_MTDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn NameColumn {
                get {
                    return this.columnName;
                }
            }
            
            internal DataColumn IDColumn {
                get {
                    return this.columnID;
                }
            }
            
            public UI_MTRow this[int index] {
                get {
                    return ((UI_MTRow)(this.Rows[index]));
                }
            }
            
            public event UI_MTRowChangeEventHandler UI_MTRowChanged;
            
            public event UI_MTRowChangeEventHandler UI_MTRowChanging;
            
            public event UI_MTRowChangeEventHandler UI_MTRowDeleted;
            
            public event UI_MTRowChangeEventHandler UI_MTRowDeleting;
            
            public void AddUI_MTRow(UI_MTRow row) {
                this.Rows.Add(row);
            }
            
            public UI_MTRow AddUI_MTRow(string Name, string ID) {
                UI_MTRow rowUI_MTRow = ((UI_MTRow)(this.NewRow()));
                rowUI_MTRow.ItemArray = new object[] {
                        Name,
                        ID};
                this.Rows.Add(rowUI_MTRow);
                return rowUI_MTRow;
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                UI_MTDataTable cln = ((UI_MTDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new UI_MTDataTable();
            }
            
            internal void InitVars() {
                this.columnName = this.Columns["Name"];
                this.columnID = this.Columns["ID"];
            }
            
            private void InitClass() {
                this.columnName = new DataColumn("Name", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnName);
                this.columnID = new DataColumn("ID", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnID);
                this.columnName.ReadOnly = true;
            }
            
            public UI_MTRow NewUI_MTRow() {
                return ((UI_MTRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new UI_MTRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(UI_MTRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.UI_MTRowChanged != null)) {
                    this.UI_MTRowChanged(this, new UI_MTRowChangeEvent(((UI_MTRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.UI_MTRowChanging != null)) {
                    this.UI_MTRowChanging(this, new UI_MTRowChangeEvent(((UI_MTRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.UI_MTRowDeleted != null)) {
                    this.UI_MTRowDeleted(this, new UI_MTRowChangeEvent(((UI_MTRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.UI_MTRowDeleting != null)) {
                    this.UI_MTRowDeleting(this, new UI_MTRowChangeEvent(((UI_MTRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveUI_MTRow(UI_MTRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class UI_MTRow : DataRow {
            
            private UI_MTDataTable tableUI_MT;
            
            internal UI_MTRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableUI_MT = ((UI_MTDataTable)(this.Table));
            }
            
            public string Name {
                get {
                    try {
                        return ((string)(this[this.tableUI_MT.NameColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableUI_MT.NameColumn] = value;
                }
            }
            
            public string ID {
                get {
                    try {
                        return ((string)(this[this.tableUI_MT.IDColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableUI_MT.IDColumn] = value;
                }
            }
            
            public bool IsNameNull() {
                return this.IsNull(this.tableUI_MT.NameColumn);
            }
            
            public void SetNameNull() {
                this[this.tableUI_MT.NameColumn] = System.Convert.DBNull;
            }
            
            public bool IsIDNull() {
                return this.IsNull(this.tableUI_MT.IDColumn);
            }
            
            public void SetIDNull() {
                this[this.tableUI_MT.IDColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class UI_MTRowChangeEvent : EventArgs {
            
            private UI_MTRow eventRow;
            
            private DataRowAction eventAction;
            
            public UI_MTRowChangeEvent(UI_MTRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public UI_MTRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
