//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// 이 소스 코드가 Microsoft.VSDesigner, 버전 1.1.4322.573에서 자동으로 생성되었습니다.
// 
namespace KIT_ERP.com.devpia.service {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="sPostalCodeSoap", Namespace="http://service.devpia.com/wsPostalCode/")]
    public class sPostalCode : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public sPostalCode() {
            this.Url = "http://service.devpia.com/wspostalcode/spostalcode.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.devpia.com/wsPostalCode/GetPostalCodeByCode", RequestNamespace="http://service.devpia.com/wsPostalCode/", ResponseNamespace="http://service.devpia.com/wsPostalCode/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public dsPostalCodeByCode GetPostalCodeByCode(string sCode) {
            object[] results = this.Invoke("GetPostalCodeByCode", new object[] {
                        sCode});
            return ((dsPostalCodeByCode)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetPostalCodeByCode(string sCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetPostalCodeByCode", new object[] {
                        sCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public dsPostalCodeByCode EndGetPostalCodeByCode(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((dsPostalCodeByCode)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.devpia.com/wsPostalCode/GetPostalCodeByDong", RequestNamespace="http://service.devpia.com/wsPostalCode/", ResponseNamespace="http://service.devpia.com/wsPostalCode/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public dsPostalCodeByDong GetPostalCodeByDong(string sDong) {
            object[] results = this.Invoke("GetPostalCodeByDong", new object[] {
                        sDong});
            return ((dsPostalCodeByDong)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetPostalCodeByDong(string sDong, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetPostalCodeByDong", new object[] {
                        sDong}, callback, asyncState);
        }
        
        /// <remarks/>
        public dsPostalCodeByDong EndGetPostalCodeByDong(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((dsPostalCodeByDong)(results[0]));
        }
    }
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class dsPostalCodeByDong : DataSet {
        
        private ZIPCODEDataTable tableZIPCODE;
        
        public dsPostalCodeByDong() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected dsPostalCodeByDong(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["ZIPCODE"] != null)) {
                    this.Tables.Add(new ZIPCODEDataTable(ds.Tables["ZIPCODE"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public ZIPCODEDataTable ZIPCODE {
            get {
                return this.tableZIPCODE;
            }
        }
        
        public override DataSet Clone() {
            dsPostalCodeByDong cln = ((dsPostalCodeByDong)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["ZIPCODE"] != null)) {
                this.Tables.Add(new ZIPCODEDataTable(ds.Tables["ZIPCODE"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableZIPCODE = ((ZIPCODEDataTable)(this.Tables["ZIPCODE"]));
            if ((this.tableZIPCODE != null)) {
                this.tableZIPCODE.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "dsPostalCodeByDong";
            this.Prefix = "";
            this.Namespace = "http://service.devpia.com/wsPostalCode/dsPostalCodeByDong.xsd";
            this.Locale = new System.Globalization.CultureInfo("ko-KR");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableZIPCODE = new ZIPCODEDataTable();
            this.Tables.Add(this.tableZIPCODE);
        }
        
        private bool ShouldSerializeZIPCODE() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void ZIPCODERowChangeEventHandler(object sender, ZIPCODERowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class ZIPCODEDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columninKey;
            
            private DataColumn columnZIPCODE;
            
            private DataColumn columnSIDO;
            
            private DataColumn columnGUGUN;
            
            private DataColumn columnDONG;
            
            private DataColumn columnBUNJI;
            
            internal ZIPCODEDataTable() : 
                    base("ZIPCODE") {
                this.InitClass();
            }
            
            internal ZIPCODEDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn inKeyColumn {
                get {
                    return this.columninKey;
                }
            }
            
            internal DataColumn ZIPCODEColumn {
                get {
                    return this.columnZIPCODE;
                }
            }
            
            internal DataColumn SIDOColumn {
                get {
                    return this.columnSIDO;
                }
            }
            
            internal DataColumn GUGUNColumn {
                get {
                    return this.columnGUGUN;
                }
            }
            
            internal DataColumn DONGColumn {
                get {
                    return this.columnDONG;
                }
            }
            
            internal DataColumn BUNJIColumn {
                get {
                    return this.columnBUNJI;
                }
            }
            
            public ZIPCODERow this[int index] {
                get {
                    return ((ZIPCODERow)(this.Rows[index]));
                }
            }
            
            public event ZIPCODERowChangeEventHandler ZIPCODERowChanged;
            
            public event ZIPCODERowChangeEventHandler ZIPCODERowChanging;
            
            public event ZIPCODERowChangeEventHandler ZIPCODERowDeleted;
            
            public event ZIPCODERowChangeEventHandler ZIPCODERowDeleting;
            
            public void AddZIPCODERow(ZIPCODERow row) {
                this.Rows.Add(row);
            }
            
            public ZIPCODERow AddZIPCODERow(string ZIPCODE, string SIDO, string GUGUN, string DONG, string BUNJI) {
                ZIPCODERow rowZIPCODERow = ((ZIPCODERow)(this.NewRow()));
                rowZIPCODERow.ItemArray = new object[] {
                        null,
                        ZIPCODE,
                        SIDO,
                        GUGUN,
                        DONG,
                        BUNJI};
                this.Rows.Add(rowZIPCODERow);
                return rowZIPCODERow;
            }
            
            public ZIPCODERow FindByinKey(int inKey) {
                return ((ZIPCODERow)(this.Rows.Find(new object[] {
                            inKey})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                ZIPCODEDataTable cln = ((ZIPCODEDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new ZIPCODEDataTable();
            }
            
            internal void InitVars() {
                this.columninKey = this.Columns["inKey"];
                this.columnZIPCODE = this.Columns["ZIPCODE"];
                this.columnSIDO = this.Columns["SIDO"];
                this.columnGUGUN = this.Columns["GUGUN"];
                this.columnDONG = this.Columns["DONG"];
                this.columnBUNJI = this.Columns["BUNJI"];
            }
            
            private void InitClass() {
                this.columninKey = new DataColumn("inKey", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columninKey);
                this.columnZIPCODE = new DataColumn("ZIPCODE", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnZIPCODE);
                this.columnSIDO = new DataColumn("SIDO", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnSIDO);
                this.columnGUGUN = new DataColumn("GUGUN", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnGUGUN);
                this.columnDONG = new DataColumn("DONG", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnDONG);
                this.columnBUNJI = new DataColumn("BUNJI", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnBUNJI);
                this.Constraints.Add(new UniqueConstraint("Constraint1", new DataColumn[] {
                                this.columninKey}, true));
                this.columninKey.AutoIncrement = true;
                this.columninKey.AllowDBNull = false;
                this.columninKey.ReadOnly = true;
                this.columninKey.Unique = true;
            }
            
            public ZIPCODERow NewZIPCODERow() {
                return ((ZIPCODERow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new ZIPCODERow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(ZIPCODERow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.ZIPCODERowChanged != null)) {
                    this.ZIPCODERowChanged(this, new ZIPCODERowChangeEvent(((ZIPCODERow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.ZIPCODERowChanging != null)) {
                    this.ZIPCODERowChanging(this, new ZIPCODERowChangeEvent(((ZIPCODERow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.ZIPCODERowDeleted != null)) {
                    this.ZIPCODERowDeleted(this, new ZIPCODERowChangeEvent(((ZIPCODERow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.ZIPCODERowDeleting != null)) {
                    this.ZIPCODERowDeleting(this, new ZIPCODERowChangeEvent(((ZIPCODERow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveZIPCODERow(ZIPCODERow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class ZIPCODERow : DataRow {
            
            private ZIPCODEDataTable tableZIPCODE;
            
            internal ZIPCODERow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableZIPCODE = ((ZIPCODEDataTable)(this.Table));
            }
            
            public int inKey {
                get {
                    return ((int)(this[this.tableZIPCODE.inKeyColumn]));
                }
                set {
                    this[this.tableZIPCODE.inKeyColumn] = value;
                }
            }
            
            public string ZIPCODE {
                get {
                    try {
                        return ((string)(this[this.tableZIPCODE.ZIPCODEColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableZIPCODE.ZIPCODEColumn] = value;
                }
            }
            
            public string SIDO {
                get {
                    try {
                        return ((string)(this[this.tableZIPCODE.SIDOColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableZIPCODE.SIDOColumn] = value;
                }
            }
            
            public string GUGUN {
                get {
                    try {
                        return ((string)(this[this.tableZIPCODE.GUGUNColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableZIPCODE.GUGUNColumn] = value;
                }
            }
            
            public string DONG {
                get {
                    try {
                        return ((string)(this[this.tableZIPCODE.DONGColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableZIPCODE.DONGColumn] = value;
                }
            }
            
            public string BUNJI {
                get {
                    try {
                        return ((string)(this[this.tableZIPCODE.BUNJIColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableZIPCODE.BUNJIColumn] = value;
                }
            }
            
            public bool IsZIPCODENull() {
                return this.IsNull(this.tableZIPCODE.ZIPCODEColumn);
            }
            
            public void SetZIPCODENull() {
                this[this.tableZIPCODE.ZIPCODEColumn] = System.Convert.DBNull;
            }
            
            public bool IsSIDONull() {
                return this.IsNull(this.tableZIPCODE.SIDOColumn);
            }
            
            public void SetSIDONull() {
                this[this.tableZIPCODE.SIDOColumn] = System.Convert.DBNull;
            }
            
            public bool IsGUGUNNull() {
                return this.IsNull(this.tableZIPCODE.GUGUNColumn);
            }
            
            public void SetGUGUNNull() {
                this[this.tableZIPCODE.GUGUNColumn] = System.Convert.DBNull;
            }
            
            public bool IsDONGNull() {
                return this.IsNull(this.tableZIPCODE.DONGColumn);
            }
            
            public void SetDONGNull() {
                this[this.tableZIPCODE.DONGColumn] = System.Convert.DBNull;
            }
            
            public bool IsBUNJINull() {
                return this.IsNull(this.tableZIPCODE.BUNJIColumn);
            }
            
            public void SetBUNJINull() {
                this[this.tableZIPCODE.BUNJIColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class ZIPCODERowChangeEvent : EventArgs {
            
            private ZIPCODERow eventRow;
            
            private DataRowAction eventAction;
            
            public ZIPCODERowChangeEvent(ZIPCODERow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public ZIPCODERow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class dsPostalCodeByCode : DataSet {
        
        private ZIPCODEDataTable tableZIPCODE;
        
        public dsPostalCodeByCode() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected dsPostalCodeByCode(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["ZIPCODE"] != null)) {
                    this.Tables.Add(new ZIPCODEDataTable(ds.Tables["ZIPCODE"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public ZIPCODEDataTable ZIPCODE {
            get {
                return this.tableZIPCODE;
            }
        }
        
        public override DataSet Clone() {
            dsPostalCodeByCode cln = ((dsPostalCodeByCode)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["ZIPCODE"] != null)) {
                this.Tables.Add(new ZIPCODEDataTable(ds.Tables["ZIPCODE"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableZIPCODE = ((ZIPCODEDataTable)(this.Tables["ZIPCODE"]));
            if ((this.tableZIPCODE != null)) {
                this.tableZIPCODE.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "dsPostalCodeByCode";
            this.Prefix = "";
            this.Namespace = "http://service.devpia.com/wsPostalCode/dsPostalCodeByCode.xsd";
            this.Locale = new System.Globalization.CultureInfo("ko-KR");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableZIPCODE = new ZIPCODEDataTable();
            this.Tables.Add(this.tableZIPCODE);
        }
        
        private bool ShouldSerializeZIPCODE() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void ZIPCODERowChangeEventHandler(object sender, ZIPCODERowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class ZIPCODEDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columninKey;
            
            private DataColumn columnZIPCODE;
            
            private DataColumn columnSIDO;
            
            private DataColumn columnGUGUN;
            
            private DataColumn columnDONG;
            
            private DataColumn columnBUNJI;
            
            internal ZIPCODEDataTable() : 
                    base("ZIPCODE") {
                this.InitClass();
            }
            
            internal ZIPCODEDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn inKeyColumn {
                get {
                    return this.columninKey;
                }
            }
            
            internal DataColumn ZIPCODEColumn {
                get {
                    return this.columnZIPCODE;
                }
            }
            
            internal DataColumn SIDOColumn {
                get {
                    return this.columnSIDO;
                }
            }
            
            internal DataColumn GUGUNColumn {
                get {
                    return this.columnGUGUN;
                }
            }
            
            internal DataColumn DONGColumn {
                get {
                    return this.columnDONG;
                }
            }
            
            internal DataColumn BUNJIColumn {
                get {
                    return this.columnBUNJI;
                }
            }
            
            public ZIPCODERow this[int index] {
                get {
                    return ((ZIPCODERow)(this.Rows[index]));
                }
            }
            
            public event ZIPCODERowChangeEventHandler ZIPCODERowChanged;
            
            public event ZIPCODERowChangeEventHandler ZIPCODERowChanging;
            
            public event ZIPCODERowChangeEventHandler ZIPCODERowDeleted;
            
            public event ZIPCODERowChangeEventHandler ZIPCODERowDeleting;
            
            public void AddZIPCODERow(ZIPCODERow row) {
                this.Rows.Add(row);
            }
            
            public ZIPCODERow AddZIPCODERow(string ZIPCODE, string SIDO, string GUGUN, string DONG, string BUNJI) {
                ZIPCODERow rowZIPCODERow = ((ZIPCODERow)(this.NewRow()));
                rowZIPCODERow.ItemArray = new object[] {
                        null,
                        ZIPCODE,
                        SIDO,
                        GUGUN,
                        DONG,
                        BUNJI};
                this.Rows.Add(rowZIPCODERow);
                return rowZIPCODERow;
            }
            
            public ZIPCODERow FindByinKey(int inKey) {
                return ((ZIPCODERow)(this.Rows.Find(new object[] {
                            inKey})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                ZIPCODEDataTable cln = ((ZIPCODEDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new ZIPCODEDataTable();
            }
            
            internal void InitVars() {
                this.columninKey = this.Columns["inKey"];
                this.columnZIPCODE = this.Columns["ZIPCODE"];
                this.columnSIDO = this.Columns["SIDO"];
                this.columnGUGUN = this.Columns["GUGUN"];
                this.columnDONG = this.Columns["DONG"];
                this.columnBUNJI = this.Columns["BUNJI"];
            }
            
            private void InitClass() {
                this.columninKey = new DataColumn("inKey", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columninKey);
                this.columnZIPCODE = new DataColumn("ZIPCODE", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnZIPCODE);
                this.columnSIDO = new DataColumn("SIDO", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnSIDO);
                this.columnGUGUN = new DataColumn("GUGUN", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnGUGUN);
                this.columnDONG = new DataColumn("DONG", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnDONG);
                this.columnBUNJI = new DataColumn("BUNJI", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnBUNJI);
                this.Constraints.Add(new UniqueConstraint("Constraint1", new DataColumn[] {
                                this.columninKey}, true));
                this.columninKey.AutoIncrement = true;
                this.columninKey.AllowDBNull = false;
                this.columninKey.ReadOnly = true;
                this.columninKey.Unique = true;
            }
            
            public ZIPCODERow NewZIPCODERow() {
                return ((ZIPCODERow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new ZIPCODERow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(ZIPCODERow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.ZIPCODERowChanged != null)) {
                    this.ZIPCODERowChanged(this, new ZIPCODERowChangeEvent(((ZIPCODERow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.ZIPCODERowChanging != null)) {
                    this.ZIPCODERowChanging(this, new ZIPCODERowChangeEvent(((ZIPCODERow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.ZIPCODERowDeleted != null)) {
                    this.ZIPCODERowDeleted(this, new ZIPCODERowChangeEvent(((ZIPCODERow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.ZIPCODERowDeleting != null)) {
                    this.ZIPCODERowDeleting(this, new ZIPCODERowChangeEvent(((ZIPCODERow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveZIPCODERow(ZIPCODERow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class ZIPCODERow : DataRow {
            
            private ZIPCODEDataTable tableZIPCODE;
            
            internal ZIPCODERow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableZIPCODE = ((ZIPCODEDataTable)(this.Table));
            }
            
            public int inKey {
                get {
                    return ((int)(this[this.tableZIPCODE.inKeyColumn]));
                }
                set {
                    this[this.tableZIPCODE.inKeyColumn] = value;
                }
            }
            
            public string ZIPCODE {
                get {
                    try {
                        return ((string)(this[this.tableZIPCODE.ZIPCODEColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableZIPCODE.ZIPCODEColumn] = value;
                }
            }
            
            public string SIDO {
                get {
                    try {
                        return ((string)(this[this.tableZIPCODE.SIDOColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableZIPCODE.SIDOColumn] = value;
                }
            }
            
            public string GUGUN {
                get {
                    try {
                        return ((string)(this[this.tableZIPCODE.GUGUNColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableZIPCODE.GUGUNColumn] = value;
                }
            }
            
            public string DONG {
                get {
                    try {
                        return ((string)(this[this.tableZIPCODE.DONGColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableZIPCODE.DONGColumn] = value;
                }
            }
            
            public string BUNJI {
                get {
                    try {
                        return ((string)(this[this.tableZIPCODE.BUNJIColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableZIPCODE.BUNJIColumn] = value;
                }
            }
            
            public bool IsZIPCODENull() {
                return this.IsNull(this.tableZIPCODE.ZIPCODEColumn);
            }
            
            public void SetZIPCODENull() {
                this[this.tableZIPCODE.ZIPCODEColumn] = System.Convert.DBNull;
            }
            
            public bool IsSIDONull() {
                return this.IsNull(this.tableZIPCODE.SIDOColumn);
            }
            
            public void SetSIDONull() {
                this[this.tableZIPCODE.SIDOColumn] = System.Convert.DBNull;
            }
            
            public bool IsGUGUNNull() {
                return this.IsNull(this.tableZIPCODE.GUGUNColumn);
            }
            
            public void SetGUGUNNull() {
                this[this.tableZIPCODE.GUGUNColumn] = System.Convert.DBNull;
            }
            
            public bool IsDONGNull() {
                return this.IsNull(this.tableZIPCODE.DONGColumn);
            }
            
            public void SetDONGNull() {
                this[this.tableZIPCODE.DONGColumn] = System.Convert.DBNull;
            }
            
            public bool IsBUNJINull() {
                return this.IsNull(this.tableZIPCODE.BUNJIColumn);
            }
            
            public void SetBUNJINull() {
                this[this.tableZIPCODE.BUNJIColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class ZIPCODERowChangeEvent : EventArgs {
            
            private ZIPCODERow eventRow;
            
            private DataRowAction eventAction;
            
            public ZIPCODERowChangeEvent(ZIPCODERow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public ZIPCODERow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
