-- TX1-R2: 품질검사원장

CREATE TABLE IF NOT EXISTS quality_inspection (
  id                            BIGINT         NOT NULL AUTO_INCREMENT PRIMARY KEY,
  inspection_no                 VARCHAR(30)    NULL,
  source_type                   ENUM('PURCHASE','OUTSOURCE') NOT NULL,
  source_receipt_line_id        BIGINT         NOT NULL,
  item_id                       BIGINT         NOT NULL,
  company_id                    BIGINT         NOT NULL,
  request_qty                   DECIMAL(18, 4) NOT NULL,
  passed_qty                    DECIMAL(18, 4) NOT NULL DEFAULT 0,
  failed_qty                    DECIMAL(18, 4) NOT NULL DEFAULT 0,
  status                        ENUM('PENDING','COMPLETED','CANCELLED') NOT NULL,
  inspection_decision_code_id   BIGINT         NULL,
  unsuitability_cause_code_id   BIGINT         NULL,
  unsuitability_status_code_id  BIGINT         NULL,
  completed_at                  DATETIME(3)    NULL,
  recording_state               TINYINT        NOT NULL DEFAULT 1,
  created_by                    VARCHAR(100)   NULL,
  created_by_id                 VARCHAR(100)   NULL,
  created_at                    DATETIME(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by                    VARCHAR(100)   NULL,
  updated_by_id                 VARCHAR(100)   NULL,
  updated_at                    DATETIME(3)    NULL ON UPDATE CURRENT_TIMESTAMP(3),
  INDEX idx_qi_status (status, source_type, recording_state),
  INDEX idx_qi_receipt_line (source_receipt_line_id, recording_state),
  CONSTRAINT fk_qi_item FOREIGN KEY (item_id) REFERENCES item (id),
  CONSTRAINT fk_qi_company FOREIGN KEY (company_id) REFERENCES company (id),
  CONSTRAINT fk_qi_receipt_line FOREIGN KEY (source_receipt_line_id) REFERENCES purchase_receipt_line (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
