//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace KIT_ERP {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class DataSet1 : DataSet {
        
        private SM_TableDataTable tableSM_Table;
        
        public DataSet1() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected DataSet1(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["SM_Table"] != null)) {
                    this.Tables.Add(new SM_TableDataTable(ds.Tables["SM_Table"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public SM_TableDataTable SM_Table {
            get {
                return this.tableSM_Table;
            }
        }
        
        public override DataSet Clone() {
            DataSet1 cln = ((DataSet1)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["SM_Table"] != null)) {
                this.Tables.Add(new SM_TableDataTable(ds.Tables["SM_Table"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableSM_Table = ((SM_TableDataTable)(this.Tables["SM_Table"]));
            if ((this.tableSM_Table != null)) {
                this.tableSM_Table.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "DataSet1";
            this.Prefix = "";
            this.Namespace = "http://www.tempuri.org/DataSet1.xsd";
            this.Locale = new System.Globalization.CultureInfo("ko-KR");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableSM_Table = new SM_TableDataTable();
            this.Tables.Add(this.tableSM_Table);
        }
        
        private bool ShouldSerializeSM_Table() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void SM_TableRowChangeEventHandler(object sender, SM_TableRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class SM_TableDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnSM_idx;
            
            private DataColumn columnSM_StockClassify;
            
            private DataColumn columnSM_ItemNumber;
            
            private DataColumn columnSM_StockLocation;
            
            private DataColumn columnSM_ProcessName;
            
            private DataColumn columnSM_CarryOverQuantity1;
            
            private DataColumn columnSM_CarryOverCost1;
            
            private DataColumn columnSM_StorageQuantity1;
            
            private DataColumn columnSM_StorageCost1;
            
            private DataColumn columnSM_DeliveryQuantity1;
            
            private DataColumn columnSM_DeliveryCost1;
            
            internal SM_TableDataTable() : 
                    base("SM_Table") {
                this.InitClass();
            }
            
            internal SM_TableDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn SM_idxColumn {
                get {
                    return this.columnSM_idx;
                }
            }
            
            internal DataColumn SM_StockClassifyColumn {
                get {
                    return this.columnSM_StockClassify;
                }
            }
            
            internal DataColumn SM_ItemNumberColumn {
                get {
                    return this.columnSM_ItemNumber;
                }
            }
            
            internal DataColumn SM_StockLocationColumn {
                get {
                    return this.columnSM_StockLocation;
                }
            }
            
            internal DataColumn SM_ProcessNameColumn {
                get {
                    return this.columnSM_ProcessName;
                }
            }
            
            internal DataColumn SM_CarryOverQuantity1Column {
                get {
                    return this.columnSM_CarryOverQuantity1;
                }
            }
            
            internal DataColumn SM_CarryOverCost1Column {
                get {
                    return this.columnSM_CarryOverCost1;
                }
            }
            
            internal DataColumn SM_StorageQuantity1Column {
                get {
                    return this.columnSM_StorageQuantity1;
                }
            }
            
            internal DataColumn SM_StorageCost1Column {
                get {
                    return this.columnSM_StorageCost1;
                }
            }
            
            internal DataColumn SM_DeliveryQuantity1Column {
                get {
                    return this.columnSM_DeliveryQuantity1;
                }
            }
            
            internal DataColumn SM_DeliveryCost1Column {
                get {
                    return this.columnSM_DeliveryCost1;
                }
            }
            
            public SM_TableRow this[int index] {
                get {
                    return ((SM_TableRow)(this.Rows[index]));
                }
            }
            
            public event SM_TableRowChangeEventHandler SM_TableRowChanged;
            
            public event SM_TableRowChangeEventHandler SM_TableRowChanging;
            
            public event SM_TableRowChangeEventHandler SM_TableRowDeleted;
            
            public event SM_TableRowChangeEventHandler SM_TableRowDeleting;
            
            public void AddSM_TableRow(SM_TableRow row) {
                this.Rows.Add(row);
            }
            
            public SM_TableRow AddSM_TableRow(string SM_StockClassify, string SM_ItemNumber, string SM_StockLocation, string SM_ProcessName, System.Double SM_CarryOverQuantity1, System.Double SM_CarryOverCost1, System.Double SM_StorageQuantity1, System.Double SM_StorageCost1, System.Double SM_DeliveryQuantity1, System.Double SM_DeliveryCost1) {
                SM_TableRow rowSM_TableRow = ((SM_TableRow)(this.NewRow()));
                rowSM_TableRow.ItemArray = new object[] {
                        null,
                        SM_StockClassify,
                        SM_ItemNumber,
                        SM_StockLocation,
                        SM_ProcessName,
                        SM_CarryOverQuantity1,
                        SM_CarryOverCost1,
                        SM_StorageQuantity1,
                        SM_StorageCost1,
                        SM_DeliveryQuantity1,
                        SM_DeliveryCost1};
                this.Rows.Add(rowSM_TableRow);
                return rowSM_TableRow;
            }
            
            public SM_TableRow FindBySM_idx(int SM_idx) {
                return ((SM_TableRow)(this.Rows.Find(new object[] {
                            SM_idx})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                SM_TableDataTable cln = ((SM_TableDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new SM_TableDataTable();
            }
            
            internal void InitVars() {
                this.columnSM_idx = this.Columns["SM_idx"];
                this.columnSM_StockClassify = this.Columns["SM_StockClassify"];
                this.columnSM_ItemNumber = this.Columns["SM_ItemNumber"];
                this.columnSM_StockLocation = this.Columns["SM_StockLocation"];
                this.columnSM_ProcessName = this.Columns["SM_ProcessName"];
                this.columnSM_CarryOverQuantity1 = this.Columns["SM_CarryOverQuantity1"];
                this.columnSM_CarryOverCost1 = this.Columns["SM_CarryOverCost1"];
                this.columnSM_StorageQuantity1 = this.Columns["SM_StorageQuantity1"];
                this.columnSM_StorageCost1 = this.Columns["SM_StorageCost1"];
                this.columnSM_DeliveryQuantity1 = this.Columns["SM_DeliveryQuantity1"];
                this.columnSM_DeliveryCost1 = this.Columns["SM_DeliveryCost1"];
            }
            
            private void InitClass() {
                this.columnSM_idx = new DataColumn("SM_idx", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnSM_idx);
                this.columnSM_StockClassify = new DataColumn("SM_StockClassify", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnSM_StockClassify);
                this.columnSM_ItemNumber = new DataColumn("SM_ItemNumber", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnSM_ItemNumber);
                this.columnSM_StockLocation = new DataColumn("SM_StockLocation", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnSM_StockLocation);
                this.columnSM_ProcessName = new DataColumn("SM_ProcessName", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnSM_ProcessName);
                this.columnSM_CarryOverQuantity1 = new DataColumn("SM_CarryOverQuantity1", typeof(System.Double), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnSM_CarryOverQuantity1);
                this.columnSM_CarryOverCost1 = new DataColumn("SM_CarryOverCost1", typeof(System.Double), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnSM_CarryOverCost1);
                this.columnSM_StorageQuantity1 = new DataColumn("SM_StorageQuantity1", typeof(System.Double), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnSM_StorageQuantity1);
                this.columnSM_StorageCost1 = new DataColumn("SM_StorageCost1", typeof(System.Double), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnSM_StorageCost1);
                this.columnSM_DeliveryQuantity1 = new DataColumn("SM_DeliveryQuantity1", typeof(System.Double), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnSM_DeliveryQuantity1);
                this.columnSM_DeliveryCost1 = new DataColumn("SM_DeliveryCost1", typeof(System.Double), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnSM_DeliveryCost1);
                this.Constraints.Add(new UniqueConstraint("Constraint1", new DataColumn[] {
                                this.columnSM_idx}, true));
                this.columnSM_idx.AutoIncrement = true;
                this.columnSM_idx.AllowDBNull = false;
                this.columnSM_idx.ReadOnly = true;
                this.columnSM_idx.Unique = true;
            }
            
            public SM_TableRow NewSM_TableRow() {
                return ((SM_TableRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new SM_TableRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(SM_TableRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.SM_TableRowChanged != null)) {
                    this.SM_TableRowChanged(this, new SM_TableRowChangeEvent(((SM_TableRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.SM_TableRowChanging != null)) {
                    this.SM_TableRowChanging(this, new SM_TableRowChangeEvent(((SM_TableRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.SM_TableRowDeleted != null)) {
                    this.SM_TableRowDeleted(this, new SM_TableRowChangeEvent(((SM_TableRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.SM_TableRowDeleting != null)) {
                    this.SM_TableRowDeleting(this, new SM_TableRowChangeEvent(((SM_TableRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveSM_TableRow(SM_TableRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class SM_TableRow : DataRow {
            
            private SM_TableDataTable tableSM_Table;
            
            internal SM_TableRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableSM_Table = ((SM_TableDataTable)(this.Table));
            }
            
            public int SM_idx {
                get {
                    return ((int)(this[this.tableSM_Table.SM_idxColumn]));
                }
                set {
                    this[this.tableSM_Table.SM_idxColumn] = value;
                }
            }
            
            public string SM_StockClassify {
                get {
                    try {
                        return ((string)(this[this.tableSM_Table.SM_StockClassifyColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableSM_Table.SM_StockClassifyColumn] = value;
                }
            }
            
            public string SM_ItemNumber {
                get {
                    try {
                        return ((string)(this[this.tableSM_Table.SM_ItemNumberColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableSM_Table.SM_ItemNumberColumn] = value;
                }
            }
            
            public string SM_StockLocation {
                get {
                    try {
                        return ((string)(this[this.tableSM_Table.SM_StockLocationColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableSM_Table.SM_StockLocationColumn] = value;
                }
            }
            
            public string SM_ProcessName {
                get {
                    try {
                        return ((string)(this[this.tableSM_Table.SM_ProcessNameColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableSM_Table.SM_ProcessNameColumn] = value;
                }
            }
            
            public System.Double SM_CarryOverQuantity1 {
                get {
                    try {
                        return ((System.Double)(this[this.tableSM_Table.SM_CarryOverQuantity1Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableSM_Table.SM_CarryOverQuantity1Column] = value;
                }
            }
            
            public System.Double SM_CarryOverCost1 {
                get {
                    try {
                        return ((System.Double)(this[this.tableSM_Table.SM_CarryOverCost1Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableSM_Table.SM_CarryOverCost1Column] = value;
                }
            }
            
            public System.Double SM_StorageQuantity1 {
                get {
                    try {
                        return ((System.Double)(this[this.tableSM_Table.SM_StorageQuantity1Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableSM_Table.SM_StorageQuantity1Column] = value;
                }
            }
            
            public System.Double SM_StorageCost1 {
                get {
                    try {
                        return ((System.Double)(this[this.tableSM_Table.SM_StorageCost1Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableSM_Table.SM_StorageCost1Column] = value;
                }
            }
            
            public System.Double SM_DeliveryQuantity1 {
                get {
                    try {
                        return ((System.Double)(this[this.tableSM_Table.SM_DeliveryQuantity1Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableSM_Table.SM_DeliveryQuantity1Column] = value;
                }
            }
            
            public System.Double SM_DeliveryCost1 {
                get {
                    try {
                        return ((System.Double)(this[this.tableSM_Table.SM_DeliveryCost1Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableSM_Table.SM_DeliveryCost1Column] = value;
                }
            }
            
            public bool IsSM_StockClassifyNull() {
                return this.IsNull(this.tableSM_Table.SM_StockClassifyColumn);
            }
            
            public void SetSM_StockClassifyNull() {
                this[this.tableSM_Table.SM_StockClassifyColumn] = System.Convert.DBNull;
            }
            
            public bool IsSM_ItemNumberNull() {
                return this.IsNull(this.tableSM_Table.SM_ItemNumberColumn);
            }
            
            public void SetSM_ItemNumberNull() {
                this[this.tableSM_Table.SM_ItemNumberColumn] = System.Convert.DBNull;
            }
            
            public bool IsSM_StockLocationNull() {
                return this.IsNull(this.tableSM_Table.SM_StockLocationColumn);
            }
            
            public void SetSM_StockLocationNull() {
                this[this.tableSM_Table.SM_StockLocationColumn] = System.Convert.DBNull;
            }
            
            public bool IsSM_ProcessNameNull() {
                return this.IsNull(this.tableSM_Table.SM_ProcessNameColumn);
            }
            
            public void SetSM_ProcessNameNull() {
                this[this.tableSM_Table.SM_ProcessNameColumn] = System.Convert.DBNull;
            }
            
            public bool IsSM_CarryOverQuantity1Null() {
                return this.IsNull(this.tableSM_Table.SM_CarryOverQuantity1Column);
            }
            
            public void SetSM_CarryOverQuantity1Null() {
                this[this.tableSM_Table.SM_CarryOverQuantity1Column] = System.Convert.DBNull;
            }
            
            public bool IsSM_CarryOverCost1Null() {
                return this.IsNull(this.tableSM_Table.SM_CarryOverCost1Column);
            }
            
            public void SetSM_CarryOverCost1Null() {
                this[this.tableSM_Table.SM_CarryOverCost1Column] = System.Convert.DBNull;
            }
            
            public bool IsSM_StorageQuantity1Null() {
                return this.IsNull(this.tableSM_Table.SM_StorageQuantity1Column);
            }
            
            public void SetSM_StorageQuantity1Null() {
                this[this.tableSM_Table.SM_StorageQuantity1Column] = System.Convert.DBNull;
            }
            
            public bool IsSM_StorageCost1Null() {
                return this.IsNull(this.tableSM_Table.SM_StorageCost1Column);
            }
            
            public void SetSM_StorageCost1Null() {
                this[this.tableSM_Table.SM_StorageCost1Column] = System.Convert.DBNull;
            }
            
            public bool IsSM_DeliveryQuantity1Null() {
                return this.IsNull(this.tableSM_Table.SM_DeliveryQuantity1Column);
            }
            
            public void SetSM_DeliveryQuantity1Null() {
                this[this.tableSM_Table.SM_DeliveryQuantity1Column] = System.Convert.DBNull;
            }
            
            public bool IsSM_DeliveryCost1Null() {
                return this.IsNull(this.tableSM_Table.SM_DeliveryCost1Column);
            }
            
            public void SetSM_DeliveryCost1Null() {
                this[this.tableSM_Table.SM_DeliveryCost1Column] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class SM_TableRowChangeEvent : EventArgs {
            
            private SM_TableRow eventRow;
            
            private DataRowAction eventAction;
            
            public SM_TableRowChangeEvent(SM_TableRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public SM_TableRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
