//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2407
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace KIT_ERP.ProductionManagement {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class dsItemGruop : DataSet {
        
        private PhantomDataTable tablePhantom;
        
        public dsItemGruop() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected dsItemGruop(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["Phantom"] != null)) {
                    this.Tables.Add(new PhantomDataTable(ds.Tables["Phantom"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public PhantomDataTable Phantom {
            get {
                return this.tablePhantom;
            }
        }
        
        public override DataSet Clone() {
            dsItemGruop cln = ((dsItemGruop)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["Phantom"] != null)) {
                this.Tables.Add(new PhantomDataTable(ds.Tables["Phantom"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tablePhantom = ((PhantomDataTable)(this.Tables["Phantom"]));
            if ((this.tablePhantom != null)) {
                this.tablePhantom.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "dsItemGruop";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dsItemGruop.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tablePhantom = new PhantomDataTable();
            this.Tables.Add(this.tablePhantom);
        }
        
        private bool ShouldSerializePhantom() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void PhantomRowChangeEventHandler(object sender, PhantomRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class PhantomDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnItemNum;
            
            private DataColumn columnItemDrawNum;
            
            private DataColumn columnItemName;
            
            private DataColumn columnDeliveryOrderRequestQuantity;
            
            private DataColumn columnRowMaterialQuantityReflection;
            
            private DataColumn columnOrderNonInStorehouseReflection;
            
            private DataColumn columnOrderRequestReadyQuantityReflection;
            
            private DataColumn columnSafyRowMaterialQuantityReflection;
            
            private DataColumn columnMinimumOrderQuantityReflection;
            
            private DataColumn columnOrderGapQuantityReflection;
            
            private DataColumn columnVolumNum;
            
            private DataColumn columnProgressCondition;
            
            private DataColumn columnRegistrationPerson;
            
            private DataColumn columnRegistrationPersonID;
            
            private DataColumn columnRegistrationDate;
            
            private DataColumn columnUpdatingPerson;
            
            private DataColumn columnUpdatingPersonID;
            
            private DataColumn columnUpdatingDate;
            
            internal PhantomDataTable() : 
                    base("Phantom") {
                this.InitClass();
            }
            
            internal PhantomDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn ItemNumColumn {
                get {
                    return this.columnItemNum;
                }
            }
            
            internal DataColumn ItemDrawNumColumn {
                get {
                    return this.columnItemDrawNum;
                }
            }
            
            internal DataColumn ItemNameColumn {
                get {
                    return this.columnItemName;
                }
            }
            
            internal DataColumn DeliveryOrderRequestQuantityColumn {
                get {
                    return this.columnDeliveryOrderRequestQuantity;
                }
            }
            
            internal DataColumn RowMaterialQuantityReflectionColumn {
                get {
                    return this.columnRowMaterialQuantityReflection;
                }
            }
            
            internal DataColumn OrderNonInStorehouseReflectionColumn {
                get {
                    return this.columnOrderNonInStorehouseReflection;
                }
            }
            
            internal DataColumn OrderRequestReadyQuantityReflectionColumn {
                get {
                    return this.columnOrderRequestReadyQuantityReflection;
                }
            }
            
            internal DataColumn SafyRowMaterialQuantityReflectionColumn {
                get {
                    return this.columnSafyRowMaterialQuantityReflection;
                }
            }
            
            internal DataColumn MinimumOrderQuantityReflectionColumn {
                get {
                    return this.columnMinimumOrderQuantityReflection;
                }
            }
            
            internal DataColumn OrderGapQuantityReflectionColumn {
                get {
                    return this.columnOrderGapQuantityReflection;
                }
            }
            
            internal DataColumn VolumNumColumn {
                get {
                    return this.columnVolumNum;
                }
            }
            
            internal DataColumn ProgressConditionColumn {
                get {
                    return this.columnProgressCondition;
                }
            }
            
            internal DataColumn RegistrationPersonColumn {
                get {
                    return this.columnRegistrationPerson;
                }
            }
            
            internal DataColumn RegistrationPersonIDColumn {
                get {
                    return this.columnRegistrationPersonID;
                }
            }
            
            internal DataColumn RegistrationDateColumn {
                get {
                    return this.columnRegistrationDate;
                }
            }
            
            internal DataColumn UpdatingPersonColumn {
                get {
                    return this.columnUpdatingPerson;
                }
            }
            
            internal DataColumn UpdatingPersonIDColumn {
                get {
                    return this.columnUpdatingPersonID;
                }
            }
            
            internal DataColumn UpdatingDateColumn {
                get {
                    return this.columnUpdatingDate;
                }
            }
            
            public PhantomRow this[int index] {
                get {
                    return ((PhantomRow)(this.Rows[index]));
                }
            }
            
            public event PhantomRowChangeEventHandler PhantomRowChanged;
            
            public event PhantomRowChangeEventHandler PhantomRowChanging;
            
            public event PhantomRowChangeEventHandler PhantomRowDeleted;
            
            public event PhantomRowChangeEventHandler PhantomRowDeleting;
            
            public void AddPhantomRow(PhantomRow row) {
                this.Rows.Add(row);
            }
            
            public PhantomRow AddPhantomRow(
                        string ItemNum, 
                        string ItemDrawNum, 
                        string ItemName, 
                        System.Decimal DeliveryOrderRequestQuantity, 
                        bool RowMaterialQuantityReflection, 
                        bool OrderNonInStorehouseReflection, 
                        bool OrderRequestReadyQuantityReflection, 
                        bool SafyRowMaterialQuantityReflection, 
                        bool MinimumOrderQuantityReflection, 
                        bool OrderGapQuantityReflection, 
                        int VolumNum, 
                        string ProgressCondition, 
                        string RegistrationPerson, 
                        string RegistrationPersonID, 
                        System.DateTime RegistrationDate, 
                        string UpdatingPerson, 
                        string UpdatingPersonID, 
                        System.DateTime UpdatingDate) {
                PhantomRow rowPhantomRow = ((PhantomRow)(this.NewRow()));
                rowPhantomRow.ItemArray = new object[] {
                        ItemNum,
                        ItemDrawNum,
                        ItemName,
                        DeliveryOrderRequestQuantity,
                        RowMaterialQuantityReflection,
                        OrderNonInStorehouseReflection,
                        OrderRequestReadyQuantityReflection,
                        SafyRowMaterialQuantityReflection,
                        MinimumOrderQuantityReflection,
                        OrderGapQuantityReflection,
                        VolumNum,
                        ProgressCondition,
                        RegistrationPerson,
                        RegistrationPersonID,
                        RegistrationDate,
                        UpdatingPerson,
                        UpdatingPersonID,
                        UpdatingDate};
                this.Rows.Add(rowPhantomRow);
                return rowPhantomRow;
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                PhantomDataTable cln = ((PhantomDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new PhantomDataTable();
            }
            
            internal void InitVars() {
                this.columnItemNum = this.Columns["ItemNum"];
                this.columnItemDrawNum = this.Columns["ItemDrawNum"];
                this.columnItemName = this.Columns["ItemName"];
                this.columnDeliveryOrderRequestQuantity = this.Columns["DeliveryOrderRequestQuantity"];
                this.columnRowMaterialQuantityReflection = this.Columns["RowMaterialQuantityReflection"];
                this.columnOrderNonInStorehouseReflection = this.Columns["OrderNonInStorehouseReflection"];
                this.columnOrderRequestReadyQuantityReflection = this.Columns["OrderRequestReadyQuantityReflection"];
                this.columnSafyRowMaterialQuantityReflection = this.Columns["SafyRowMaterialQuantityReflection"];
                this.columnMinimumOrderQuantityReflection = this.Columns["MinimumOrderQuantityReflection"];
                this.columnOrderGapQuantityReflection = this.Columns["OrderGapQuantityReflection"];
                this.columnVolumNum = this.Columns["VolumNum"];
                this.columnProgressCondition = this.Columns["ProgressCondition"];
                this.columnRegistrationPerson = this.Columns["RegistrationPerson"];
                this.columnRegistrationPersonID = this.Columns["RegistrationPersonID"];
                this.columnRegistrationDate = this.Columns["RegistrationDate"];
                this.columnUpdatingPerson = this.Columns["UpdatingPerson"];
                this.columnUpdatingPersonID = this.Columns["UpdatingPersonID"];
                this.columnUpdatingDate = this.Columns["UpdatingDate"];
            }
            
            private void InitClass() {
                this.columnItemNum = new DataColumn("ItemNum", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnItemNum);
                this.columnItemDrawNum = new DataColumn("ItemDrawNum", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnItemDrawNum);
                this.columnItemName = new DataColumn("ItemName", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnItemName);
                this.columnDeliveryOrderRequestQuantity = new DataColumn("DeliveryOrderRequestQuantity", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnDeliveryOrderRequestQuantity);
                this.columnRowMaterialQuantityReflection = new DataColumn("RowMaterialQuantityReflection", typeof(bool), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnRowMaterialQuantityReflection);
                this.columnOrderNonInStorehouseReflection = new DataColumn("OrderNonInStorehouseReflection", typeof(bool), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnOrderNonInStorehouseReflection);
                this.columnOrderRequestReadyQuantityReflection = new DataColumn("OrderRequestReadyQuantityReflection", typeof(bool), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnOrderRequestReadyQuantityReflection);
                this.columnSafyRowMaterialQuantityReflection = new DataColumn("SafyRowMaterialQuantityReflection", typeof(bool), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnSafyRowMaterialQuantityReflection);
                this.columnMinimumOrderQuantityReflection = new DataColumn("MinimumOrderQuantityReflection", typeof(bool), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnMinimumOrderQuantityReflection);
                this.columnOrderGapQuantityReflection = new DataColumn("OrderGapQuantityReflection", typeof(bool), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnOrderGapQuantityReflection);
                this.columnVolumNum = new DataColumn("VolumNum", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnVolumNum);
                this.columnProgressCondition = new DataColumn("ProgressCondition", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnProgressCondition);
                this.columnRegistrationPerson = new DataColumn("RegistrationPerson", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnRegistrationPerson);
                this.columnRegistrationPersonID = new DataColumn("RegistrationPersonID", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnRegistrationPersonID);
                this.columnRegistrationDate = new DataColumn("RegistrationDate", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnRegistrationDate);
                this.columnUpdatingPerson = new DataColumn("UpdatingPerson", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnUpdatingPerson);
                this.columnUpdatingPersonID = new DataColumn("UpdatingPersonID", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnUpdatingPersonID);
                this.columnUpdatingDate = new DataColumn("UpdatingDate", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnUpdatingDate);
            }
            
            public PhantomRow NewPhantomRow() {
                return ((PhantomRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new PhantomRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(PhantomRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.PhantomRowChanged != null)) {
                    this.PhantomRowChanged(this, new PhantomRowChangeEvent(((PhantomRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.PhantomRowChanging != null)) {
                    this.PhantomRowChanging(this, new PhantomRowChangeEvent(((PhantomRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.PhantomRowDeleted != null)) {
                    this.PhantomRowDeleted(this, new PhantomRowChangeEvent(((PhantomRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.PhantomRowDeleting != null)) {
                    this.PhantomRowDeleting(this, new PhantomRowChangeEvent(((PhantomRow)(e.Row)), e.Action));
                }
            }
            
            public void RemovePhantomRow(PhantomRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class PhantomRow : DataRow {
            
            private PhantomDataTable tablePhantom;
            
            internal PhantomRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tablePhantom = ((PhantomDataTable)(this.Table));
            }
            
            public string ItemNum {
                get {
                    try {
                        return ((string)(this[this.tablePhantom.ItemNumColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tablePhantom.ItemNumColumn] = value;
                }
            }
            
            public string ItemDrawNum {
                get {
                    try {
                        return ((string)(this[this.tablePhantom.ItemDrawNumColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tablePhantom.ItemDrawNumColumn] = value;
                }
            }
            
            public string ItemName {
                get {
                    try {
                        return ((string)(this[this.tablePhantom.ItemNameColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tablePhantom.ItemNameColumn] = value;
                }
            }
            
            public System.Decimal DeliveryOrderRequestQuantity {
                get {
                    try {
                        return ((System.Decimal)(this[this.tablePhantom.DeliveryOrderRequestQuantityColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tablePhantom.DeliveryOrderRequestQuantityColumn] = value;
                }
            }
            
            public bool RowMaterialQuantityReflection {
                get {
                    try {
                        return ((bool)(this[this.tablePhantom.RowMaterialQuantityReflectionColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tablePhantom.RowMaterialQuantityReflectionColumn] = value;
                }
            }
            
            public bool OrderNonInStorehouseReflection {
                get {
                    try {
                        return ((bool)(this[this.tablePhantom.OrderNonInStorehouseReflectionColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tablePhantom.OrderNonInStorehouseReflectionColumn] = value;
                }
            }
            
            public bool OrderRequestReadyQuantityReflection {
                get {
                    try {
                        return ((bool)(this[this.tablePhantom.OrderRequestReadyQuantityReflectionColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tablePhantom.OrderRequestReadyQuantityReflectionColumn] = value;
                }
            }
            
            public bool SafyRowMaterialQuantityReflection {
                get {
                    try {
                        return ((bool)(this[this.tablePhantom.SafyRowMaterialQuantityReflectionColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tablePhantom.SafyRowMaterialQuantityReflectionColumn] = value;
                }
            }
            
            public bool MinimumOrderQuantityReflection {
                get {
                    try {
                        return ((bool)(this[this.tablePhantom.MinimumOrderQuantityReflectionColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tablePhantom.MinimumOrderQuantityReflectionColumn] = value;
                }
            }
            
            public bool OrderGapQuantityReflection {
                get {
                    try {
                        return ((bool)(this[this.tablePhantom.OrderGapQuantityReflectionColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tablePhantom.OrderGapQuantityReflectionColumn] = value;
                }
            }
            
            public int VolumNum {
                get {
                    try {
                        return ((int)(this[this.tablePhantom.VolumNumColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tablePhantom.VolumNumColumn] = value;
                }
            }
            
            public string ProgressCondition {
                get {
                    try {
                        return ((string)(this[this.tablePhantom.ProgressConditionColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tablePhantom.ProgressConditionColumn] = value;
                }
            }
            
            public string RegistrationPerson {
                get {
                    try {
                        return ((string)(this[this.tablePhantom.RegistrationPersonColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tablePhantom.RegistrationPersonColumn] = value;
                }
            }
            
            public string RegistrationPersonID {
                get {
                    try {
                        return ((string)(this[this.tablePhantom.RegistrationPersonIDColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tablePhantom.RegistrationPersonIDColumn] = value;
                }
            }
            
            public System.DateTime RegistrationDate {
                get {
                    try {
                        return ((System.DateTime)(this[this.tablePhantom.RegistrationDateColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tablePhantom.RegistrationDateColumn] = value;
                }
            }
            
            public string UpdatingPerson {
                get {
                    try {
                        return ((string)(this[this.tablePhantom.UpdatingPersonColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tablePhantom.UpdatingPersonColumn] = value;
                }
            }
            
            public string UpdatingPersonID {
                get {
                    try {
                        return ((string)(this[this.tablePhantom.UpdatingPersonIDColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tablePhantom.UpdatingPersonIDColumn] = value;
                }
            }
            
            public System.DateTime UpdatingDate {
                get {
                    try {
                        return ((System.DateTime)(this[this.tablePhantom.UpdatingDateColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tablePhantom.UpdatingDateColumn] = value;
                }
            }
            
            public bool IsItemNumNull() {
                return this.IsNull(this.tablePhantom.ItemNumColumn);
            }
            
            public void SetItemNumNull() {
                this[this.tablePhantom.ItemNumColumn] = System.Convert.DBNull;
            }
            
            public bool IsItemDrawNumNull() {
                return this.IsNull(this.tablePhantom.ItemDrawNumColumn);
            }
            
            public void SetItemDrawNumNull() {
                this[this.tablePhantom.ItemDrawNumColumn] = System.Convert.DBNull;
            }
            
            public bool IsItemNameNull() {
                return this.IsNull(this.tablePhantom.ItemNameColumn);
            }
            
            public void SetItemNameNull() {
                this[this.tablePhantom.ItemNameColumn] = System.Convert.DBNull;
            }
            
            public bool IsDeliveryOrderRequestQuantityNull() {
                return this.IsNull(this.tablePhantom.DeliveryOrderRequestQuantityColumn);
            }
            
            public void SetDeliveryOrderRequestQuantityNull() {
                this[this.tablePhantom.DeliveryOrderRequestQuantityColumn] = System.Convert.DBNull;
            }
            
            public bool IsRowMaterialQuantityReflectionNull() {
                return this.IsNull(this.tablePhantom.RowMaterialQuantityReflectionColumn);
            }
            
            public void SetRowMaterialQuantityReflectionNull() {
                this[this.tablePhantom.RowMaterialQuantityReflectionColumn] = System.Convert.DBNull;
            }
            
            public bool IsOrderNonInStorehouseReflectionNull() {
                return this.IsNull(this.tablePhantom.OrderNonInStorehouseReflectionColumn);
            }
            
            public void SetOrderNonInStorehouseReflectionNull() {
                this[this.tablePhantom.OrderNonInStorehouseReflectionColumn] = System.Convert.DBNull;
            }
            
            public bool IsOrderRequestReadyQuantityReflectionNull() {
                return this.IsNull(this.tablePhantom.OrderRequestReadyQuantityReflectionColumn);
            }
            
            public void SetOrderRequestReadyQuantityReflectionNull() {
                this[this.tablePhantom.OrderRequestReadyQuantityReflectionColumn] = System.Convert.DBNull;
            }
            
            public bool IsSafyRowMaterialQuantityReflectionNull() {
                return this.IsNull(this.tablePhantom.SafyRowMaterialQuantityReflectionColumn);
            }
            
            public void SetSafyRowMaterialQuantityReflectionNull() {
                this[this.tablePhantom.SafyRowMaterialQuantityReflectionColumn] = System.Convert.DBNull;
            }
            
            public bool IsMinimumOrderQuantityReflectionNull() {
                return this.IsNull(this.tablePhantom.MinimumOrderQuantityReflectionColumn);
            }
            
            public void SetMinimumOrderQuantityReflectionNull() {
                this[this.tablePhantom.MinimumOrderQuantityReflectionColumn] = System.Convert.DBNull;
            }
            
            public bool IsOrderGapQuantityReflectionNull() {
                return this.IsNull(this.tablePhantom.OrderGapQuantityReflectionColumn);
            }
            
            public void SetOrderGapQuantityReflectionNull() {
                this[this.tablePhantom.OrderGapQuantityReflectionColumn] = System.Convert.DBNull;
            }
            
            public bool IsVolumNumNull() {
                return this.IsNull(this.tablePhantom.VolumNumColumn);
            }
            
            public void SetVolumNumNull() {
                this[this.tablePhantom.VolumNumColumn] = System.Convert.DBNull;
            }
            
            public bool IsProgressConditionNull() {
                return this.IsNull(this.tablePhantom.ProgressConditionColumn);
            }
            
            public void SetProgressConditionNull() {
                this[this.tablePhantom.ProgressConditionColumn] = System.Convert.DBNull;
            }
            
            public bool IsRegistrationPersonNull() {
                return this.IsNull(this.tablePhantom.RegistrationPersonColumn);
            }
            
            public void SetRegistrationPersonNull() {
                this[this.tablePhantom.RegistrationPersonColumn] = System.Convert.DBNull;
            }
            
            public bool IsRegistrationPersonIDNull() {
                return this.IsNull(this.tablePhantom.RegistrationPersonIDColumn);
            }
            
            public void SetRegistrationPersonIDNull() {
                this[this.tablePhantom.RegistrationPersonIDColumn] = System.Convert.DBNull;
            }
            
            public bool IsRegistrationDateNull() {
                return this.IsNull(this.tablePhantom.RegistrationDateColumn);
            }
            
            public void SetRegistrationDateNull() {
                this[this.tablePhantom.RegistrationDateColumn] = System.Convert.DBNull;
            }
            
            public bool IsUpdatingPersonNull() {
                return this.IsNull(this.tablePhantom.UpdatingPersonColumn);
            }
            
            public void SetUpdatingPersonNull() {
                this[this.tablePhantom.UpdatingPersonColumn] = System.Convert.DBNull;
            }
            
            public bool IsUpdatingPersonIDNull() {
                return this.IsNull(this.tablePhantom.UpdatingPersonIDColumn);
            }
            
            public void SetUpdatingPersonIDNull() {
                this[this.tablePhantom.UpdatingPersonIDColumn] = System.Convert.DBNull;
            }
            
            public bool IsUpdatingDateNull() {
                return this.IsNull(this.tablePhantom.UpdatingDateColumn);
            }
            
            public void SetUpdatingDateNull() {
                this[this.tablePhantom.UpdatingDateColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class PhantomRowChangeEvent : EventArgs {
            
            private PhantomRow eventRow;
            
            private DataRowAction eventAction;
            
            public PhantomRowChangeEvent(PhantomRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public PhantomRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
