//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2407
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace KIT_ERP.ProductionManagement {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class dsPhantomErr : DataSet {
        
        private ItemGroupErr_HTDataTable tableItemGroupErr_HT;
        
        public dsPhantomErr() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected dsPhantomErr(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["ItemGroupErr_HT"] != null)) {
                    this.Tables.Add(new ItemGroupErr_HTDataTable(ds.Tables["ItemGroupErr_HT"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public ItemGroupErr_HTDataTable ItemGroupErr_HT {
            get {
                return this.tableItemGroupErr_HT;
            }
        }
        
        public override DataSet Clone() {
            dsPhantomErr cln = ((dsPhantomErr)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["ItemGroupErr_HT"] != null)) {
                this.Tables.Add(new ItemGroupErr_HTDataTable(ds.Tables["ItemGroupErr_HT"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableItemGroupErr_HT = ((ItemGroupErr_HTDataTable)(this.Tables["ItemGroupErr_HT"]));
            if ((this.tableItemGroupErr_HT != null)) {
                this.tableItemGroupErr_HT.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "dsPhantomErr";
            this.Prefix = "";
            this.Namespace = "http://www.tempuri.org/dsPhantomErr.xsd";
            this.Locale = new System.Globalization.CultureInfo("ko-KR");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableItemGroupErr_HT = new ItemGroupErr_HTDataTable();
            this.Tables.Add(this.tableItemGroupErr_HT);
        }
        
        private bool ShouldSerializeItemGroupErr_HT() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void ItemGroupErr_HTRowChangeEventHandler(object sender, ItemGroupErr_HTRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class ItemGroupErr_HTDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnItemNum;
            
            private DataColumn columnCompanyName;
            
            private DataColumn columnBusinessRegistrationNum;
            
            private DataColumn columnReceivingOrderDate;
            
            private DataColumn columnDeliveryRequestDate;
            
            private DataColumn columnTotalReceiveingOrderQuantity;
            
            private DataColumn columnErrRegion;
            
            private DataColumn columnItemGroupErrIndex;
            
            internal ItemGroupErr_HTDataTable() : 
                    base("ItemGroupErr_HT") {
                this.InitClass();
            }
            
            internal ItemGroupErr_HTDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn ItemNumColumn {
                get {
                    return this.columnItemNum;
                }
            }
            
            internal DataColumn CompanyNameColumn {
                get {
                    return this.columnCompanyName;
                }
            }
            
            internal DataColumn BusinessRegistrationNumColumn {
                get {
                    return this.columnBusinessRegistrationNum;
                }
            }
            
            internal DataColumn ReceivingOrderDateColumn {
                get {
                    return this.columnReceivingOrderDate;
                }
            }
            
            internal DataColumn DeliveryRequestDateColumn {
                get {
                    return this.columnDeliveryRequestDate;
                }
            }
            
            internal DataColumn TotalReceiveingOrderQuantityColumn {
                get {
                    return this.columnTotalReceiveingOrderQuantity;
                }
            }
            
            internal DataColumn ErrRegionColumn {
                get {
                    return this.columnErrRegion;
                }
            }
            
            internal DataColumn ItemGroupErrIndexColumn {
                get {
                    return this.columnItemGroupErrIndex;
                }
            }
            
            public ItemGroupErr_HTRow this[int index] {
                get {
                    return ((ItemGroupErr_HTRow)(this.Rows[index]));
                }
            }
            
            public event ItemGroupErr_HTRowChangeEventHandler ItemGroupErr_HTRowChanged;
            
            public event ItemGroupErr_HTRowChangeEventHandler ItemGroupErr_HTRowChanging;
            
            public event ItemGroupErr_HTRowChangeEventHandler ItemGroupErr_HTRowDeleted;
            
            public event ItemGroupErr_HTRowChangeEventHandler ItemGroupErr_HTRowDeleting;
            
            public void AddItemGroupErr_HTRow(ItemGroupErr_HTRow row) {
                this.Rows.Add(row);
            }
            
            public ItemGroupErr_HTRow AddItemGroupErr_HTRow(string ItemNum, string CompanyName, string BusinessRegistrationNum, System.DateTime ReceivingOrderDate, System.DateTime DeliveryRequestDate, System.Decimal TotalReceiveingOrderQuantity, string ErrRegion) {
                ItemGroupErr_HTRow rowItemGroupErr_HTRow = ((ItemGroupErr_HTRow)(this.NewRow()));
                rowItemGroupErr_HTRow.ItemArray = new object[] {
                        ItemNum,
                        CompanyName,
                        BusinessRegistrationNum,
                        ReceivingOrderDate,
                        DeliveryRequestDate,
                        TotalReceiveingOrderQuantity,
                        ErrRegion,
                        null};
                this.Rows.Add(rowItemGroupErr_HTRow);
                return rowItemGroupErr_HTRow;
            }
            
            public ItemGroupErr_HTRow FindByItemGroupErrIndex(int ItemGroupErrIndex) {
                return ((ItemGroupErr_HTRow)(this.Rows.Find(new object[] {
                            ItemGroupErrIndex})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                ItemGroupErr_HTDataTable cln = ((ItemGroupErr_HTDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new ItemGroupErr_HTDataTable();
            }
            
            internal void InitVars() {
                this.columnItemNum = this.Columns["ItemNum"];
                this.columnCompanyName = this.Columns["CompanyName"];
                this.columnBusinessRegistrationNum = this.Columns["BusinessRegistrationNum"];
                this.columnReceivingOrderDate = this.Columns["ReceivingOrderDate"];
                this.columnDeliveryRequestDate = this.Columns["DeliveryRequestDate"];
                this.columnTotalReceiveingOrderQuantity = this.Columns["TotalReceiveingOrderQuantity"];
                this.columnErrRegion = this.Columns["ErrRegion"];
                this.columnItemGroupErrIndex = this.Columns["ItemGroupErrIndex"];
            }
            
            private void InitClass() {
                this.columnItemNum = new DataColumn("ItemNum", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnItemNum);
                this.columnCompanyName = new DataColumn("CompanyName", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnCompanyName);
                this.columnBusinessRegistrationNum = new DataColumn("BusinessRegistrationNum", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnBusinessRegistrationNum);
                this.columnReceivingOrderDate = new DataColumn("ReceivingOrderDate", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnReceivingOrderDate);
                this.columnDeliveryRequestDate = new DataColumn("DeliveryRequestDate", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnDeliveryRequestDate);
                this.columnTotalReceiveingOrderQuantity = new DataColumn("TotalReceiveingOrderQuantity", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnTotalReceiveingOrderQuantity);
                this.columnErrRegion = new DataColumn("ErrRegion", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnErrRegion);
                this.columnItemGroupErrIndex = new DataColumn("ItemGroupErrIndex", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnItemGroupErrIndex);
                this.Constraints.Add(new UniqueConstraint("Constraint1", new DataColumn[] {
                                this.columnItemGroupErrIndex}, true));
                this.columnItemGroupErrIndex.AutoIncrement = true;
                this.columnItemGroupErrIndex.AllowDBNull = false;
                this.columnItemGroupErrIndex.ReadOnly = true;
                this.columnItemGroupErrIndex.Unique = true;
            }
            
            public ItemGroupErr_HTRow NewItemGroupErr_HTRow() {
                return ((ItemGroupErr_HTRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new ItemGroupErr_HTRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(ItemGroupErr_HTRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.ItemGroupErr_HTRowChanged != null)) {
                    this.ItemGroupErr_HTRowChanged(this, new ItemGroupErr_HTRowChangeEvent(((ItemGroupErr_HTRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.ItemGroupErr_HTRowChanging != null)) {
                    this.ItemGroupErr_HTRowChanging(this, new ItemGroupErr_HTRowChangeEvent(((ItemGroupErr_HTRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.ItemGroupErr_HTRowDeleted != null)) {
                    this.ItemGroupErr_HTRowDeleted(this, new ItemGroupErr_HTRowChangeEvent(((ItemGroupErr_HTRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.ItemGroupErr_HTRowDeleting != null)) {
                    this.ItemGroupErr_HTRowDeleting(this, new ItemGroupErr_HTRowChangeEvent(((ItemGroupErr_HTRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveItemGroupErr_HTRow(ItemGroupErr_HTRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class ItemGroupErr_HTRow : DataRow {
            
            private ItemGroupErr_HTDataTable tableItemGroupErr_HT;
            
            internal ItemGroupErr_HTRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableItemGroupErr_HT = ((ItemGroupErr_HTDataTable)(this.Table));
            }
            
            public string ItemNum {
                get {
                    try {
                        return ((string)(this[this.tableItemGroupErr_HT.ItemNumColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableItemGroupErr_HT.ItemNumColumn] = value;
                }
            }
            
            public string CompanyName {
                get {
                    try {
                        return ((string)(this[this.tableItemGroupErr_HT.CompanyNameColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableItemGroupErr_HT.CompanyNameColumn] = value;
                }
            }
            
            public string BusinessRegistrationNum {
                get {
                    try {
                        return ((string)(this[this.tableItemGroupErr_HT.BusinessRegistrationNumColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableItemGroupErr_HT.BusinessRegistrationNumColumn] = value;
                }
            }
            
            public System.DateTime ReceivingOrderDate {
                get {
                    try {
                        return ((System.DateTime)(this[this.tableItemGroupErr_HT.ReceivingOrderDateColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableItemGroupErr_HT.ReceivingOrderDateColumn] = value;
                }
            }
            
            public System.DateTime DeliveryRequestDate {
                get {
                    try {
                        return ((System.DateTime)(this[this.tableItemGroupErr_HT.DeliveryRequestDateColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableItemGroupErr_HT.DeliveryRequestDateColumn] = value;
                }
            }
            
            public System.Decimal TotalReceiveingOrderQuantity {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableItemGroupErr_HT.TotalReceiveingOrderQuantityColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableItemGroupErr_HT.TotalReceiveingOrderQuantityColumn] = value;
                }
            }
            
            public string ErrRegion {
                get {
                    try {
                        return ((string)(this[this.tableItemGroupErr_HT.ErrRegionColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableItemGroupErr_HT.ErrRegionColumn] = value;
                }
            }
            
            public int ItemGroupErrIndex {
                get {
                    return ((int)(this[this.tableItemGroupErr_HT.ItemGroupErrIndexColumn]));
                }
                set {
                    this[this.tableItemGroupErr_HT.ItemGroupErrIndexColumn] = value;
                }
            }
            
            public bool IsItemNumNull() {
                return this.IsNull(this.tableItemGroupErr_HT.ItemNumColumn);
            }
            
            public void SetItemNumNull() {
                this[this.tableItemGroupErr_HT.ItemNumColumn] = System.Convert.DBNull;
            }
            
            public bool IsCompanyNameNull() {
                return this.IsNull(this.tableItemGroupErr_HT.CompanyNameColumn);
            }
            
            public void SetCompanyNameNull() {
                this[this.tableItemGroupErr_HT.CompanyNameColumn] = System.Convert.DBNull;
            }
            
            public bool IsBusinessRegistrationNumNull() {
                return this.IsNull(this.tableItemGroupErr_HT.BusinessRegistrationNumColumn);
            }
            
            public void SetBusinessRegistrationNumNull() {
                this[this.tableItemGroupErr_HT.BusinessRegistrationNumColumn] = System.Convert.DBNull;
            }
            
            public bool IsReceivingOrderDateNull() {
                return this.IsNull(this.tableItemGroupErr_HT.ReceivingOrderDateColumn);
            }
            
            public void SetReceivingOrderDateNull() {
                this[this.tableItemGroupErr_HT.ReceivingOrderDateColumn] = System.Convert.DBNull;
            }
            
            public bool IsDeliveryRequestDateNull() {
                return this.IsNull(this.tableItemGroupErr_HT.DeliveryRequestDateColumn);
            }
            
            public void SetDeliveryRequestDateNull() {
                this[this.tableItemGroupErr_HT.DeliveryRequestDateColumn] = System.Convert.DBNull;
            }
            
            public bool IsTotalReceiveingOrderQuantityNull() {
                return this.IsNull(this.tableItemGroupErr_HT.TotalReceiveingOrderQuantityColumn);
            }
            
            public void SetTotalReceiveingOrderQuantityNull() {
                this[this.tableItemGroupErr_HT.TotalReceiveingOrderQuantityColumn] = System.Convert.DBNull;
            }
            
            public bool IsErrRegionNull() {
                return this.IsNull(this.tableItemGroupErr_HT.ErrRegionColumn);
            }
            
            public void SetErrRegionNull() {
                this[this.tableItemGroupErr_HT.ErrRegionColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class ItemGroupErr_HTRowChangeEvent : EventArgs {
            
            private ItemGroupErr_HTRow eventRow;
            
            private DataRowAction eventAction;
            
            public ItemGroupErr_HTRowChangeEvent(ItemGroupErr_HTRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public ItemGroupErr_HTRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
