//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2407
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace KIT_ERP.ProductionManagement {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class dsPhantom : DataSet {
        
        private ItemGroup_HTDataTable tableItemGroup_HT;
        
        public dsPhantom() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected dsPhantom(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["ItemGroup_HT"] != null)) {
                    this.Tables.Add(new ItemGroup_HTDataTable(ds.Tables["ItemGroup_HT"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public ItemGroup_HTDataTable ItemGroup_HT {
            get {
                return this.tableItemGroup_HT;
            }
        }
        
        public override DataSet Clone() {
            dsPhantom cln = ((dsPhantom)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["ItemGroup_HT"] != null)) {
                this.Tables.Add(new ItemGroup_HTDataTable(ds.Tables["ItemGroup_HT"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableItemGroup_HT = ((ItemGroup_HTDataTable)(this.Tables["ItemGroup_HT"]));
            if ((this.tableItemGroup_HT != null)) {
                this.tableItemGroup_HT.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "dsPhantom";
            this.Prefix = "";
            this.Namespace = "http://www.tempuri.org/dsPhantom.xsd";
            this.Locale = new System.Globalization.CultureInfo("ko-KR");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableItemGroup_HT = new ItemGroup_HTDataTable();
            this.Tables.Add(this.tableItemGroup_HT);
        }
        
        private bool ShouldSerializeItemGroup_HT() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void ItemGroup_HTRowChangeEventHandler(object sender, ItemGroup_HTRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class ItemGroup_HTDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnItemGroup;
            
            private DataColumn columnReceivingOrderDate;
            
            private DataColumn columnDeliveryDate;
            
            private DataColumn columnQuantity;
            
            private DataColumn columnProgressCondition;
            
            private DataColumn columnItemGroupIndex;
            
            internal ItemGroup_HTDataTable() : 
                    base("ItemGroup_HT") {
                this.InitClass();
            }
            
            internal ItemGroup_HTDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn ItemGroupColumn {
                get {
                    return this.columnItemGroup;
                }
            }
            
            internal DataColumn ReceivingOrderDateColumn {
                get {
                    return this.columnReceivingOrderDate;
                }
            }
            
            internal DataColumn DeliveryDateColumn {
                get {
                    return this.columnDeliveryDate;
                }
            }
            
            internal DataColumn QuantityColumn {
                get {
                    return this.columnQuantity;
                }
            }
            
            internal DataColumn ProgressConditionColumn {
                get {
                    return this.columnProgressCondition;
                }
            }
            
            internal DataColumn ItemGroupIndexColumn {
                get {
                    return this.columnItemGroupIndex;
                }
            }
            
            public ItemGroup_HTRow this[int index] {
                get {
                    return ((ItemGroup_HTRow)(this.Rows[index]));
                }
            }
            
            public event ItemGroup_HTRowChangeEventHandler ItemGroup_HTRowChanged;
            
            public event ItemGroup_HTRowChangeEventHandler ItemGroup_HTRowChanging;
            
            public event ItemGroup_HTRowChangeEventHandler ItemGroup_HTRowDeleted;
            
            public event ItemGroup_HTRowChangeEventHandler ItemGroup_HTRowDeleting;
            
            public void AddItemGroup_HTRow(ItemGroup_HTRow row) {
                this.Rows.Add(row);
            }
            
            public ItemGroup_HTRow AddItemGroup_HTRow(string ItemGroup, System.DateTime ReceivingOrderDate, System.DateTime DeliveryDate, System.Decimal Quantity, string ProgressCondition) {
                ItemGroup_HTRow rowItemGroup_HTRow = ((ItemGroup_HTRow)(this.NewRow()));
                rowItemGroup_HTRow.ItemArray = new object[] {
                        ItemGroup,
                        ReceivingOrderDate,
                        DeliveryDate,
                        Quantity,
                        ProgressCondition,
                        null};
                this.Rows.Add(rowItemGroup_HTRow);
                return rowItemGroup_HTRow;
            }
            
            public ItemGroup_HTRow FindByItemGroupIndex(int ItemGroupIndex) {
                return ((ItemGroup_HTRow)(this.Rows.Find(new object[] {
                            ItemGroupIndex})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                ItemGroup_HTDataTable cln = ((ItemGroup_HTDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new ItemGroup_HTDataTable();
            }
            
            internal void InitVars() {
                this.columnItemGroup = this.Columns["ItemGroup"];
                this.columnReceivingOrderDate = this.Columns["ReceivingOrderDate"];
                this.columnDeliveryDate = this.Columns["DeliveryDate"];
                this.columnQuantity = this.Columns["Quantity"];
                this.columnProgressCondition = this.Columns["ProgressCondition"];
                this.columnItemGroupIndex = this.Columns["ItemGroupIndex"];
            }
            
            private void InitClass() {
                this.columnItemGroup = new DataColumn("ItemGroup", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnItemGroup);
                this.columnReceivingOrderDate = new DataColumn("ReceivingOrderDate", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnReceivingOrderDate);
                this.columnDeliveryDate = new DataColumn("DeliveryDate", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnDeliveryDate);
                this.columnQuantity = new DataColumn("Quantity", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnQuantity);
                this.columnProgressCondition = new DataColumn("ProgressCondition", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnProgressCondition);
                this.columnItemGroupIndex = new DataColumn("ItemGroupIndex", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnItemGroupIndex);
                this.Constraints.Add(new UniqueConstraint("Constraint1", new DataColumn[] {
                                this.columnItemGroupIndex}, true));
                this.columnItemGroupIndex.AutoIncrement = true;
                this.columnItemGroupIndex.AllowDBNull = false;
                this.columnItemGroupIndex.ReadOnly = true;
                this.columnItemGroupIndex.Unique = true;
            }
            
            public ItemGroup_HTRow NewItemGroup_HTRow() {
                return ((ItemGroup_HTRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new ItemGroup_HTRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(ItemGroup_HTRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.ItemGroup_HTRowChanged != null)) {
                    this.ItemGroup_HTRowChanged(this, new ItemGroup_HTRowChangeEvent(((ItemGroup_HTRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.ItemGroup_HTRowChanging != null)) {
                    this.ItemGroup_HTRowChanging(this, new ItemGroup_HTRowChangeEvent(((ItemGroup_HTRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.ItemGroup_HTRowDeleted != null)) {
                    this.ItemGroup_HTRowDeleted(this, new ItemGroup_HTRowChangeEvent(((ItemGroup_HTRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.ItemGroup_HTRowDeleting != null)) {
                    this.ItemGroup_HTRowDeleting(this, new ItemGroup_HTRowChangeEvent(((ItemGroup_HTRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveItemGroup_HTRow(ItemGroup_HTRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class ItemGroup_HTRow : DataRow {
            
            private ItemGroup_HTDataTable tableItemGroup_HT;
            
            internal ItemGroup_HTRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableItemGroup_HT = ((ItemGroup_HTDataTable)(this.Table));
            }
            
            public string ItemGroup {
                get {
                    try {
                        return ((string)(this[this.tableItemGroup_HT.ItemGroupColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableItemGroup_HT.ItemGroupColumn] = value;
                }
            }
            
            public System.DateTime ReceivingOrderDate {
                get {
                    try {
                        return ((System.DateTime)(this[this.tableItemGroup_HT.ReceivingOrderDateColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableItemGroup_HT.ReceivingOrderDateColumn] = value;
                }
            }
            
            public System.DateTime DeliveryDate {
                get {
                    try {
                        return ((System.DateTime)(this[this.tableItemGroup_HT.DeliveryDateColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableItemGroup_HT.DeliveryDateColumn] = value;
                }
            }
            
            public System.Decimal Quantity {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableItemGroup_HT.QuantityColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableItemGroup_HT.QuantityColumn] = value;
                }
            }
            
            public string ProgressCondition {
                get {
                    try {
                        return ((string)(this[this.tableItemGroup_HT.ProgressConditionColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableItemGroup_HT.ProgressConditionColumn] = value;
                }
            }
            
            public int ItemGroupIndex {
                get {
                    return ((int)(this[this.tableItemGroup_HT.ItemGroupIndexColumn]));
                }
                set {
                    this[this.tableItemGroup_HT.ItemGroupIndexColumn] = value;
                }
            }
            
            public bool IsItemGroupNull() {
                return this.IsNull(this.tableItemGroup_HT.ItemGroupColumn);
            }
            
            public void SetItemGroupNull() {
                this[this.tableItemGroup_HT.ItemGroupColumn] = System.Convert.DBNull;
            }
            
            public bool IsReceivingOrderDateNull() {
                return this.IsNull(this.tableItemGroup_HT.ReceivingOrderDateColumn);
            }
            
            public void SetReceivingOrderDateNull() {
                this[this.tableItemGroup_HT.ReceivingOrderDateColumn] = System.Convert.DBNull;
            }
            
            public bool IsDeliveryDateNull() {
                return this.IsNull(this.tableItemGroup_HT.DeliveryDateColumn);
            }
            
            public void SetDeliveryDateNull() {
                this[this.tableItemGroup_HT.DeliveryDateColumn] = System.Convert.DBNull;
            }
            
            public bool IsQuantityNull() {
                return this.IsNull(this.tableItemGroup_HT.QuantityColumn);
            }
            
            public void SetQuantityNull() {
                this[this.tableItemGroup_HT.QuantityColumn] = System.Convert.DBNull;
            }
            
            public bool IsProgressConditionNull() {
                return this.IsNull(this.tableItemGroup_HT.ProgressConditionColumn);
            }
            
            public void SetProgressConditionNull() {
                this[this.tableItemGroup_HT.ProgressConditionColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class ItemGroup_HTRowChangeEvent : EventArgs {
            
            private ItemGroup_HTRow eventRow;
            
            private DataRowAction eventAction;
            
            public ItemGroup_HTRowChangeEvent(ItemGroup_HTRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public ItemGroup_HTRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
