//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2407
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace KIT_ERP.ProductionManagement {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class dsPlanQuantityResult : DataSet {
        
        private TempGroupViewPP_HTDataTable tableTempGroupViewPP_HT;
        
        public dsPlanQuantityResult() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected dsPlanQuantityResult(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["TempGroupViewPP_HT"] != null)) {
                    this.Tables.Add(new TempGroupViewPP_HTDataTable(ds.Tables["TempGroupViewPP_HT"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public TempGroupViewPP_HTDataTable TempGroupViewPP_HT {
            get {
                return this.tableTempGroupViewPP_HT;
            }
        }
        
        public override DataSet Clone() {
            dsPlanQuantityResult cln = ((dsPlanQuantityResult)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["TempGroupViewPP_HT"] != null)) {
                this.Tables.Add(new TempGroupViewPP_HTDataTable(ds.Tables["TempGroupViewPP_HT"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableTempGroupViewPP_HT = ((TempGroupViewPP_HTDataTable)(this.Tables["TempGroupViewPP_HT"]));
            if ((this.tableTempGroupViewPP_HT != null)) {
                this.tableTempGroupViewPP_HT.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "dsPlanQuantityResult";
            this.Prefix = "";
            this.Namespace = "http://www.tempuri.org/dsPlanQuantityResult.xsd";
            this.Locale = new System.Globalization.CultureInfo("ko-KR");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableTempGroupViewPP_HT = new TempGroupViewPP_HTDataTable();
            this.Tables.Add(this.tableTempGroupViewPP_HT);
        }
        
        private bool ShouldSerializeTempGroupViewPP_HT() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void TempGroupViewPP_HTRowChangeEventHandler(object sender, TempGroupViewPP_HTRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class TempGroupViewPP_HTDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnIdx;
            
            private DataColumn columnPropertyClassification;
            
            private DataColumn columnType;
            
            private DataColumn columnItemNum;
            
            private DataColumn columnItemName;
            
            private DataColumn columnOrderRemainQuantity;
            
            private DataColumn columnPlanRemainQuantity;
            
            private DataColumn columnInsufficiencyQuantity;
            
            private DataColumn columnStockQuantity;
            
            private DataColumn columnThisPlanQuantity;
            
            private DataColumn columnNeedQuantity;
            
            private DataColumn columnProductionCompleteDate;
            
            private DataColumn columnProductionBeginDate;
            
            internal TempGroupViewPP_HTDataTable() : 
                    base("TempGroupViewPP_HT") {
                this.InitClass();
            }
            
            internal TempGroupViewPP_HTDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn IdxColumn {
                get {
                    return this.columnIdx;
                }
            }
            
            internal DataColumn PropertyClassificationColumn {
                get {
                    return this.columnPropertyClassification;
                }
            }
            
            internal DataColumn TypeColumn {
                get {
                    return this.columnType;
                }
            }
            
            internal DataColumn ItemNumColumn {
                get {
                    return this.columnItemNum;
                }
            }
            
            internal DataColumn ItemNameColumn {
                get {
                    return this.columnItemName;
                }
            }
            
            internal DataColumn OrderRemainQuantityColumn {
                get {
                    return this.columnOrderRemainQuantity;
                }
            }
            
            internal DataColumn PlanRemainQuantityColumn {
                get {
                    return this.columnPlanRemainQuantity;
                }
            }
            
            internal DataColumn InsufficiencyQuantityColumn {
                get {
                    return this.columnInsufficiencyQuantity;
                }
            }
            
            internal DataColumn StockQuantityColumn {
                get {
                    return this.columnStockQuantity;
                }
            }
            
            internal DataColumn ThisPlanQuantityColumn {
                get {
                    return this.columnThisPlanQuantity;
                }
            }
            
            internal DataColumn NeedQuantityColumn {
                get {
                    return this.columnNeedQuantity;
                }
            }
            
            internal DataColumn ProductionCompleteDateColumn {
                get {
                    return this.columnProductionCompleteDate;
                }
            }
            
            internal DataColumn ProductionBeginDateColumn {
                get {
                    return this.columnProductionBeginDate;
                }
            }
            
            public TempGroupViewPP_HTRow this[int index] {
                get {
                    return ((TempGroupViewPP_HTRow)(this.Rows[index]));
                }
            }
            
            public event TempGroupViewPP_HTRowChangeEventHandler TempGroupViewPP_HTRowChanged;
            
            public event TempGroupViewPP_HTRowChangeEventHandler TempGroupViewPP_HTRowChanging;
            
            public event TempGroupViewPP_HTRowChangeEventHandler TempGroupViewPP_HTRowDeleted;
            
            public event TempGroupViewPP_HTRowChangeEventHandler TempGroupViewPP_HTRowDeleting;
            
            public void AddTempGroupViewPP_HTRow(TempGroupViewPP_HTRow row) {
                this.Rows.Add(row);
            }
            
            public TempGroupViewPP_HTRow AddTempGroupViewPP_HTRow(string PropertyClassification, string Type, string ItemNum, string ItemName, System.Decimal OrderRemainQuantity, System.Decimal PlanRemainQuantity, System.Decimal InsufficiencyQuantity, System.Decimal StockQuantity, System.Decimal ThisPlanQuantity, System.Decimal NeedQuantity, System.DateTime ProductionCompleteDate, System.DateTime ProductionBeginDate) {
                TempGroupViewPP_HTRow rowTempGroupViewPP_HTRow = ((TempGroupViewPP_HTRow)(this.NewRow()));
                rowTempGroupViewPP_HTRow.ItemArray = new object[] {
                        null,
                        PropertyClassification,
                        Type,
                        ItemNum,
                        ItemName,
                        OrderRemainQuantity,
                        PlanRemainQuantity,
                        InsufficiencyQuantity,
                        StockQuantity,
                        ThisPlanQuantity,
                        NeedQuantity,
                        ProductionCompleteDate,
                        ProductionBeginDate};
                this.Rows.Add(rowTempGroupViewPP_HTRow);
                return rowTempGroupViewPP_HTRow;
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                TempGroupViewPP_HTDataTable cln = ((TempGroupViewPP_HTDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new TempGroupViewPP_HTDataTable();
            }
            
            internal void InitVars() {
                this.columnIdx = this.Columns["Idx"];
                this.columnPropertyClassification = this.Columns["PropertyClassification"];
                this.columnType = this.Columns["Type"];
                this.columnItemNum = this.Columns["ItemNum"];
                this.columnItemName = this.Columns["ItemName"];
                this.columnOrderRemainQuantity = this.Columns["OrderRemainQuantity"];
                this.columnPlanRemainQuantity = this.Columns["PlanRemainQuantity"];
                this.columnInsufficiencyQuantity = this.Columns["InsufficiencyQuantity"];
                this.columnStockQuantity = this.Columns["StockQuantity"];
                this.columnThisPlanQuantity = this.Columns["ThisPlanQuantity"];
                this.columnNeedQuantity = this.Columns["NeedQuantity"];
                this.columnProductionCompleteDate = this.Columns["ProductionCompleteDate"];
                this.columnProductionBeginDate = this.Columns["ProductionBeginDate"];
            }
            
            private void InitClass() {
                this.columnIdx = new DataColumn("Idx", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnIdx);
                this.columnPropertyClassification = new DataColumn("PropertyClassification", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPropertyClassification);
                this.columnType = new DataColumn("Type", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnType);
                this.columnItemNum = new DataColumn("ItemNum", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnItemNum);
                this.columnItemName = new DataColumn("ItemName", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnItemName);
                this.columnOrderRemainQuantity = new DataColumn("OrderRemainQuantity", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnOrderRemainQuantity);
                this.columnPlanRemainQuantity = new DataColumn("PlanRemainQuantity", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPlanRemainQuantity);
                this.columnInsufficiencyQuantity = new DataColumn("InsufficiencyQuantity", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnInsufficiencyQuantity);
                this.columnStockQuantity = new DataColumn("StockQuantity", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnStockQuantity);
                this.columnThisPlanQuantity = new DataColumn("ThisPlanQuantity", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnThisPlanQuantity);
                this.columnNeedQuantity = new DataColumn("NeedQuantity", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnNeedQuantity);
                this.columnProductionCompleteDate = new DataColumn("ProductionCompleteDate", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnProductionCompleteDate);
                this.columnProductionBeginDate = new DataColumn("ProductionBeginDate", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnProductionBeginDate);
                this.columnIdx.AutoIncrement = true;
                this.columnIdx.AllowDBNull = false;
                this.columnIdx.ReadOnly = true;
            }
            
            public TempGroupViewPP_HTRow NewTempGroupViewPP_HTRow() {
                return ((TempGroupViewPP_HTRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new TempGroupViewPP_HTRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(TempGroupViewPP_HTRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.TempGroupViewPP_HTRowChanged != null)) {
                    this.TempGroupViewPP_HTRowChanged(this, new TempGroupViewPP_HTRowChangeEvent(((TempGroupViewPP_HTRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.TempGroupViewPP_HTRowChanging != null)) {
                    this.TempGroupViewPP_HTRowChanging(this, new TempGroupViewPP_HTRowChangeEvent(((TempGroupViewPP_HTRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.TempGroupViewPP_HTRowDeleted != null)) {
                    this.TempGroupViewPP_HTRowDeleted(this, new TempGroupViewPP_HTRowChangeEvent(((TempGroupViewPP_HTRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.TempGroupViewPP_HTRowDeleting != null)) {
                    this.TempGroupViewPP_HTRowDeleting(this, new TempGroupViewPP_HTRowChangeEvent(((TempGroupViewPP_HTRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveTempGroupViewPP_HTRow(TempGroupViewPP_HTRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class TempGroupViewPP_HTRow : DataRow {
            
            private TempGroupViewPP_HTDataTable tableTempGroupViewPP_HT;
            
            internal TempGroupViewPP_HTRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableTempGroupViewPP_HT = ((TempGroupViewPP_HTDataTable)(this.Table));
            }
            
            public int Idx {
                get {
                    return ((int)(this[this.tableTempGroupViewPP_HT.IdxColumn]));
                }
                set {
                    this[this.tableTempGroupViewPP_HT.IdxColumn] = value;
                }
            }
            
            public string PropertyClassification {
                get {
                    try {
                        return ((string)(this[this.tableTempGroupViewPP_HT.PropertyClassificationColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableTempGroupViewPP_HT.PropertyClassificationColumn] = value;
                }
            }
            
            public string Type {
                get {
                    try {
                        return ((string)(this[this.tableTempGroupViewPP_HT.TypeColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableTempGroupViewPP_HT.TypeColumn] = value;
                }
            }
            
            public string ItemNum {
                get {
                    try {
                        return ((string)(this[this.tableTempGroupViewPP_HT.ItemNumColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableTempGroupViewPP_HT.ItemNumColumn] = value;
                }
            }
            
            public string ItemName {
                get {
                    try {
                        return ((string)(this[this.tableTempGroupViewPP_HT.ItemNameColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableTempGroupViewPP_HT.ItemNameColumn] = value;
                }
            }
            
            public System.Decimal OrderRemainQuantity {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableTempGroupViewPP_HT.OrderRemainQuantityColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableTempGroupViewPP_HT.OrderRemainQuantityColumn] = value;
                }
            }
            
            public System.Decimal PlanRemainQuantity {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableTempGroupViewPP_HT.PlanRemainQuantityColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableTempGroupViewPP_HT.PlanRemainQuantityColumn] = value;
                }
            }
            
            public System.Decimal InsufficiencyQuantity {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableTempGroupViewPP_HT.InsufficiencyQuantityColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableTempGroupViewPP_HT.InsufficiencyQuantityColumn] = value;
                }
            }
            
            public System.Decimal StockQuantity {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableTempGroupViewPP_HT.StockQuantityColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableTempGroupViewPP_HT.StockQuantityColumn] = value;
                }
            }
            
            public System.Decimal ThisPlanQuantity {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableTempGroupViewPP_HT.ThisPlanQuantityColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableTempGroupViewPP_HT.ThisPlanQuantityColumn] = value;
                }
            }
            
            public System.Decimal NeedQuantity {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableTempGroupViewPP_HT.NeedQuantityColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableTempGroupViewPP_HT.NeedQuantityColumn] = value;
                }
            }
            
            public System.DateTime ProductionCompleteDate {
                get {
                    try {
                        return ((System.DateTime)(this[this.tableTempGroupViewPP_HT.ProductionCompleteDateColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableTempGroupViewPP_HT.ProductionCompleteDateColumn] = value;
                }
            }
            
            public System.DateTime ProductionBeginDate {
                get {
                    try {
                        return ((System.DateTime)(this[this.tableTempGroupViewPP_HT.ProductionBeginDateColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableTempGroupViewPP_HT.ProductionBeginDateColumn] = value;
                }
            }
            
            public bool IsPropertyClassificationNull() {
                return this.IsNull(this.tableTempGroupViewPP_HT.PropertyClassificationColumn);
            }
            
            public void SetPropertyClassificationNull() {
                this[this.tableTempGroupViewPP_HT.PropertyClassificationColumn] = System.Convert.DBNull;
            }
            
            public bool IsTypeNull() {
                return this.IsNull(this.tableTempGroupViewPP_HT.TypeColumn);
            }
            
            public void SetTypeNull() {
                this[this.tableTempGroupViewPP_HT.TypeColumn] = System.Convert.DBNull;
            }
            
            public bool IsItemNumNull() {
                return this.IsNull(this.tableTempGroupViewPP_HT.ItemNumColumn);
            }
            
            public void SetItemNumNull() {
                this[this.tableTempGroupViewPP_HT.ItemNumColumn] = System.Convert.DBNull;
            }
            
            public bool IsItemNameNull() {
                return this.IsNull(this.tableTempGroupViewPP_HT.ItemNameColumn);
            }
            
            public void SetItemNameNull() {
                this[this.tableTempGroupViewPP_HT.ItemNameColumn] = System.Convert.DBNull;
            }
            
            public bool IsOrderRemainQuantityNull() {
                return this.IsNull(this.tableTempGroupViewPP_HT.OrderRemainQuantityColumn);
            }
            
            public void SetOrderRemainQuantityNull() {
                this[this.tableTempGroupViewPP_HT.OrderRemainQuantityColumn] = System.Convert.DBNull;
            }
            
            public bool IsPlanRemainQuantityNull() {
                return this.IsNull(this.tableTempGroupViewPP_HT.PlanRemainQuantityColumn);
            }
            
            public void SetPlanRemainQuantityNull() {
                this[this.tableTempGroupViewPP_HT.PlanRemainQuantityColumn] = System.Convert.DBNull;
            }
            
            public bool IsInsufficiencyQuantityNull() {
                return this.IsNull(this.tableTempGroupViewPP_HT.InsufficiencyQuantityColumn);
            }
            
            public void SetInsufficiencyQuantityNull() {
                this[this.tableTempGroupViewPP_HT.InsufficiencyQuantityColumn] = System.Convert.DBNull;
            }
            
            public bool IsStockQuantityNull() {
                return this.IsNull(this.tableTempGroupViewPP_HT.StockQuantityColumn);
            }
            
            public void SetStockQuantityNull() {
                this[this.tableTempGroupViewPP_HT.StockQuantityColumn] = System.Convert.DBNull;
            }
            
            public bool IsThisPlanQuantityNull() {
                return this.IsNull(this.tableTempGroupViewPP_HT.ThisPlanQuantityColumn);
            }
            
            public void SetThisPlanQuantityNull() {
                this[this.tableTempGroupViewPP_HT.ThisPlanQuantityColumn] = System.Convert.DBNull;
            }
            
            public bool IsNeedQuantityNull() {
                return this.IsNull(this.tableTempGroupViewPP_HT.NeedQuantityColumn);
            }
            
            public void SetNeedQuantityNull() {
                this[this.tableTempGroupViewPP_HT.NeedQuantityColumn] = System.Convert.DBNull;
            }
            
            public bool IsProductionCompleteDateNull() {
                return this.IsNull(this.tableTempGroupViewPP_HT.ProductionCompleteDateColumn);
            }
            
            public void SetProductionCompleteDateNull() {
                this[this.tableTempGroupViewPP_HT.ProductionCompleteDateColumn] = System.Convert.DBNull;
            }
            
            public bool IsProductionBeginDateNull() {
                return this.IsNull(this.tableTempGroupViewPP_HT.ProductionBeginDateColumn);
            }
            
            public void SetProductionBeginDateNull() {
                this[this.tableTempGroupViewPP_HT.ProductionBeginDateColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class TempGroupViewPP_HTRowChangeEvent : EventArgs {
            
            private TempGroupViewPP_HTRow eventRow;
            
            private DataRowAction eventAction;
            
            public TempGroupViewPP_HTRowChangeEvent(TempGroupViewPP_HTRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public TempGroupViewPP_HTRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
