//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace KIT_ERP.ProductionManagement {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class dsRowMaterial : DataSet {
        
        private MRC_HTDataTable tableMRC_HT;
        
        private RowMaterialDataTable tableRowMaterial;
        
        private RowMaterialQuantityDataTable tableRowMaterialQuantity;
        
        public dsRowMaterial() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected dsRowMaterial(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["MRC_HT"] != null)) {
                    this.Tables.Add(new MRC_HTDataTable(ds.Tables["MRC_HT"]));
                }
                if ((ds.Tables["RowMaterial"] != null)) {
                    this.Tables.Add(new RowMaterialDataTable(ds.Tables["RowMaterial"]));
                }
                if ((ds.Tables["RowMaterialQuantity"] != null)) {
                    this.Tables.Add(new RowMaterialQuantityDataTable(ds.Tables["RowMaterialQuantity"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public MRC_HTDataTable MRC_HT {
            get {
                return this.tableMRC_HT;
            }
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public RowMaterialDataTable RowMaterial {
            get {
                return this.tableRowMaterial;
            }
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public RowMaterialQuantityDataTable RowMaterialQuantity {
            get {
                return this.tableRowMaterialQuantity;
            }
        }
        
        public override DataSet Clone() {
            dsRowMaterial cln = ((dsRowMaterial)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["MRC_HT"] != null)) {
                this.Tables.Add(new MRC_HTDataTable(ds.Tables["MRC_HT"]));
            }
            if ((ds.Tables["RowMaterial"] != null)) {
                this.Tables.Add(new RowMaterialDataTable(ds.Tables["RowMaterial"]));
            }
            if ((ds.Tables["RowMaterialQuantity"] != null)) {
                this.Tables.Add(new RowMaterialQuantityDataTable(ds.Tables["RowMaterialQuantity"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableMRC_HT = ((MRC_HTDataTable)(this.Tables["MRC_HT"]));
            if ((this.tableMRC_HT != null)) {
                this.tableMRC_HT.InitVars();
            }
            this.tableRowMaterial = ((RowMaterialDataTable)(this.Tables["RowMaterial"]));
            if ((this.tableRowMaterial != null)) {
                this.tableRowMaterial.InitVars();
            }
            this.tableRowMaterialQuantity = ((RowMaterialQuantityDataTable)(this.Tables["RowMaterialQuantity"]));
            if ((this.tableRowMaterialQuantity != null)) {
                this.tableRowMaterialQuantity.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "dsRowMaterial";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dsRowMaterial.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableMRC_HT = new MRC_HTDataTable();
            this.Tables.Add(this.tableMRC_HT);
            this.tableRowMaterial = new RowMaterialDataTable();
            this.Tables.Add(this.tableRowMaterial);
            this.tableRowMaterialQuantity = new RowMaterialQuantityDataTable();
            this.Tables.Add(this.tableRowMaterialQuantity);
        }
        
        private bool ShouldSerializeMRC_HT() {
            return false;
        }
        
        private bool ShouldSerializeRowMaterial() {
            return false;
        }
        
        private bool ShouldSerializeRowMaterialQuantity() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void MRC_HTRowChangeEventHandler(object sender, MRC_HTRowChangeEvent e);
        
        public delegate void RowMaterialRowChangeEventHandler(object sender, RowMaterialRowChangeEvent e);
        
        public delegate void RowMaterialQuantityRowChangeEventHandler(object sender, RowMaterialQuantityRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class MRC_HTDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnItemNum;
            
            private DataColumn columnItemDrawNum;
            
            private DataColumn columnItemName;
            
            private DataColumn columnDeliveryOrderRequestQuantity;
            
            private DataColumn columnRowMaterialQuantityReflection;
            
            private DataColumn columnOrderNonInStorehouseReflection;
            
            private DataColumn columnOrderRequestReadyQuantityReflection;
            
            private DataColumn columnSafyRowMaterialQuantityReflection;
            
            private DataColumn columnMinimumOrderQuantityReflection;
            
            private DataColumn columnOrderGapQuantityReflection;
            
            private DataColumn columnVolumNum;
            
            private DataColumn columnProgressCondition;
            
            private DataColumn columnRegistrationPerson;
            
            private DataColumn columnRegistrationPersonID;
            
            private DataColumn columnRegistrationDate;
            
            private DataColumn columnUpdatingPerson;
            
            private DataColumn columnUpdatingPersonID;
            
            private DataColumn columnUpdatingDate;
            
            internal MRC_HTDataTable() : 
                    base("MRC_HT") {
                this.InitClass();
            }
            
            internal MRC_HTDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn ItemNumColumn {
                get {
                    return this.columnItemNum;
                }
            }
            
            internal DataColumn ItemDrawNumColumn {
                get {
                    return this.columnItemDrawNum;
                }
            }
            
            internal DataColumn ItemNameColumn {
                get {
                    return this.columnItemName;
                }
            }
            
            internal DataColumn DeliveryOrderRequestQuantityColumn {
                get {
                    return this.columnDeliveryOrderRequestQuantity;
                }
            }
            
            internal DataColumn RowMaterialQuantityReflectionColumn {
                get {
                    return this.columnRowMaterialQuantityReflection;
                }
            }
            
            internal DataColumn OrderNonInStorehouseReflectionColumn {
                get {
                    return this.columnOrderNonInStorehouseReflection;
                }
            }
            
            internal DataColumn OrderRequestReadyQuantityReflectionColumn {
                get {
                    return this.columnOrderRequestReadyQuantityReflection;
                }
            }
            
            internal DataColumn SafyRowMaterialQuantityReflectionColumn {
                get {
                    return this.columnSafyRowMaterialQuantityReflection;
                }
            }
            
            internal DataColumn MinimumOrderQuantityReflectionColumn {
                get {
                    return this.columnMinimumOrderQuantityReflection;
                }
            }
            
            internal DataColumn OrderGapQuantityReflectionColumn {
                get {
                    return this.columnOrderGapQuantityReflection;
                }
            }
            
            internal DataColumn VolumNumColumn {
                get {
                    return this.columnVolumNum;
                }
            }
            
            internal DataColumn ProgressConditionColumn {
                get {
                    return this.columnProgressCondition;
                }
            }
            
            internal DataColumn RegistrationPersonColumn {
                get {
                    return this.columnRegistrationPerson;
                }
            }
            
            internal DataColumn RegistrationPersonIDColumn {
                get {
                    return this.columnRegistrationPersonID;
                }
            }
            
            internal DataColumn RegistrationDateColumn {
                get {
                    return this.columnRegistrationDate;
                }
            }
            
            internal DataColumn UpdatingPersonColumn {
                get {
                    return this.columnUpdatingPerson;
                }
            }
            
            internal DataColumn UpdatingPersonIDColumn {
                get {
                    return this.columnUpdatingPersonID;
                }
            }
            
            internal DataColumn UpdatingDateColumn {
                get {
                    return this.columnUpdatingDate;
                }
            }
            
            public MRC_HTRow this[int index] {
                get {
                    return ((MRC_HTRow)(this.Rows[index]));
                }
            }
            
            public event MRC_HTRowChangeEventHandler MRC_HTRowChanged;
            
            public event MRC_HTRowChangeEventHandler MRC_HTRowChanging;
            
            public event MRC_HTRowChangeEventHandler MRC_HTRowDeleted;
            
            public event MRC_HTRowChangeEventHandler MRC_HTRowDeleting;
            
            public void AddMRC_HTRow(MRC_HTRow row) {
                this.Rows.Add(row);
            }
            
            public MRC_HTRow AddMRC_HTRow(
                        string ItemNum, 
                        string ItemDrawNum, 
                        string ItemName, 
                        System.Decimal DeliveryOrderRequestQuantity, 
                        bool RowMaterialQuantityReflection, 
                        bool OrderNonInStorehouseReflection, 
                        bool OrderRequestReadyQuantityReflection, 
                        bool SafyRowMaterialQuantityReflection, 
                        bool MinimumOrderQuantityReflection, 
                        bool OrderGapQuantityReflection, 
                        int VolumNum, 
                        string ProgressCondition, 
                        string RegistrationPerson, 
                        string RegistrationPersonID, 
                        System.DateTime RegistrationDate, 
                        string UpdatingPerson, 
                        string UpdatingPersonID, 
                        System.DateTime UpdatingDate) {
                MRC_HTRow rowMRC_HTRow = ((MRC_HTRow)(this.NewRow()));
                rowMRC_HTRow.ItemArray = new object[] {
                        ItemNum,
                        ItemDrawNum,
                        ItemName,
                        DeliveryOrderRequestQuantity,
                        RowMaterialQuantityReflection,
                        OrderNonInStorehouseReflection,
                        OrderRequestReadyQuantityReflection,
                        SafyRowMaterialQuantityReflection,
                        MinimumOrderQuantityReflection,
                        OrderGapQuantityReflection,
                        VolumNum,
                        ProgressCondition,
                        RegistrationPerson,
                        RegistrationPersonID,
                        RegistrationDate,
                        UpdatingPerson,
                        UpdatingPersonID,
                        UpdatingDate};
                this.Rows.Add(rowMRC_HTRow);
                return rowMRC_HTRow;
            }
            
            public MRC_HTRow FindByItemNum(string ItemNum) {
                return ((MRC_HTRow)(this.Rows.Find(new object[] {
                            ItemNum})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                MRC_HTDataTable cln = ((MRC_HTDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new MRC_HTDataTable();
            }
            
            internal void InitVars() {
                this.columnItemNum = this.Columns["ItemNum"];
                this.columnItemDrawNum = this.Columns["ItemDrawNum"];
                this.columnItemName = this.Columns["ItemName"];
                this.columnDeliveryOrderRequestQuantity = this.Columns["DeliveryOrderRequestQuantity"];
                this.columnRowMaterialQuantityReflection = this.Columns["RowMaterialQuantityReflection"];
                this.columnOrderNonInStorehouseReflection = this.Columns["OrderNonInStorehouseReflection"];
                this.columnOrderRequestReadyQuantityReflection = this.Columns["OrderRequestReadyQuantityReflection"];
                this.columnSafyRowMaterialQuantityReflection = this.Columns["SafyRowMaterialQuantityReflection"];
                this.columnMinimumOrderQuantityReflection = this.Columns["MinimumOrderQuantityReflection"];
                this.columnOrderGapQuantityReflection = this.Columns["OrderGapQuantityReflection"];
                this.columnVolumNum = this.Columns["VolumNum"];
                this.columnProgressCondition = this.Columns["ProgressCondition"];
                this.columnRegistrationPerson = this.Columns["RegistrationPerson"];
                this.columnRegistrationPersonID = this.Columns["RegistrationPersonID"];
                this.columnRegistrationDate = this.Columns["RegistrationDate"];
                this.columnUpdatingPerson = this.Columns["UpdatingPerson"];
                this.columnUpdatingPersonID = this.Columns["UpdatingPersonID"];
                this.columnUpdatingDate = this.Columns["UpdatingDate"];
            }
            
            private void InitClass() {
                this.columnItemNum = new DataColumn("ItemNum", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnItemNum);
                this.columnItemDrawNum = new DataColumn("ItemDrawNum", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnItemDrawNum);
                this.columnItemName = new DataColumn("ItemName", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnItemName);
                this.columnDeliveryOrderRequestQuantity = new DataColumn("DeliveryOrderRequestQuantity", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnDeliveryOrderRequestQuantity);
                this.columnRowMaterialQuantityReflection = new DataColumn("RowMaterialQuantityReflection", typeof(bool), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnRowMaterialQuantityReflection);
                this.columnOrderNonInStorehouseReflection = new DataColumn("OrderNonInStorehouseReflection", typeof(bool), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnOrderNonInStorehouseReflection);
                this.columnOrderRequestReadyQuantityReflection = new DataColumn("OrderRequestReadyQuantityReflection", typeof(bool), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnOrderRequestReadyQuantityReflection);
                this.columnSafyRowMaterialQuantityReflection = new DataColumn("SafyRowMaterialQuantityReflection", typeof(bool), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnSafyRowMaterialQuantityReflection);
                this.columnMinimumOrderQuantityReflection = new DataColumn("MinimumOrderQuantityReflection", typeof(bool), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnMinimumOrderQuantityReflection);
                this.columnOrderGapQuantityReflection = new DataColumn("OrderGapQuantityReflection", typeof(bool), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnOrderGapQuantityReflection);
                this.columnVolumNum = new DataColumn("VolumNum", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnVolumNum);
                this.columnProgressCondition = new DataColumn("ProgressCondition", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnProgressCondition);
                this.columnRegistrationPerson = new DataColumn("RegistrationPerson", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnRegistrationPerson);
                this.columnRegistrationPersonID = new DataColumn("RegistrationPersonID", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnRegistrationPersonID);
                this.columnRegistrationDate = new DataColumn("RegistrationDate", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnRegistrationDate);
                this.columnUpdatingPerson = new DataColumn("UpdatingPerson", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnUpdatingPerson);
                this.columnUpdatingPersonID = new DataColumn("UpdatingPersonID", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnUpdatingPersonID);
                this.columnUpdatingDate = new DataColumn("UpdatingDate", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnUpdatingDate);
                this.Constraints.Add(new UniqueConstraint("dsRowMaterialKey1", new DataColumn[] {
                                this.columnItemNum}, true));
                this.columnItemNum.AllowDBNull = false;
                this.columnItemNum.Unique = true;
            }
            
            public MRC_HTRow NewMRC_HTRow() {
                return ((MRC_HTRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new MRC_HTRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(MRC_HTRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.MRC_HTRowChanged != null)) {
                    this.MRC_HTRowChanged(this, new MRC_HTRowChangeEvent(((MRC_HTRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.MRC_HTRowChanging != null)) {
                    this.MRC_HTRowChanging(this, new MRC_HTRowChangeEvent(((MRC_HTRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.MRC_HTRowDeleted != null)) {
                    this.MRC_HTRowDeleted(this, new MRC_HTRowChangeEvent(((MRC_HTRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.MRC_HTRowDeleting != null)) {
                    this.MRC_HTRowDeleting(this, new MRC_HTRowChangeEvent(((MRC_HTRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveMRC_HTRow(MRC_HTRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class MRC_HTRow : DataRow {
            
            private MRC_HTDataTable tableMRC_HT;
            
            internal MRC_HTRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableMRC_HT = ((MRC_HTDataTable)(this.Table));
            }
            
            public string ItemNum {
                get {
                    return ((string)(this[this.tableMRC_HT.ItemNumColumn]));
                }
                set {
                    this[this.tableMRC_HT.ItemNumColumn] = value;
                }
            }
            
            public string ItemDrawNum {
                get {
                    try {
                        return ((string)(this[this.tableMRC_HT.ItemDrawNumColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableMRC_HT.ItemDrawNumColumn] = value;
                }
            }
            
            public string ItemName {
                get {
                    try {
                        return ((string)(this[this.tableMRC_HT.ItemNameColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableMRC_HT.ItemNameColumn] = value;
                }
            }
            
            public System.Decimal DeliveryOrderRequestQuantity {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableMRC_HT.DeliveryOrderRequestQuantityColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableMRC_HT.DeliveryOrderRequestQuantityColumn] = value;
                }
            }
            
            public bool RowMaterialQuantityReflection {
                get {
                    try {
                        return ((bool)(this[this.tableMRC_HT.RowMaterialQuantityReflectionColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableMRC_HT.RowMaterialQuantityReflectionColumn] = value;
                }
            }
            
            public bool OrderNonInStorehouseReflection {
                get {
                    try {
                        return ((bool)(this[this.tableMRC_HT.OrderNonInStorehouseReflectionColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableMRC_HT.OrderNonInStorehouseReflectionColumn] = value;
                }
            }
            
            public bool OrderRequestReadyQuantityReflection {
                get {
                    try {
                        return ((bool)(this[this.tableMRC_HT.OrderRequestReadyQuantityReflectionColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableMRC_HT.OrderRequestReadyQuantityReflectionColumn] = value;
                }
            }
            
            public bool SafyRowMaterialQuantityReflection {
                get {
                    try {
                        return ((bool)(this[this.tableMRC_HT.SafyRowMaterialQuantityReflectionColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableMRC_HT.SafyRowMaterialQuantityReflectionColumn] = value;
                }
            }
            
            public bool MinimumOrderQuantityReflection {
                get {
                    try {
                        return ((bool)(this[this.tableMRC_HT.MinimumOrderQuantityReflectionColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableMRC_HT.MinimumOrderQuantityReflectionColumn] = value;
                }
            }
            
            public bool OrderGapQuantityReflection {
                get {
                    try {
                        return ((bool)(this[this.tableMRC_HT.OrderGapQuantityReflectionColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableMRC_HT.OrderGapQuantityReflectionColumn] = value;
                }
            }
            
            public int VolumNum {
                get {
                    try {
                        return ((int)(this[this.tableMRC_HT.VolumNumColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableMRC_HT.VolumNumColumn] = value;
                }
            }
            
            public string ProgressCondition {
                get {
                    try {
                        return ((string)(this[this.tableMRC_HT.ProgressConditionColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableMRC_HT.ProgressConditionColumn] = value;
                }
            }
            
            public string RegistrationPerson {
                get {
                    try {
                        return ((string)(this[this.tableMRC_HT.RegistrationPersonColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableMRC_HT.RegistrationPersonColumn] = value;
                }
            }
            
            public string RegistrationPersonID {
                get {
                    try {
                        return ((string)(this[this.tableMRC_HT.RegistrationPersonIDColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableMRC_HT.RegistrationPersonIDColumn] = value;
                }
            }
            
            public System.DateTime RegistrationDate {
                get {
                    try {
                        return ((System.DateTime)(this[this.tableMRC_HT.RegistrationDateColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableMRC_HT.RegistrationDateColumn] = value;
                }
            }
            
            public string UpdatingPerson {
                get {
                    try {
                        return ((string)(this[this.tableMRC_HT.UpdatingPersonColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableMRC_HT.UpdatingPersonColumn] = value;
                }
            }
            
            public string UpdatingPersonID {
                get {
                    try {
                        return ((string)(this[this.tableMRC_HT.UpdatingPersonIDColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableMRC_HT.UpdatingPersonIDColumn] = value;
                }
            }
            
            public System.DateTime UpdatingDate {
                get {
                    try {
                        return ((System.DateTime)(this[this.tableMRC_HT.UpdatingDateColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableMRC_HT.UpdatingDateColumn] = value;
                }
            }
            
            public bool IsItemDrawNumNull() {
                return this.IsNull(this.tableMRC_HT.ItemDrawNumColumn);
            }
            
            public void SetItemDrawNumNull() {
                this[this.tableMRC_HT.ItemDrawNumColumn] = System.Convert.DBNull;
            }
            
            public bool IsItemNameNull() {
                return this.IsNull(this.tableMRC_HT.ItemNameColumn);
            }
            
            public void SetItemNameNull() {
                this[this.tableMRC_HT.ItemNameColumn] = System.Convert.DBNull;
            }
            
            public bool IsDeliveryOrderRequestQuantityNull() {
                return this.IsNull(this.tableMRC_HT.DeliveryOrderRequestQuantityColumn);
            }
            
            public void SetDeliveryOrderRequestQuantityNull() {
                this[this.tableMRC_HT.DeliveryOrderRequestQuantityColumn] = System.Convert.DBNull;
            }
            
            public bool IsRowMaterialQuantityReflectionNull() {
                return this.IsNull(this.tableMRC_HT.RowMaterialQuantityReflectionColumn);
            }
            
            public void SetRowMaterialQuantityReflectionNull() {
                this[this.tableMRC_HT.RowMaterialQuantityReflectionColumn] = System.Convert.DBNull;
            }
            
            public bool IsOrderNonInStorehouseReflectionNull() {
                return this.IsNull(this.tableMRC_HT.OrderNonInStorehouseReflectionColumn);
            }
            
            public void SetOrderNonInStorehouseReflectionNull() {
                this[this.tableMRC_HT.OrderNonInStorehouseReflectionColumn] = System.Convert.DBNull;
            }
            
            public bool IsOrderRequestReadyQuantityReflectionNull() {
                return this.IsNull(this.tableMRC_HT.OrderRequestReadyQuantityReflectionColumn);
            }
            
            public void SetOrderRequestReadyQuantityReflectionNull() {
                this[this.tableMRC_HT.OrderRequestReadyQuantityReflectionColumn] = System.Convert.DBNull;
            }
            
            public bool IsSafyRowMaterialQuantityReflectionNull() {
                return this.IsNull(this.tableMRC_HT.SafyRowMaterialQuantityReflectionColumn);
            }
            
            public void SetSafyRowMaterialQuantityReflectionNull() {
                this[this.tableMRC_HT.SafyRowMaterialQuantityReflectionColumn] = System.Convert.DBNull;
            }
            
            public bool IsMinimumOrderQuantityReflectionNull() {
                return this.IsNull(this.tableMRC_HT.MinimumOrderQuantityReflectionColumn);
            }
            
            public void SetMinimumOrderQuantityReflectionNull() {
                this[this.tableMRC_HT.MinimumOrderQuantityReflectionColumn] = System.Convert.DBNull;
            }
            
            public bool IsOrderGapQuantityReflectionNull() {
                return this.IsNull(this.tableMRC_HT.OrderGapQuantityReflectionColumn);
            }
            
            public void SetOrderGapQuantityReflectionNull() {
                this[this.tableMRC_HT.OrderGapQuantityReflectionColumn] = System.Convert.DBNull;
            }
            
            public bool IsVolumNumNull() {
                return this.IsNull(this.tableMRC_HT.VolumNumColumn);
            }
            
            public void SetVolumNumNull() {
                this[this.tableMRC_HT.VolumNumColumn] = System.Convert.DBNull;
            }
            
            public bool IsProgressConditionNull() {
                return this.IsNull(this.tableMRC_HT.ProgressConditionColumn);
            }
            
            public void SetProgressConditionNull() {
                this[this.tableMRC_HT.ProgressConditionColumn] = System.Convert.DBNull;
            }
            
            public bool IsRegistrationPersonNull() {
                return this.IsNull(this.tableMRC_HT.RegistrationPersonColumn);
            }
            
            public void SetRegistrationPersonNull() {
                this[this.tableMRC_HT.RegistrationPersonColumn] = System.Convert.DBNull;
            }
            
            public bool IsRegistrationPersonIDNull() {
                return this.IsNull(this.tableMRC_HT.RegistrationPersonIDColumn);
            }
            
            public void SetRegistrationPersonIDNull() {
                this[this.tableMRC_HT.RegistrationPersonIDColumn] = System.Convert.DBNull;
            }
            
            public bool IsRegistrationDateNull() {
                return this.IsNull(this.tableMRC_HT.RegistrationDateColumn);
            }
            
            public void SetRegistrationDateNull() {
                this[this.tableMRC_HT.RegistrationDateColumn] = System.Convert.DBNull;
            }
            
            public bool IsUpdatingPersonNull() {
                return this.IsNull(this.tableMRC_HT.UpdatingPersonColumn);
            }
            
            public void SetUpdatingPersonNull() {
                this[this.tableMRC_HT.UpdatingPersonColumn] = System.Convert.DBNull;
            }
            
            public bool IsUpdatingPersonIDNull() {
                return this.IsNull(this.tableMRC_HT.UpdatingPersonIDColumn);
            }
            
            public void SetUpdatingPersonIDNull() {
                this[this.tableMRC_HT.UpdatingPersonIDColumn] = System.Convert.DBNull;
            }
            
            public bool IsUpdatingDateNull() {
                return this.IsNull(this.tableMRC_HT.UpdatingDateColumn);
            }
            
            public void SetUpdatingDateNull() {
                this[this.tableMRC_HT.UpdatingDateColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class MRC_HTRowChangeEvent : EventArgs {
            
            private MRC_HTRow eventRow;
            
            private DataRowAction eventAction;
            
            public MRC_HTRowChangeEvent(MRC_HTRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public MRC_HTRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class RowMaterialDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnItemNum;
            
            private DataColumn columnItemDrawNum;
            
            private DataColumn columnItemName;

			private DataColumn columnUnit;

			 private DataColumn columnStandard;
            
            private DataColumn columnTotalQuantity;
            
            private DataColumn columnPSQuantity;
            
            private DataColumn columnRMSQuantity;
            
            private DataColumn columnWorkQuantity;
            
            private DataColumn columnRemainderQuantity;
            
            private DataColumn columnPureQuantity;
            
            private DataColumn columnOutRowQuantity;
            
            private DataColumn columnOutWorkQuantity;
            
            private DataColumn columnOutRemainderQuantity;
            
            private DataColumn columnRowMaterialQuantityReflection;
            
            private DataColumn columnRowMaterialReadyQuantity;
            
            private DataColumn columnOrderNonInStorehouseReflection;
            
            private DataColumn columnOrderRequestReadyQuantityReflection;
            
            private DataColumn columnFactRowMaterialQuantityReflection;
            
            private DataColumn columnSafyRowMaterialQuantityReflection;
            
            private DataColumn columnMinimumOrderQuantityReflection;
            
            private DataColumn columnOrderGapQuantityReflection;
            
            private DataColumn columnDeliveryOrderRequestQuantity;
            
            internal RowMaterialDataTable() : 
                    base("RowMaterial") {
                this.InitClass();
            }
            
            internal RowMaterialDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn ItemNumColumn {
                get {
                    return this.columnItemNum;
                }
            }
            
            internal DataColumn ItemDrawNumColumn {
                get {
                    return this.columnItemDrawNum;
                }
            }
            
            internal DataColumn ItemNameColumn {
                get {
                    return this.columnItemName;
                }
            }

			internal DataColumn UnitColumn 
			{
				get 
				{
					return this.columnUnit;
				}
			}

			internal DataColumn StandardColumn 
			{
				get 
				{
					return this.columnStandard;
				}
			}
            
            internal DataColumn TotalQuantityColumn {
                get {
                    return this.columnTotalQuantity;
                }
            }
            
            internal DataColumn PSQuantityColumn {
                get {
                    return this.columnPSQuantity;
                }
            }
            
            internal DataColumn RMSQuantityColumn {
                get {
                    return this.columnRMSQuantity;
                }
            }
            
            internal DataColumn WorkQuantityColumn {
                get {
                    return this.columnWorkQuantity;
                }
            }
            
            internal DataColumn RemainderQuantityColumn {
                get {
                    return this.columnRemainderQuantity;
                }
            }
            
            internal DataColumn PureQuantityColumn {
                get {
                    return this.columnPureQuantity;
                }
            }
            
            internal DataColumn OutRowQuantityColumn {
                get {
                    return this.columnOutRowQuantity;
                }
            }
            
            internal DataColumn OutWorkQuantityColumn {
                get {
                    return this.columnOutWorkQuantity;
                }
            }
            
            internal DataColumn OutRemainderQuantityColumn {
                get {
                    return this.columnOutRemainderQuantity;
                }
            }
            
            internal DataColumn RowMaterialQuantityReflectionColumn {
                get {
                    return this.columnRowMaterialQuantityReflection;
                }
            }
            
            internal DataColumn RowMaterialReadyQuantityColumn {
                get {
                    return this.columnRowMaterialReadyQuantity;
                }
            }
            
            internal DataColumn OrderNonInStorehouseReflectionColumn {
                get {
                    return this.columnOrderNonInStorehouseReflection;
                }
            }
            
            internal DataColumn OrderRequestReadyQuantityReflectionColumn {
                get {
                    return this.columnOrderRequestReadyQuantityReflection;
                }
            }
            
            internal DataColumn FactRowMaterialQuantityReflectionColumn {
                get {
                    return this.columnFactRowMaterialQuantityReflection;
                }
            }
            
            internal DataColumn SafyRowMaterialQuantityReflectionColumn {
                get {
                    return this.columnSafyRowMaterialQuantityReflection;
                }
            }
            
            internal DataColumn MinimumOrderQuantityReflectionColumn {
                get {
                    return this.columnMinimumOrderQuantityReflection;
                }
            }
            
            internal DataColumn OrderGapQuantityReflectionColumn {
                get {
                    return this.columnOrderGapQuantityReflection;
                }
            }
            
            internal DataColumn DeliveryOrderRequestQuantityColumn {
                get {
                    return this.columnDeliveryOrderRequestQuantity;
                }
            }
            
            public RowMaterialRow this[int index] {
                get {
                    return ((RowMaterialRow)(this.Rows[index]));
                }
            }
            
            public event RowMaterialRowChangeEventHandler RowMaterialRowChanged;
            
            public event RowMaterialRowChangeEventHandler RowMaterialRowChanging;
            
            public event RowMaterialRowChangeEventHandler RowMaterialRowDeleted;
            
            public event RowMaterialRowChangeEventHandler RowMaterialRowDeleting;
            
            public void AddRowMaterialRow(RowMaterialRow row) {
                this.Rows.Add(row);
            }
            
            public RowMaterialRow AddRowMaterialRow(
                        string ItemNum, 
                        string ItemDrawNum, 
                        string ItemName, 
						string Unit, 
						string Standard, 
                        System.Decimal TotalQuantity, 
                        System.Decimal PSQuantity, 
                        System.Decimal RMSQuantity, 
                        System.Decimal WorkQuantity, 
                        System.Decimal RemainderQuantity, 
                        System.Decimal PureQuantity, 
                        System.Decimal OutRowQuantity, 
                        System.Decimal OutWorkQuantity, 
                        System.Decimal OutRemainderQuantity, 
                        System.Decimal RowMaterialQuantityReflection, 
                        System.Decimal RowMaterialReadyQuantity, 
                        System.Decimal OrderNonInStorehouseReflection, 
                        System.Decimal OrderRequestReadyQuantityReflection, 
                        System.Decimal FactRowMaterialQuantityReflection, 
                        System.Decimal SafyRowMaterialQuantityReflection, 
                        System.Decimal MinimumOrderQuantityReflection, 
                        System.Decimal OrderGapQuantityReflection, 
                        System.Decimal DeliveryOrderRequestQuantity) {
                RowMaterialRow rowRowMaterialRow = ((RowMaterialRow)(this.NewRow()));
                rowRowMaterialRow.ItemArray = new object[] {
                        ItemNum,
                        ItemDrawNum,
                        ItemName,
					    Unit, 
						Standard,
                        TotalQuantity,
                        PSQuantity,
                        RMSQuantity,
                        WorkQuantity,
                        RemainderQuantity,
                        PureQuantity,
                        OutRowQuantity,
                        OutWorkQuantity,
                        OutRemainderQuantity,
                        RowMaterialQuantityReflection,
                        RowMaterialReadyQuantity,
                        OrderNonInStorehouseReflection,
                        OrderRequestReadyQuantityReflection,
                        FactRowMaterialQuantityReflection,
                        SafyRowMaterialQuantityReflection,
                        MinimumOrderQuantityReflection,
                        OrderGapQuantityReflection,
                        DeliveryOrderRequestQuantity};
                this.Rows.Add(rowRowMaterialRow);
                return rowRowMaterialRow;
            }
            
            public RowMaterialRow FindByItemNum(string ItemNum) {
                return ((RowMaterialRow)(this.Rows.Find(new object[] {
                            ItemNum})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                RowMaterialDataTable cln = ((RowMaterialDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new RowMaterialDataTable();
            }
            
            internal void InitVars() {
                this.columnItemNum = this.Columns["ItemNum"];
                this.columnItemDrawNum = this.Columns["ItemDrawNum"];
                this.columnItemName = this.Columns["ItemName"];
				this.columnUnit = this.Columns["Unit"];
				this.columnStandard = this.Columns["Standard"];
                this.columnTotalQuantity = this.Columns["TotalQuantity"];
                this.columnPSQuantity = this.Columns["PSQuantity"];
                this.columnRMSQuantity = this.Columns["RMSQuantity"];
                this.columnWorkQuantity = this.Columns["WorkQuantity"];
                this.columnRemainderQuantity = this.Columns["RemainderQuantity"];
                this.columnPureQuantity = this.Columns["PureQuantity"];
                this.columnOutRowQuantity = this.Columns["OutRowQuantity"];
                this.columnOutWorkQuantity = this.Columns["OutWorkQuantity"];
                this.columnOutRemainderQuantity = this.Columns["OutRemainderQuantity"];
                this.columnRowMaterialQuantityReflection = this.Columns["RowMaterialQuantityReflection"];
                this.columnRowMaterialReadyQuantity = this.Columns["RowMaterialReadyQuantity"];
                this.columnOrderNonInStorehouseReflection = this.Columns["OrderNonInStorehouseReflection"];
                this.columnOrderRequestReadyQuantityReflection = this.Columns["OrderRequestReadyQuantityReflection"];
                this.columnFactRowMaterialQuantityReflection = this.Columns["FactRowMaterialQuantityReflection"];
                this.columnSafyRowMaterialQuantityReflection = this.Columns["SafyRowMaterialQuantityReflection"];
                this.columnMinimumOrderQuantityReflection = this.Columns["MinimumOrderQuantityReflection"];
                this.columnOrderGapQuantityReflection = this.Columns["OrderGapQuantityReflection"];
                this.columnDeliveryOrderRequestQuantity = this.Columns["DeliveryOrderRequestQuantity"];
            }
            
            private void InitClass() {
                this.columnItemNum = new DataColumn("ItemNum", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnItemNum);
                this.columnItemDrawNum = new DataColumn("ItemDrawNum", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnItemDrawNum);
                this.columnItemName = new DataColumn("ItemName", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnItemName);
                
				this.columnUnit = new DataColumn("Unit", typeof(string), null, System.Data.MappingType.Element);
				this.Columns.Add(this.columnUnit);
				this.columnStandard = new DataColumn("Standard", typeof(string), null, System.Data.MappingType.Element);
				this.Columns.Add(this.columnStandard);			
				
				this.columnTotalQuantity = new DataColumn("TotalQuantity", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnTotalQuantity);
                this.columnPSQuantity = new DataColumn("PSQuantity", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPSQuantity);
                this.columnRMSQuantity = new DataColumn("RMSQuantity", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnRMSQuantity);
                this.columnWorkQuantity = new DataColumn("WorkQuantity", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnWorkQuantity);
                this.columnRemainderQuantity = new DataColumn("RemainderQuantity", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnRemainderQuantity);
                this.columnPureQuantity = new DataColumn("PureQuantity", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPureQuantity);
                this.columnOutRowQuantity = new DataColumn("OutRowQuantity", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnOutRowQuantity);
                this.columnOutWorkQuantity = new DataColumn("OutWorkQuantity", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnOutWorkQuantity);
                this.columnOutRemainderQuantity = new DataColumn("OutRemainderQuantity", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnOutRemainderQuantity);
                this.columnRowMaterialQuantityReflection = new DataColumn("RowMaterialQuantityReflection", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnRowMaterialQuantityReflection);
                this.columnRowMaterialReadyQuantity = new DataColumn("RowMaterialReadyQuantity", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnRowMaterialReadyQuantity);
                this.columnOrderNonInStorehouseReflection = new DataColumn("OrderNonInStorehouseReflection", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnOrderNonInStorehouseReflection);
                this.columnOrderRequestReadyQuantityReflection = new DataColumn("OrderRequestReadyQuantityReflection", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnOrderRequestReadyQuantityReflection);
                this.columnFactRowMaterialQuantityReflection = new DataColumn("FactRowMaterialQuantityReflection", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnFactRowMaterialQuantityReflection);
                this.columnSafyRowMaterialQuantityReflection = new DataColumn("SafyRowMaterialQuantityReflection", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnSafyRowMaterialQuantityReflection);
                this.columnMinimumOrderQuantityReflection = new DataColumn("MinimumOrderQuantityReflection", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnMinimumOrderQuantityReflection);
                this.columnOrderGapQuantityReflection = new DataColumn("OrderGapQuantityReflection", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnOrderGapQuantityReflection);
                this.columnDeliveryOrderRequestQuantity = new DataColumn("DeliveryOrderRequestQuantity", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnDeliveryOrderRequestQuantity);
                this.Constraints.Add(new UniqueConstraint("dsRowMaterialKey2", new DataColumn[] {
                                this.columnItemNum}, true));
                this.columnItemNum.AllowDBNull = false;
                this.columnItemNum.Unique = true;
            }
            
            public RowMaterialRow NewRowMaterialRow() {
                return ((RowMaterialRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new RowMaterialRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(RowMaterialRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.RowMaterialRowChanged != null)) {
                    this.RowMaterialRowChanged(this, new RowMaterialRowChangeEvent(((RowMaterialRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.RowMaterialRowChanging != null)) {
                    this.RowMaterialRowChanging(this, new RowMaterialRowChangeEvent(((RowMaterialRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.RowMaterialRowDeleted != null)) {
                    this.RowMaterialRowDeleted(this, new RowMaterialRowChangeEvent(((RowMaterialRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.RowMaterialRowDeleting != null)) {
                    this.RowMaterialRowDeleting(this, new RowMaterialRowChangeEvent(((RowMaterialRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveRowMaterialRow(RowMaterialRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class RowMaterialRow : DataRow {
            
            private RowMaterialDataTable tableRowMaterial;
            
            internal RowMaterialRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableRowMaterial = ((RowMaterialDataTable)(this.Table));
            }
            
            public string ItemNum {
                get {
                    return ((string)(this[this.tableRowMaterial.ItemNumColumn]));
                }
                set {
                    this[this.tableRowMaterial.ItemNumColumn] = value;
                }
            }
            
            public string ItemDrawNum {
                get {
                    try {
                        return ((string)(this[this.tableRowMaterial.ItemDrawNumColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableRowMaterial.ItemDrawNumColumn] = value;
                }
            }
            
            public string ItemName {
                get {
                    try {
                        return ((string)(this[this.tableRowMaterial.ItemNameColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableRowMaterial.ItemNameColumn] = value;
                }
            }



			public string Unit
			{
				get 
				{
					try 
					{
						return ((string)(this[this.tableRowMaterial.UnitColumn]));
					}
					catch (InvalidCastException e) 
					{
						throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
					}
				}
				set 
				{
					this[this.tableRowMaterial.UnitColumn] = value;
				}
			}
            
			public string Standard 
			{
				get 
				{
					try 
					{
						return ((string)(this[this.tableRowMaterial.StandardColumn]));
					}
					catch (InvalidCastException e) 
					{
						throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
					}
				}
				set 
				{
					this[this.tableRowMaterial.StandardColumn] = value;
				}
			}
            
            public System.Decimal TotalQuantity {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableRowMaterial.TotalQuantityColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableRowMaterial.TotalQuantityColumn] = value;
                }
            }
            
            public System.Decimal PSQuantity {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableRowMaterial.PSQuantityColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableRowMaterial.PSQuantityColumn] = value;
                }
            }
            
            public System.Decimal RMSQuantity {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableRowMaterial.RMSQuantityColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableRowMaterial.RMSQuantityColumn] = value;
                }
            }
            
            public System.Decimal WorkQuantity {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableRowMaterial.WorkQuantityColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableRowMaterial.WorkQuantityColumn] = value;
                }
            }
            
            public System.Decimal RemainderQuantity {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableRowMaterial.RemainderQuantityColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableRowMaterial.RemainderQuantityColumn] = value;
                }
            }
            
            public System.Decimal PureQuantity {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableRowMaterial.PureQuantityColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableRowMaterial.PureQuantityColumn] = value;
                }
            }
            
            public System.Decimal OutRowQuantity {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableRowMaterial.OutRowQuantityColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableRowMaterial.OutRowQuantityColumn] = value;
                }
            }
            
            public System.Decimal OutWorkQuantity {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableRowMaterial.OutWorkQuantityColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableRowMaterial.OutWorkQuantityColumn] = value;
                }
            }
            
            public System.Decimal OutRemainderQuantity {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableRowMaterial.OutRemainderQuantityColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableRowMaterial.OutRemainderQuantityColumn] = value;
                }
            }
            
            public System.Decimal RowMaterialQuantityReflection {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableRowMaterial.RowMaterialQuantityReflectionColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableRowMaterial.RowMaterialQuantityReflectionColumn] = value;
                }
            }
            
            public System.Decimal RowMaterialReadyQuantity {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableRowMaterial.RowMaterialReadyQuantityColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableRowMaterial.RowMaterialReadyQuantityColumn] = value;
                }
            }
            
            public System.Decimal OrderNonInStorehouseReflection {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableRowMaterial.OrderNonInStorehouseReflectionColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableRowMaterial.OrderNonInStorehouseReflectionColumn] = value;
                }
            }
            
            public System.Decimal OrderRequestReadyQuantityReflection {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableRowMaterial.OrderRequestReadyQuantityReflectionColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableRowMaterial.OrderRequestReadyQuantityReflectionColumn] = value;
                }
            }
            
            public System.Decimal FactRowMaterialQuantityReflection {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableRowMaterial.FactRowMaterialQuantityReflectionColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableRowMaterial.FactRowMaterialQuantityReflectionColumn] = value;
                }
            }
            
            public System.Decimal SafyRowMaterialQuantityReflection {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableRowMaterial.SafyRowMaterialQuantityReflectionColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableRowMaterial.SafyRowMaterialQuantityReflectionColumn] = value;
                }
            }
            
            public System.Decimal MinimumOrderQuantityReflection {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableRowMaterial.MinimumOrderQuantityReflectionColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableRowMaterial.MinimumOrderQuantityReflectionColumn] = value;
                }
            }
            
            public System.Decimal OrderGapQuantityReflection {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableRowMaterial.OrderGapQuantityReflectionColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableRowMaterial.OrderGapQuantityReflectionColumn] = value;
                }
            }
            
            public System.Decimal DeliveryOrderRequestQuantity {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableRowMaterial.DeliveryOrderRequestQuantityColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableRowMaterial.DeliveryOrderRequestQuantityColumn] = value;
                }
            }
            
            public bool IsItemDrawNumNull() {
                return this.IsNull(this.tableRowMaterial.ItemDrawNumColumn);
            }
            
            public void SetItemDrawNumNull() {
                this[this.tableRowMaterial.ItemDrawNumColumn] = System.Convert.DBNull;
            }

                 
            public bool IsItemNameNull() {
                return this.IsNull(this.tableRowMaterial.ItemNameColumn);
            }
            
            public void SetItemNameNull() {
                this[this.tableRowMaterial.ItemNameColumn] = System.Convert.DBNull;
            }
            
			public bool IsUnitNull() 
			{
				return this.IsNull(this.tableRowMaterial.UnitColumn);
			}
            
			public void SetUnitNull() 
			{
				this[this.tableRowMaterial.UnitColumn] = System.Convert.DBNull;
			}


			public bool IsStandardNull() 
			{
				return this.IsNull(this.tableRowMaterial.StandardColumn);
			}
            
			public void SetStandardNull() 
			{
				this[this.tableRowMaterial.StandardColumn] = System.Convert.DBNull;
			}



            public bool IsTotalQuantityNull() {
                return this.IsNull(this.tableRowMaterial.TotalQuantityColumn);
            }
            
            public void SetTotalQuantityNull() {
                this[this.tableRowMaterial.TotalQuantityColumn] = System.Convert.DBNull;
            }
            
            public bool IsPSQuantityNull() {
                return this.IsNull(this.tableRowMaterial.PSQuantityColumn);
            }
            
            public void SetPSQuantityNull() {
                this[this.tableRowMaterial.PSQuantityColumn] = System.Convert.DBNull;
            }
            
            public bool IsRMSQuantityNull() {
                return this.IsNull(this.tableRowMaterial.RMSQuantityColumn);
            }
            
            public void SetRMSQuantityNull() {
                this[this.tableRowMaterial.RMSQuantityColumn] = System.Convert.DBNull;
            }
            
            public bool IsWorkQuantityNull() {
                return this.IsNull(this.tableRowMaterial.WorkQuantityColumn);
            }
            
            public void SetWorkQuantityNull() {
                this[this.tableRowMaterial.WorkQuantityColumn] = System.Convert.DBNull;
            }
            
            public bool IsRemainderQuantityNull() {
                return this.IsNull(this.tableRowMaterial.RemainderQuantityColumn);
            }
            
            public void SetRemainderQuantityNull() {
                this[this.tableRowMaterial.RemainderQuantityColumn] = System.Convert.DBNull;
            }
            
            public bool IsPureQuantityNull() {
                return this.IsNull(this.tableRowMaterial.PureQuantityColumn);
            }
            
            public void SetPureQuantityNull() {
                this[this.tableRowMaterial.PureQuantityColumn] = System.Convert.DBNull;
            }
            
            public bool IsOutRowQuantityNull() {
                return this.IsNull(this.tableRowMaterial.OutRowQuantityColumn);
            }
            
            public void SetOutRowQuantityNull() {
                this[this.tableRowMaterial.OutRowQuantityColumn] = System.Convert.DBNull;
            }
            
            public bool IsOutWorkQuantityNull() {
                return this.IsNull(this.tableRowMaterial.OutWorkQuantityColumn);
            }
            
            public void SetOutWorkQuantityNull() {
                this[this.tableRowMaterial.OutWorkQuantityColumn] = System.Convert.DBNull;
            }
            
            public bool IsOutRemainderQuantityNull() {
                return this.IsNull(this.tableRowMaterial.OutRemainderQuantityColumn);
            }
            
            public void SetOutRemainderQuantityNull() {
                this[this.tableRowMaterial.OutRemainderQuantityColumn] = System.Convert.DBNull;
            }
            
            public bool IsRowMaterialQuantityReflectionNull() {
                return this.IsNull(this.tableRowMaterial.RowMaterialQuantityReflectionColumn);
            }
            
            public void SetRowMaterialQuantityReflectionNull() {
                this[this.tableRowMaterial.RowMaterialQuantityReflectionColumn] = System.Convert.DBNull;
            }
            
            public bool IsRowMaterialReadyQuantityNull() {
                return this.IsNull(this.tableRowMaterial.RowMaterialReadyQuantityColumn);
            }
            
            public void SetRowMaterialReadyQuantityNull() {
                this[this.tableRowMaterial.RowMaterialReadyQuantityColumn] = System.Convert.DBNull;
            }
            
            public bool IsOrderNonInStorehouseReflectionNull() {
                return this.IsNull(this.tableRowMaterial.OrderNonInStorehouseReflectionColumn);
            }
            
            public void SetOrderNonInStorehouseReflectionNull() {
                this[this.tableRowMaterial.OrderNonInStorehouseReflectionColumn] = System.Convert.DBNull;
            }
            
            public bool IsOrderRequestReadyQuantityReflectionNull() {
                return this.IsNull(this.tableRowMaterial.OrderRequestReadyQuantityReflectionColumn);
            }
            
            public void SetOrderRequestReadyQuantityReflectionNull() {
                this[this.tableRowMaterial.OrderRequestReadyQuantityReflectionColumn] = System.Convert.DBNull;
            }
            
            public bool IsFactRowMaterialQuantityReflectionNull() {
                return this.IsNull(this.tableRowMaterial.FactRowMaterialQuantityReflectionColumn);
            }
            
            public void SetFactRowMaterialQuantityReflectionNull() {
                this[this.tableRowMaterial.FactRowMaterialQuantityReflectionColumn] = System.Convert.DBNull;
            }
            
            public bool IsSafyRowMaterialQuantityReflectionNull() {
                return this.IsNull(this.tableRowMaterial.SafyRowMaterialQuantityReflectionColumn);
            }
            
            public void SetSafyRowMaterialQuantityReflectionNull() {
                this[this.tableRowMaterial.SafyRowMaterialQuantityReflectionColumn] = System.Convert.DBNull;
            }
            
            public bool IsMinimumOrderQuantityReflectionNull() {
                return this.IsNull(this.tableRowMaterial.MinimumOrderQuantityReflectionColumn);
            }
            
            public void SetMinimumOrderQuantityReflectionNull() {
                this[this.tableRowMaterial.MinimumOrderQuantityReflectionColumn] = System.Convert.DBNull;
            }
            
            public bool IsOrderGapQuantityReflectionNull() {
                return this.IsNull(this.tableRowMaterial.OrderGapQuantityReflectionColumn);
            }
            
            public void SetOrderGapQuantityReflectionNull() {
                this[this.tableRowMaterial.OrderGapQuantityReflectionColumn] = System.Convert.DBNull;
            }
            
            public bool IsDeliveryOrderRequestQuantityNull() {
                return this.IsNull(this.tableRowMaterial.DeliveryOrderRequestQuantityColumn);
            }
            
            public void SetDeliveryOrderRequestQuantityNull() {
                this[this.tableRowMaterial.DeliveryOrderRequestQuantityColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class RowMaterialRowChangeEvent : EventArgs {
            
            private RowMaterialRow eventRow;
            
            private DataRowAction eventAction;
            
            public RowMaterialRowChangeEvent(RowMaterialRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public RowMaterialRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class RowMaterialQuantityDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnProductionPlanHistoryIndex;
            
            private DataColumn columnItemNum;
            
            private DataColumn columnItemDrawNum;
            
            private DataColumn columnItemName;
            
            private DataColumn columnProcessSequenceNum;
            
            private DataColumn columnProductionPlanQuantity;
            
            private DataColumn columnTotalWorkCompletionQuantity;
            
            internal RowMaterialQuantityDataTable() : 
                    base("RowMaterialQuantity") {
                this.InitClass();
            }
            
            internal RowMaterialQuantityDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn ProductionPlanHistoryIndexColumn {
                get {
                    return this.columnProductionPlanHistoryIndex;
                }
            }
            
            internal DataColumn ItemNumColumn {
                get {
                    return this.columnItemNum;
                }
            }
            
            internal DataColumn ItemDrawNumColumn {
                get {
                    return this.columnItemDrawNum;
                }
            }
            
            internal DataColumn ItemNameColumn {
                get {
                    return this.columnItemName;
                }
            }
            
            internal DataColumn ProcessSequenceNumColumn {
                get {
                    return this.columnProcessSequenceNum;
                }
            }
            
            internal DataColumn ProductionPlanQuantityColumn {
                get {
                    return this.columnProductionPlanQuantity;
                }
            }
            
            internal DataColumn TotalWorkCompletionQuantityColumn {
                get {
                    return this.columnTotalWorkCompletionQuantity;
                }
            }
            
            public RowMaterialQuantityRow this[int index] {
                get {
                    return ((RowMaterialQuantityRow)(this.Rows[index]));
                }
            }
            
            public event RowMaterialQuantityRowChangeEventHandler RowMaterialQuantityRowChanged;
            
            public event RowMaterialQuantityRowChangeEventHandler RowMaterialQuantityRowChanging;
            
            public event RowMaterialQuantityRowChangeEventHandler RowMaterialQuantityRowDeleted;
            
            public event RowMaterialQuantityRowChangeEventHandler RowMaterialQuantityRowDeleting;
            
            public void AddRowMaterialQuantityRow(RowMaterialQuantityRow row) {
                this.Rows.Add(row);
            }
            
            public RowMaterialQuantityRow AddRowMaterialQuantityRow(int ProductionPlanHistoryIndex, string ItemNum, string ItemDrawNum, string ItemName, int ProcessSequenceNum, System.Decimal ProductionPlanQuantity, System.Decimal TotalWorkCompletionQuantity) {
                RowMaterialQuantityRow rowRowMaterialQuantityRow = ((RowMaterialQuantityRow)(this.NewRow()));
                rowRowMaterialQuantityRow.ItemArray = new object[] {
                        ProductionPlanHistoryIndex,
                        ItemNum,
                        ItemDrawNum,
                        ItemName,
                        ProcessSequenceNum,
                        ProductionPlanQuantity,
                        TotalWorkCompletionQuantity};
                this.Rows.Add(rowRowMaterialQuantityRow);
                return rowRowMaterialQuantityRow;
            }
            
            public RowMaterialQuantityRow FindByProductionPlanHistoryIndex(int ProductionPlanHistoryIndex) {
                return ((RowMaterialQuantityRow)(this.Rows.Find(new object[] {
                            ProductionPlanHistoryIndex})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                RowMaterialQuantityDataTable cln = ((RowMaterialQuantityDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new RowMaterialQuantityDataTable();
            }
            
            internal void InitVars() {
                this.columnProductionPlanHistoryIndex = this.Columns["ProductionPlanHistoryIndex"];
                this.columnItemNum = this.Columns["ItemNum"];
                this.columnItemDrawNum = this.Columns["ItemDrawNum"];
                this.columnItemName = this.Columns["ItemName"];
                this.columnProcessSequenceNum = this.Columns["ProcessSequenceNum"];
                this.columnProductionPlanQuantity = this.Columns["ProductionPlanQuantity"];
                this.columnTotalWorkCompletionQuantity = this.Columns["TotalWorkCompletionQuantity"];
            }
            
            private void InitClass() {
                this.columnProductionPlanHistoryIndex = new DataColumn("ProductionPlanHistoryIndex", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnProductionPlanHistoryIndex);
                this.columnItemNum = new DataColumn("ItemNum", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnItemNum);
                this.columnItemDrawNum = new DataColumn("ItemDrawNum", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnItemDrawNum);
                this.columnItemName = new DataColumn("ItemName", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnItemName);
                this.columnProcessSequenceNum = new DataColumn("ProcessSequenceNum", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnProcessSequenceNum);
                this.columnProductionPlanQuantity = new DataColumn("ProductionPlanQuantity", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnProductionPlanQuantity);
                this.columnTotalWorkCompletionQuantity = new DataColumn("TotalWorkCompletionQuantity", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnTotalWorkCompletionQuantity);
                this.Constraints.Add(new UniqueConstraint("dsRowMaterialKey3", new DataColumn[] {
                                this.columnProductionPlanHistoryIndex}, true));
                this.columnProductionPlanHistoryIndex.AllowDBNull = false;
                this.columnProductionPlanHistoryIndex.Unique = true;
            }
            
            public RowMaterialQuantityRow NewRowMaterialQuantityRow() {
                return ((RowMaterialQuantityRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new RowMaterialQuantityRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(RowMaterialQuantityRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.RowMaterialQuantityRowChanged != null)) {
                    this.RowMaterialQuantityRowChanged(this, new RowMaterialQuantityRowChangeEvent(((RowMaterialQuantityRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.RowMaterialQuantityRowChanging != null)) {
                    this.RowMaterialQuantityRowChanging(this, new RowMaterialQuantityRowChangeEvent(((RowMaterialQuantityRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.RowMaterialQuantityRowDeleted != null)) {
                    this.RowMaterialQuantityRowDeleted(this, new RowMaterialQuantityRowChangeEvent(((RowMaterialQuantityRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.RowMaterialQuantityRowDeleting != null)) {
                    this.RowMaterialQuantityRowDeleting(this, new RowMaterialQuantityRowChangeEvent(((RowMaterialQuantityRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveRowMaterialQuantityRow(RowMaterialQuantityRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class RowMaterialQuantityRow : DataRow {
            
            private RowMaterialQuantityDataTable tableRowMaterialQuantity;
            
            internal RowMaterialQuantityRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableRowMaterialQuantity = ((RowMaterialQuantityDataTable)(this.Table));
            }
            
            public int ProductionPlanHistoryIndex {
                get {
                    return ((int)(this[this.tableRowMaterialQuantity.ProductionPlanHistoryIndexColumn]));
                }
                set {
                    this[this.tableRowMaterialQuantity.ProductionPlanHistoryIndexColumn] = value;
                }
            }
            
            public string ItemNum {
                get {
                    try {
                        return ((string)(this[this.tableRowMaterialQuantity.ItemNumColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableRowMaterialQuantity.ItemNumColumn] = value;
                }
            }
            
            public string ItemDrawNum {
                get {
                    try {
                        return ((string)(this[this.tableRowMaterialQuantity.ItemDrawNumColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableRowMaterialQuantity.ItemDrawNumColumn] = value;
                }
            }
            
            public string ItemName {
                get {
                    try {
                        return ((string)(this[this.tableRowMaterialQuantity.ItemNameColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableRowMaterialQuantity.ItemNameColumn] = value;
                }
            }
            
            public int ProcessSequenceNum {
                get {
                    try {
                        return ((int)(this[this.tableRowMaterialQuantity.ProcessSequenceNumColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableRowMaterialQuantity.ProcessSequenceNumColumn] = value;
                }
            }
            
            public System.Decimal ProductionPlanQuantity {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableRowMaterialQuantity.ProductionPlanQuantityColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableRowMaterialQuantity.ProductionPlanQuantityColumn] = value;
                }
            }
            
            public System.Decimal TotalWorkCompletionQuantity {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableRowMaterialQuantity.TotalWorkCompletionQuantityColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("이 값은 DBNull이므로 가져올 수 없습니다.", e);
                    }
                }
                set {
                    this[this.tableRowMaterialQuantity.TotalWorkCompletionQuantityColumn] = value;
                }
            }
            
            public bool IsItemNumNull() {
                return this.IsNull(this.tableRowMaterialQuantity.ItemNumColumn);
            }
            
            public void SetItemNumNull() {
                this[this.tableRowMaterialQuantity.ItemNumColumn] = System.Convert.DBNull;
            }
            
            public bool IsItemDrawNumNull() {
                return this.IsNull(this.tableRowMaterialQuantity.ItemDrawNumColumn);
            }
            
            public void SetItemDrawNumNull() {
                this[this.tableRowMaterialQuantity.ItemDrawNumColumn] = System.Convert.DBNull;
            }
            
            public bool IsItemNameNull() {
                return this.IsNull(this.tableRowMaterialQuantity.ItemNameColumn);
            }
            
            public void SetItemNameNull() {
                this[this.tableRowMaterialQuantity.ItemNameColumn] = System.Convert.DBNull;
            }
            
            public bool IsProcessSequenceNumNull() {
                return this.IsNull(this.tableRowMaterialQuantity.ProcessSequenceNumColumn);
            }
            
            public void SetProcessSequenceNumNull() {
                this[this.tableRowMaterialQuantity.ProcessSequenceNumColumn] = System.Convert.DBNull;
            }
            
            public bool IsProductionPlanQuantityNull() {
                return this.IsNull(this.tableRowMaterialQuantity.ProductionPlanQuantityColumn);
            }
            
            public void SetProductionPlanQuantityNull() {
                this[this.tableRowMaterialQuantity.ProductionPlanQuantityColumn] = System.Convert.DBNull;
            }
            
            public bool IsTotalWorkCompletionQuantityNull() {
                return this.IsNull(this.tableRowMaterialQuantity.TotalWorkCompletionQuantityColumn);
            }
            
            public void SetTotalWorkCompletionQuantityNull() {
                this[this.tableRowMaterialQuantity.TotalWorkCompletionQuantityColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class RowMaterialQuantityRowChangeEvent : EventArgs {
            
            private RowMaterialQuantityRow eventRow;
            
            private DataRowAction eventAction;
            
            public RowMaterialQuantityRowChangeEvent(RowMaterialQuantityRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public RowMaterialQuantityRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
